services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  vision-v2-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/vision-v2-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-central1
      - STACKYARD_GCP_VISION_PRODUCT_SET_ID=product-set-1
      - STACKYARD_GCP_VISION_PRODUCT_ID=product-1
      - STACKYARD_GCP_VISION_REFERENCE_IMAGE_ID=reference-image-1
      - STACKYARD_GCP_VISION_IMAGE_URI=gs://stackyard-inputs/image-1.jpg
      - STACKYARD_GCP_VISION_FILE_URI=gs://stackyard-inputs/file-1.pdf
      - STACKYARD_GCP_VISION_OUTPUT_URI=gs://stackyard-outputs/vision/
      - STACKYARD_GCP_VISION_IMPORT_CSV_URI=gs://stackyard-inputs/vision-import.csv
