services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  batch-basic:
    build:
      context: ../../../..
      dockerfile: examples/aws/batch/batch-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_COMPUTE_ENV=batch-basic-ce
      - STACKYARD_JOB_QUEUE=batch-basic-queue
      - STACKYARD_JOB_DEFINITION=batch-basic-jobdef
      - STACKYARD_JOB_NAME=batch-basic-job
