services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  phishingprotection-apiv1beta1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/phishingprotection-apiv1beta1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_NUMBER=123456789012
      - STACKYARD_GCP_PHISHING_URI=https://example.test/suspected-phishing
