services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  neptune-basic:
    build:
      context: ../../..
      dockerfile: examples/neptune/neptune-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_NEPTUNE_CLUSTER=neptune-basic-cluster
