services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  lightsail-basic:
    build:
      context: ../../..
      dockerfile: examples/lightsail/lightsail-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_AVAILABILITY_ZONE=us-east-1a
      - STACKYARD_INSTANCE_NAME=lightsail-basic-instance
