services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  ecr-advanced:
    build:
      context: ../../..
      dockerfile: examples/ecr/ecr-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_REPOSITORY_NAME=ecr-advanced-repo
      - STACKYARD_CACHE_PREFIX=ecr-advanced-cache
      - STACKYARD_TEMPLATE_PREFIX=ecr-advanced-template
