services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  resourcemanager-apiv2:
    build:
      context: ../../../..
      dockerfile: examples/gcp/resourcemanager-apiv2/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_FOLDER_PARENT=organizations/123456
      - STACKYARD_GCP_FOLDER_NAME=folders/1001
      - STACKYARD_GCP_DESTINATION_PARENT=folders/2000
