services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  timestream-advanced:
    build:
      context: ../../..
      dockerfile: examples/timestream/timestream-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_DB_CLUSTER_ID=cluster-000000000001
      - STACKYARD_DB_INSTANCE_ID=instance-000000000001
      - STACKYARD_RESOURCE_ARN=arn:aws:timestream-influxdb:us-east-1:123456789012:db-cluster/cluster-000000000001
