services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  cloudprofiler-apiv2:
    build:
      context: ../../../..
      dockerfile: examples/gcp/cloudprofiler-apiv2/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_PROFILER_PARENT=projects/stackyard
      - STACKYARD_GCP_PROFILE_ID=stackyard-profile
