services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  domains-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/domains-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-central1
      - STACKYARD_GCP_DOMAINS_DOMAIN_NAME=example.test
      - STACKYARD_GCP_DOMAINS_REGISTRATION_ID=example.test
      - STACKYARD_GCP_DOMAINS_TRANSFER_AUTH_CODE=transfer-code-123
