services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  eventarc-publishing-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/eventarc-publishing-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-central1
      - STACKYARD_GCP_EVENTARC_CHANNEL_ID=team-channel
      - STACKYARD_GCP_EVENTARC_CONNECTION_PROJECT_ID=partner
      - STACKYARD_GCP_EVENTARC_CONNECTION_ID=conn-1
      - STACKYARD_GCP_EVENTARC_MESSAGE_BUS_ID=team-bus
