services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  neptunedata:
    build:
      context: ../../../..
      dockerfile: examples/aws/neptunedata/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_NEPTUNEDATA_LOAD_ID=stackyard-load-job
