package server

type accessAnalyzerDataType struct {
	Name string
}

// AWS IAM Access Analyzer data types sourced from:
// https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_Types.html
var accessAnalyzerDataTypes = []accessAnalyzerDataType{
	{Name: "Access"},
	{Name: "AccessPreview"},
	{Name: "AccessPreviewFinding"},
	{Name: "AccessPreviewStatusReason"},
	{Name: "AccessPreviewSummary"},
	{Name: "AclGrantee"},
	{Name: "AnalysisRule"},
	{Name: "AnalysisRuleCriteria"},
	{Name: "AnalyzedResource"},
	{Name: "AnalyzedResourceSummary"},
	{Name: "AnalyzerConfiguration"},
	{Name: "AnalyzerSummary"},
	{Name: "ArchiveRuleSummary"},
	{Name: "CloudTrailDetails"},
	{Name: "CloudTrailProperties"},
	{Name: "Configuration"},
	{Name: "Criterion"},
	{Name: "DynamodbStreamConfiguration"},
	{Name: "DynamodbTableConfiguration"},
	{Name: "EbsSnapshotConfiguration"},
	{Name: "EcrRepositoryConfiguration"},
	{Name: "EfsFileSystemConfiguration"},
	{Name: "ExternalAccessDetails"},
	{Name: "ExternalAccessFindingsStatistics"},
	{Name: "Finding"},
	{Name: "FindingAggregationAccountDetails"},
	{Name: "FindingDetails"},
	{Name: "FindingSource"},
	{Name: "FindingSourceDetail"},
	{Name: "FindingsStatistics"},
	{Name: "FindingSummary"},
	{Name: "FindingSummaryV2"},
	{Name: "GeneratedPolicy"},
	{Name: "GeneratedPolicyProperties"},
	{Name: "GeneratedPolicyResult"},
	{Name: "IamRoleConfiguration"},
	{Name: "InlineArchiveRule"},
	{Name: "InternalAccessAnalysisRule"},
	{Name: "InternalAccessAnalysisRuleCriteria"},
	{Name: "InternalAccessConfiguration"},
	{Name: "InternalAccessDetails"},
	{Name: "InternalAccessFindingsStatistics"},
	{Name: "InternalAccessResourceTypeDetails"},
	{Name: "InternetConfiguration"},
	{Name: "JobDetails"},
	{Name: "JobError"},
	{Name: "KmsGrantConfiguration"},
	{Name: "KmsGrantConstraints"},
	{Name: "KmsKeyConfiguration"},
	{Name: "Location"},
	{Name: "NetworkOriginConfiguration"},
	{Name: "PathElement"},
	{Name: "PolicyGeneration"},
	{Name: "PolicyGenerationDetails"},
	{Name: "Position"},
	{Name: "RdsDbClusterSnapshotAttributeValue"},
	{Name: "RdsDbClusterSnapshotConfiguration"},
	{Name: "RdsDbSnapshotAttributeValue"},
	{Name: "RdsDbSnapshotConfiguration"},
	{Name: "ReasonSummary"},
	{Name: "RecommendationError"},
	{Name: "RecommendedStep"},
	{Name: "ResourceTypeDetails"},
	{Name: "S3AccessPointConfiguration"},
	{Name: "S3BucketAclGrantConfiguration"},
	{Name: "S3BucketConfiguration"},
	{Name: "S3ExpressDirectoryAccessPointConfiguration"},
	{Name: "S3ExpressDirectoryBucketConfiguration"},
	{Name: "S3PublicAccessBlockConfiguration"},
	{Name: "SecretsManagerSecretConfiguration"},
	{Name: "SnsTopicConfiguration"},
	{Name: "SortCriteria"},
	{Name: "Span"},
	{Name: "SqsQueueConfiguration"},
	{Name: "StatusReason"},
	{Name: "Substring"},
	{Name: "Trail"},
	{Name: "TrailProperties"},
	{Name: "UnusedAccessConfiguration"},
	{Name: "UnusedAccessFindingsStatistics"},
	{Name: "UnusedAccessTypeStatistics"},
	{Name: "UnusedAction"},
	{Name: "UnusedIamRoleDetails"},
	{Name: "UnusedIamUserAccessKeyDetails"},
	{Name: "UnusedIamUserPasswordDetails"},
	{Name: "UnusedPermissionDetails"},
	{Name: "UnusedPermissionsRecommendedStep"},
	{Name: "ValidatePolicyFinding"},
	{Name: "ValidationExceptionField"},
	{Name: "VpcConfiguration"},
	{Name: "ValidatePolicy"},
}

var accessAnalyzerDataTypeByName = func() map[string]accessAnalyzerDataType {
	out := make(map[string]accessAnalyzerDataType, len(accessAnalyzerDataTypes))
	for _, dt := range accessAnalyzerDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
