package server

type apiGatewayOperation struct {
	Name   string
	Method string
	URI    string
}

// AWS API Gateway operations sourced from:
// https://docs.aws.amazon.com/apigateway/latest/api/API_Operations.html
var apiGatewayOperations = []apiGatewayOperation{
	{Name: "CreateApiKey", Method: "POST", URI: "/apigateway/create-api-key"},
	{Name: "CreateAuthorizer", Method: "POST", URI: "/apigateway/create-authorizer"},
	{Name: "CreateBasePathMapping", Method: "POST", URI: "/apigateway/create-base-path-mapping"},
	{Name: "CreateDeployment", Method: "POST", URI: "/apigateway/create-deployment"},
	{Name: "CreateDocumentationPart", Method: "POST", URI: "/apigateway/create-documentation-part"},
	{Name: "CreateDocumentationVersion", Method: "POST", URI: "/apigateway/create-documentation-version"},
	{Name: "CreateDomainName", Method: "POST", URI: "/apigateway/create-domain-name"},
	{Name: "CreateDomainNameAccessAssociation", Method: "POST", URI: "/apigateway/create-domain-name-access-association"},
	{Name: "CreateModel", Method: "POST", URI: "/apigateway/create-model"},
	{Name: "CreateRequestValidator", Method: "POST", URI: "/apigateway/create-request-validator"},
	{Name: "CreateResource", Method: "POST", URI: "/apigateway/create-resource"},
	{Name: "CreateRestApi", Method: "POST", URI: "/apigateway/create-rest-api"},
	{Name: "CreateStage", Method: "POST", URI: "/apigateway/create-stage"},
	{Name: "CreateUsagePlan", Method: "POST", URI: "/apigateway/create-usage-plan"},
	{Name: "CreateUsagePlanKey", Method: "POST", URI: "/apigateway/create-usage-plan-key"},
	{Name: "CreateVpcLink", Method: "POST", URI: "/apigateway/create-vpc-link"},
	{Name: "DeleteApiKey", Method: "POST", URI: "/apigateway/delete-api-key"},
	{Name: "DeleteAuthorizer", Method: "POST", URI: "/apigateway/delete-authorizer"},
	{Name: "DeleteBasePathMapping", Method: "POST", URI: "/apigateway/delete-base-path-mapping"},
	{Name: "DeleteClientCertificate", Method: "POST", URI: "/apigateway/delete-client-certificate"},
	{Name: "DeleteDeployment", Method: "POST", URI: "/apigateway/delete-deployment"},
	{Name: "DeleteDocumentationPart", Method: "POST", URI: "/apigateway/delete-documentation-part"},
	{Name: "DeleteDocumentationVersion", Method: "POST", URI: "/apigateway/delete-documentation-version"},
	{Name: "DeleteDomainName", Method: "POST", URI: "/apigateway/delete-domain-name"},
	{Name: "DeleteDomainNameAccessAssociation", Method: "POST", URI: "/apigateway/delete-domain-name-access-association"},
	{Name: "DeleteGatewayResponse", Method: "POST", URI: "/apigateway/delete-gateway-response"},
	{Name: "DeleteIntegration", Method: "POST", URI: "/apigateway/delete-integration"},
	{Name: "DeleteIntegrationResponse", Method: "POST", URI: "/apigateway/delete-integration-response"},
	{Name: "DeleteMethod", Method: "POST", URI: "/apigateway/delete-method"},
	{Name: "DeleteMethodResponse", Method: "POST", URI: "/apigateway/delete-method-response"},
	{Name: "DeleteModel", Method: "POST", URI: "/apigateway/delete-model"},
	{Name: "DeleteRequestValidator", Method: "POST", URI: "/apigateway/delete-request-validator"},
	{Name: "DeleteResource", Method: "POST", URI: "/apigateway/delete-resource"},
	{Name: "DeleteRestApi", Method: "POST", URI: "/apigateway/delete-rest-api"},
	{Name: "DeleteStage", Method: "POST", URI: "/apigateway/delete-stage"},
	{Name: "DeleteUsagePlan", Method: "POST", URI: "/apigateway/delete-usage-plan"},
	{Name: "DeleteUsagePlanKey", Method: "POST", URI: "/apigateway/delete-usage-plan-key"},
	{Name: "DeleteVpcLink", Method: "POST", URI: "/apigateway/delete-vpc-link"},
	{Name: "FlushStageAuthorizersCache", Method: "POST", URI: "/apigateway/flush-stage-authorizers-cache"},
	{Name: "FlushStageCache", Method: "POST", URI: "/apigateway/flush-stage-cache"},
	{Name: "GenerateClientCertificate", Method: "POST", URI: "/apigateway/generate-client-certificate"},
	{Name: "GetAccount", Method: "POST", URI: "/apigateway/get-account"},
	{Name: "GetApiKey", Method: "POST", URI: "/apigateway/get-api-key"},
	{Name: "GetApiKeys", Method: "POST", URI: "/apigateway/get-api-keys"},
	{Name: "GetAuthorizer", Method: "POST", URI: "/apigateway/get-authorizer"},
	{Name: "GetAuthorizers", Method: "POST", URI: "/apigateway/get-authorizers"},
	{Name: "GetBasePathMapping", Method: "POST", URI: "/apigateway/get-base-path-mapping"},
	{Name: "GetBasePathMappings", Method: "POST", URI: "/apigateway/get-base-path-mappings"},
	{Name: "GetClientCertificate", Method: "POST", URI: "/apigateway/get-client-certificate"},
	{Name: "GetClientCertificates", Method: "POST", URI: "/apigateway/get-client-certificates"},
	{Name: "GetDeployment", Method: "POST", URI: "/apigateway/get-deployment"},
	{Name: "GetDeployments", Method: "POST", URI: "/apigateway/get-deployments"},
	{Name: "GetDocumentationPart", Method: "POST", URI: "/apigateway/get-documentation-part"},
	{Name: "GetDocumentationParts", Method: "POST", URI: "/apigateway/get-documentation-parts"},
	{Name: "GetDocumentationVersion", Method: "POST", URI: "/apigateway/get-documentation-version"},
	{Name: "GetDocumentationVersions", Method: "POST", URI: "/apigateway/get-documentation-versions"},
	{Name: "GetDomainName", Method: "POST", URI: "/apigateway/get-domain-name"},
	{Name: "GetDomainNameAccessAssociations", Method: "POST", URI: "/apigateway/get-domain-name-access-associations"},
	{Name: "GetDomainNames", Method: "POST", URI: "/apigateway/get-domain-names"},
	{Name: "GetExport", Method: "POST", URI: "/apigateway/get-export"},
	{Name: "GetGatewayResponse", Method: "POST", URI: "/apigateway/get-gateway-response"},
	{Name: "GetGatewayResponses", Method: "POST", URI: "/apigateway/get-gateway-responses"},
	{Name: "GetIntegration", Method: "POST", URI: "/apigateway/get-integration"},
	{Name: "GetIntegrationResponse", Method: "POST", URI: "/apigateway/get-integration-response"},
	{Name: "GetMethod", Method: "POST", URI: "/apigateway/get-method"},
	{Name: "GetMethodResponse", Method: "POST", URI: "/apigateway/get-method-response"},
	{Name: "GetModel", Method: "POST", URI: "/apigateway/get-model"},
	{Name: "GetModels", Method: "POST", URI: "/apigateway/get-models"},
	{Name: "GetModelTemplate", Method: "POST", URI: "/apigateway/get-model-template"},
	{Name: "GetRequestValidator", Method: "POST", URI: "/apigateway/get-request-validator"},
	{Name: "GetRequestValidators", Method: "POST", URI: "/apigateway/get-request-validators"},
	{Name: "GetResource", Method: "POST", URI: "/apigateway/get-resource"},
	{Name: "GetResources", Method: "POST", URI: "/apigateway/get-resources"},
	{Name: "GetRestApi", Method: "POST", URI: "/apigateway/get-rest-api"},
	{Name: "GetRestApis", Method: "POST", URI: "/apigateway/get-rest-apis"},
	{Name: "GetSdk", Method: "POST", URI: "/apigateway/get-sdk"},
	{Name: "GetSdkType", Method: "POST", URI: "/apigateway/get-sdk-type"},
	{Name: "GetSdkTypes", Method: "POST", URI: "/apigateway/get-sdk-types"},
	{Name: "GetStage", Method: "POST", URI: "/apigateway/get-stage"},
	{Name: "GetStages", Method: "POST", URI: "/apigateway/get-stages"},
	{Name: "GetTags", Method: "POST", URI: "/apigateway/get-tags"},
	{Name: "GetUsage", Method: "POST", URI: "/apigateway/get-usage"},
	{Name: "GetUsagePlan", Method: "POST", URI: "/apigateway/get-usage-plan"},
	{Name: "GetUsagePlanKey", Method: "POST", URI: "/apigateway/get-usage-plan-key"},
	{Name: "GetUsagePlanKeys", Method: "POST", URI: "/apigateway/get-usage-plan-keys"},
	{Name: "GetUsagePlans", Method: "POST", URI: "/apigateway/get-usage-plans"},
	{Name: "GetVpcLink", Method: "POST", URI: "/apigateway/get-vpc-link"},
	{Name: "GetVpcLinks", Method: "POST", URI: "/apigateway/get-vpc-links"},
	{Name: "ImportApiKeys", Method: "POST", URI: "/apigateway/import-api-keys"},
	{Name: "ImportDocumentationParts", Method: "POST", URI: "/apigateway/import-documentation-parts"},
	{Name: "ImportRestApi", Method: "POST", URI: "/apigateway/import-rest-api"},
	{Name: "PutGatewayResponse", Method: "POST", URI: "/apigateway/put-gateway-response"},
	{Name: "PutIntegration", Method: "POST", URI: "/apigateway/put-integration"},
	{Name: "PutIntegrationResponse", Method: "POST", URI: "/apigateway/put-integration-response"},
	{Name: "PutMethod", Method: "POST", URI: "/apigateway/put-method"},
	{Name: "PutMethodResponse", Method: "POST", URI: "/apigateway/put-method-response"},
	{Name: "PutRestApi", Method: "POST", URI: "/apigateway/put-rest-api"},
	{Name: "RejectDomainNameAccessAssociation", Method: "POST", URI: "/apigateway/reject-domain-name-access-association"},
	{Name: "TagResource", Method: "POST", URI: "/apigateway/tag-resource"},
	{Name: "TestInvokeAuthorizer", Method: "POST", URI: "/apigateway/test-invoke-authorizer"},
	{Name: "TestInvokeMethod", Method: "POST", URI: "/apigateway/test-invoke-method"},
	{Name: "UntagResource", Method: "POST", URI: "/apigateway/untag-resource"},
	{Name: "UpdateAccount", Method: "POST", URI: "/apigateway/update-account"},
	{Name: "UpdateApiKey", Method: "POST", URI: "/apigateway/update-api-key"},
	{Name: "UpdateAuthorizer", Method: "POST", URI: "/apigateway/update-authorizer"},
	{Name: "UpdateBasePathMapping", Method: "POST", URI: "/apigateway/update-base-path-mapping"},
	{Name: "UpdateClientCertificate", Method: "POST", URI: "/apigateway/update-client-certificate"},
	{Name: "UpdateDeployment", Method: "POST", URI: "/apigateway/update-deployment"},
	{Name: "UpdateDocumentationPart", Method: "POST", URI: "/apigateway/update-documentation-part"},
	{Name: "UpdateDocumentationVersion", Method: "POST", URI: "/apigateway/update-documentation-version"},
	{Name: "UpdateDomainName", Method: "POST", URI: "/apigateway/update-domain-name"},
	{Name: "UpdateGatewayResponse", Method: "POST", URI: "/apigateway/update-gateway-response"},
	{Name: "UpdateIntegration", Method: "POST", URI: "/apigateway/update-integration"},
	{Name: "UpdateIntegrationResponse", Method: "POST", URI: "/apigateway/update-integration-response"},
	{Name: "UpdateMethod", Method: "POST", URI: "/apigateway/update-method"},
	{Name: "UpdateMethodResponse", Method: "POST", URI: "/apigateway/update-method-response"},
	{Name: "UpdateModel", Method: "POST", URI: "/apigateway/update-model"},
	{Name: "UpdateRequestValidator", Method: "POST", URI: "/apigateway/update-request-validator"},
	{Name: "UpdateResource", Method: "POST", URI: "/apigateway/update-resource"},
	{Name: "UpdateRestApi", Method: "POST", URI: "/apigateway/update-rest-api"},
	{Name: "UpdateStage", Method: "POST", URI: "/apigateway/update-stage"},
	{Name: "UpdateUsage", Method: "POST", URI: "/apigateway/update-usage"},
	{Name: "UpdateUsagePlan", Method: "POST", URI: "/apigateway/update-usage-plan"},
	{Name: "UpdateVpcLink", Method: "POST", URI: "/apigateway/update-vpc-link"},
}

var apiGatewayOperationByName = func() map[string]apiGatewayOperation {
	out := make(map[string]apiGatewayOperation, len(apiGatewayOperations))
	for _, op := range apiGatewayOperations {
		out[op.Name] = op
	}
	return out
}()
