package server

type apiGatewayV2Operation struct {
	Name   string
	Method string
	URI    string
}

// AWS API Gateway v2 operations sourced from:
// https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/operations.html
var apiGatewayV2Operations = []apiGatewayV2Operation{
	{Name: "CreateApi", Method: "POST", URI: "/apigatewayv2/create-api"},
	{Name: "CreateApiMapping", Method: "POST", URI: "/apigatewayv2/create-api-mapping"},
	{Name: "CreateAuthorizer", Method: "POST", URI: "/apigatewayv2/create-authorizer"},
	{Name: "CreateDeployment", Method: "POST", URI: "/apigatewayv2/create-deployment"},
	{Name: "CreateDomainName", Method: "POST", URI: "/apigatewayv2/create-domain-name"},
	{Name: "CreateIntegration", Method: "POST", URI: "/apigatewayv2/create-integration"},
	{Name: "CreateIntegrationResponse", Method: "POST", URI: "/apigatewayv2/create-integration-response"},
	{Name: "CreateModel", Method: "POST", URI: "/apigatewayv2/create-model"},
	{Name: "CreatePortal", Method: "POST", URI: "/apigatewayv2/create-portal"},
	{Name: "CreatePortalProduct", Method: "POST", URI: "/apigatewayv2/create-portal-product"},
	{Name: "CreateProductPage", Method: "POST", URI: "/apigatewayv2/create-product-page"},
	{Name: "CreateProductRestEndpointPage", Method: "POST", URI: "/apigatewayv2/create-product-rest-endpoint-page"},
	{Name: "CreateRoute", Method: "POST", URI: "/apigatewayv2/create-route"},
	{Name: "CreateRouteResponse", Method: "POST", URI: "/apigatewayv2/create-route-response"},
	{Name: "CreateRoutingRule", Method: "POST", URI: "/apigatewayv2/create-routing-rule"},
	{Name: "CreateStage", Method: "POST", URI: "/apigatewayv2/create-stage"},
	{Name: "CreateVpcLink", Method: "POST", URI: "/apigatewayv2/create-vpc-link"},
	{Name: "DeleteAccessLogSettings", Method: "POST", URI: "/apigatewayv2/delete-access-log-settings"},
	{Name: "DeleteApi", Method: "POST", URI: "/apigatewayv2/delete-api"},
	{Name: "DeleteApiMapping", Method: "POST", URI: "/apigatewayv2/delete-api-mapping"},
	{Name: "DeleteAuthorizer", Method: "POST", URI: "/apigatewayv2/delete-authorizer"},
	{Name: "DeleteCorsConfiguration", Method: "POST", URI: "/apigatewayv2/delete-cors-configuration"},
	{Name: "DeleteDeployment", Method: "POST", URI: "/apigatewayv2/delete-deployment"},
	{Name: "DeleteDomainName", Method: "POST", URI: "/apigatewayv2/delete-domain-name"},
	{Name: "DeleteIntegration", Method: "POST", URI: "/apigatewayv2/delete-integration"},
	{Name: "DeleteIntegrationResponse", Method: "POST", URI: "/apigatewayv2/delete-integration-response"},
	{Name: "DeleteModel", Method: "POST", URI: "/apigatewayv2/delete-model"},
	{Name: "DeletePortal", Method: "POST", URI: "/apigatewayv2/delete-portal"},
	{Name: "DeletePortalProduct", Method: "POST", URI: "/apigatewayv2/delete-portal-product"},
	{Name: "DeletePortalProductSharingPolicy", Method: "POST", URI: "/apigatewayv2/delete-portal-product-sharing-policy"},
	{Name: "DeleteProductPage", Method: "POST", URI: "/apigatewayv2/delete-product-page"},
	{Name: "DeleteProductRestEndpointPage", Method: "POST", URI: "/apigatewayv2/delete-product-rest-endpoint-page"},
	{Name: "DeleteRoute", Method: "POST", URI: "/apigatewayv2/delete-route"},
	{Name: "DeleteRouteRequestParameter", Method: "POST", URI: "/apigatewayv2/delete-route-request-parameter"},
	{Name: "DeleteRouteResponse", Method: "POST", URI: "/apigatewayv2/delete-route-response"},
	{Name: "DeleteRouteSettings", Method: "POST", URI: "/apigatewayv2/delete-route-settings"},
	{Name: "DeleteRoutingRule", Method: "POST", URI: "/apigatewayv2/delete-routing-rule"},
	{Name: "DeleteStage", Method: "POST", URI: "/apigatewayv2/delete-stage"},
	{Name: "DeleteVpcLink", Method: "POST", URI: "/apigatewayv2/delete-vpc-link"},
	{Name: "DisablePortal", Method: "POST", URI: "/apigatewayv2/disable-portal"},
	{Name: "ExportApi", Method: "POST", URI: "/apigatewayv2/export-api"},
	{Name: "GetApi", Method: "POST", URI: "/apigatewayv2/get-api"},
	{Name: "GetApiMapping", Method: "POST", URI: "/apigatewayv2/get-api-mapping"},
	{Name: "GetApiMappings", Method: "POST", URI: "/apigatewayv2/get-api-mappings"},
	{Name: "GetApis", Method: "POST", URI: "/apigatewayv2/get-apis"},
	{Name: "GetAuthorizer", Method: "POST", URI: "/apigatewayv2/get-authorizer"},
	{Name: "GetAuthorizers", Method: "POST", URI: "/apigatewayv2/get-authorizers"},
	{Name: "GetDeployment", Method: "POST", URI: "/apigatewayv2/get-deployment"},
	{Name: "GetDeployments", Method: "POST", URI: "/apigatewayv2/get-deployments"},
	{Name: "GetDomainName", Method: "POST", URI: "/apigatewayv2/get-domain-name"},
	{Name: "GetDomainNames", Method: "POST", URI: "/apigatewayv2/get-domain-names"},
	{Name: "GetIntegration", Method: "POST", URI: "/apigatewayv2/get-integration"},
	{Name: "GetIntegrationResponse", Method: "POST", URI: "/apigatewayv2/get-integration-response"},
	{Name: "GetIntegrationResponses", Method: "POST", URI: "/apigatewayv2/get-integration-responses"},
	{Name: "GetIntegrations", Method: "POST", URI: "/apigatewayv2/get-integrations"},
	{Name: "GetModel", Method: "POST", URI: "/apigatewayv2/get-model"},
	{Name: "GetModels", Method: "POST", URI: "/apigatewayv2/get-models"},
	{Name: "GetModelTemplate", Method: "POST", URI: "/apigatewayv2/get-model-template"},
	{Name: "GetPortal", Method: "POST", URI: "/apigatewayv2/get-portal"},
	{Name: "GetPortalProduct", Method: "POST", URI: "/apigatewayv2/get-portal-product"},
	{Name: "GetPortalProductSharingPolicy", Method: "POST", URI: "/apigatewayv2/get-portal-product-sharing-policy"},
	{Name: "GetProductPage", Method: "POST", URI: "/apigatewayv2/get-product-page"},
	{Name: "GetProductRestEndpointPage", Method: "POST", URI: "/apigatewayv2/get-product-rest-endpoint-page"},
	{Name: "GetRoute", Method: "POST", URI: "/apigatewayv2/get-route"},
	{Name: "GetRouteResponse", Method: "POST", URI: "/apigatewayv2/get-route-response"},
	{Name: "GetRouteResponses", Method: "POST", URI: "/apigatewayv2/get-route-responses"},
	{Name: "GetRoutes", Method: "POST", URI: "/apigatewayv2/get-routes"},
	{Name: "GetRoutingRule", Method: "POST", URI: "/apigatewayv2/get-routing-rule"},
	{Name: "GetStage", Method: "POST", URI: "/apigatewayv2/get-stage"},
	{Name: "GetStages", Method: "POST", URI: "/apigatewayv2/get-stages"},
	{Name: "GetTags", Method: "POST", URI: "/apigatewayv2/get-tags"},
	{Name: "GetVpcLink", Method: "POST", URI: "/apigatewayv2/get-vpc-link"},
	{Name: "GetVpcLinks", Method: "POST", URI: "/apigatewayv2/get-vpc-links"},
	{Name: "ImportApi", Method: "POST", URI: "/apigatewayv2/import-api"},
	{Name: "ReimportApi", Method: "POST", URI: "/apigatewayv2/reimport-api"},
	{Name: "ResetAuthorizersCache", Method: "POST", URI: "/apigatewayv2/reset-authorizers-cache"},
	{Name: "TagResource", Method: "POST", URI: "/apigatewayv2/tag-resource"},
	{Name: "UntagResource", Method: "POST", URI: "/apigatewayv2/untag-resource"},
	{Name: "UpdateApi", Method: "POST", URI: "/apigatewayv2/update-api"},
	{Name: "UpdateApiMapping", Method: "POST", URI: "/apigatewayv2/update-api-mapping"},
	{Name: "UpdateAuthorizer", Method: "POST", URI: "/apigatewayv2/update-authorizer"},
	{Name: "UpdateDeployment", Method: "POST", URI: "/apigatewayv2/update-deployment"},
	{Name: "UpdateDomainName", Method: "POST", URI: "/apigatewayv2/update-domain-name"},
	{Name: "UpdateIntegration", Method: "POST", URI: "/apigatewayv2/update-integration"},
	{Name: "UpdateIntegrationResponse", Method: "POST", URI: "/apigatewayv2/update-integration-response"},
	{Name: "UpdateModel", Method: "POST", URI: "/apigatewayv2/update-model"},
	{Name: "UpdatePortal", Method: "POST", URI: "/apigatewayv2/update-portal"},
	{Name: "UpdatePortalProduct", Method: "POST", URI: "/apigatewayv2/update-portal-product"},
	{Name: "UpdateProductPage", Method: "POST", URI: "/apigatewayv2/update-product-page"},
	{Name: "UpdateProductRestEndpointPage", Method: "POST", URI: "/apigatewayv2/update-product-rest-endpoint-page"},
	{Name: "UpdateRoute", Method: "POST", URI: "/apigatewayv2/update-route"},
	{Name: "UpdateRouteResponse", Method: "POST", URI: "/apigatewayv2/update-route-response"},
	{Name: "UpdateStage", Method: "POST", URI: "/apigatewayv2/update-stage"},
	{Name: "UpdateVpcLink", Method: "POST", URI: "/apigatewayv2/update-vpc-link"},
}

var apiGatewayV2OperationByName = func() map[string]apiGatewayV2Operation {
	out := make(map[string]apiGatewayV2Operation, len(apiGatewayV2Operations))
	for _, op := range apiGatewayV2Operations {
		out[op.Name] = op
	}
	return out
}()
