package server

type bedrockOperation struct {
	Name string
}

// Amazon Bedrock operations sourced from:
// https://docs.aws.amazon.com/bedrock/latest/APIReference/API_Operations.html
var bedrockOperations = []bedrockOperation{
	{Name: "BatchDeleteEvaluationJob"},
	{Name: "CancelAutomatedReasoningPolicyBuildWorkflow"},
	{Name: "CreateAutomatedReasoningPolicy"},
	{Name: "CreateAutomatedReasoningPolicyTestCase"},
	{Name: "CreateAutomatedReasoningPolicyVersion"},
	{Name: "CreateCustomModel"},
	{Name: "CreateCustomModelDeployment"},
	{Name: "CreateEvaluationJob"},
	{Name: "CreateFoundationModelAgreement"},
	{Name: "CreateGuardrail"},
	{Name: "CreateGuardrailVersion"},
	{Name: "CreateInferenceProfile"},
	{Name: "CreateMarketplaceModelEndpoint"},
	{Name: "CreateModelCopyJob"},
	{Name: "CreateModelCustomizationJob"},
	{Name: "CreateModelImportJob"},
	{Name: "CreateModelInvocationJob"},
	{Name: "CreatePromptRouter"},
	{Name: "CreateProvisionedModelThroughput"},
	{Name: "DeleteAutomatedReasoningPolicy"},
	{Name: "DeleteAutomatedReasoningPolicyBuildWorkflow"},
	{Name: "DeleteAutomatedReasoningPolicyTestCase"},
	{Name: "DeleteCustomModel"},
	{Name: "DeleteCustomModelDeployment"},
	{Name: "DeleteEnforcedGuardrailConfiguration"},
	{Name: "DeleteFoundationModelAgreement"},
	{Name: "DeleteGuardrail"},
	{Name: "DeleteImportedModel"},
	{Name: "DeleteInferenceProfile"},
	{Name: "DeleteMarketplaceModelEndpoint"},
	{Name: "DeleteModelInvocationLoggingConfiguration"},
	{Name: "DeletePromptRouter"},
	{Name: "DeleteProvisionedModelThroughput"},
	{Name: "DeregisterMarketplaceModelEndpoint"},
	{Name: "ExportAutomatedReasoningPolicyVersion"},
	{Name: "GetAutomatedReasoningPolicy"},
	{Name: "GetAutomatedReasoningPolicyAnnotations"},
	{Name: "GetAutomatedReasoningPolicyBuildWorkflow"},
	{Name: "GetAutomatedReasoningPolicyBuildWorkflowResultAssets"},
	{Name: "GetAutomatedReasoningPolicyNextScenario"},
	{Name: "GetAutomatedReasoningPolicyTestCase"},
	{Name: "GetAutomatedReasoningPolicyTestResult"},
	{Name: "GetCustomModel"},
	{Name: "GetCustomModelDeployment"},
	{Name: "GetEvaluationJob"},
	{Name: "GetFoundationModel"},
	{Name: "GetFoundationModelAvailability"},
	{Name: "GetGuardrail"},
	{Name: "GetImportedModel"},
	{Name: "GetInferenceProfile"},
	{Name: "GetMarketplaceModelEndpoint"},
	{Name: "GetModelCopyJob"},
	{Name: "GetModelCustomizationJob"},
	{Name: "GetModelImportJob"},
	{Name: "GetModelInvocationJob"},
	{Name: "GetModelInvocationLoggingConfiguration"},
	{Name: "GetPromptRouter"},
	{Name: "GetProvisionedModelThroughput"},
	{Name: "GetUseCaseForModelAccess"},
	{Name: "ListAutomatedReasoningPolicies"},
	{Name: "ListAutomatedReasoningPolicyBuildWorkflows"},
	{Name: "ListAutomatedReasoningPolicyTestCases"},
	{Name: "ListAutomatedReasoningPolicyTestResults"},
	{Name: "ListCustomModelDeployments"},
	{Name: "ListCustomModels"},
	{Name: "ListEnforcedGuardrailsConfiguration"},
	{Name: "ListEvaluationJobs"},
	{Name: "ListFoundationModelAgreementOffers"},
	{Name: "ListFoundationModels"},
	{Name: "ListGuardrails"},
	{Name: "ListImportedModels"},
	{Name: "ListInferenceProfiles"},
	{Name: "ListMarketplaceModelEndpoints"},
	{Name: "ListModelCopyJobs"},
	{Name: "ListModelCustomizationJobs"},
	{Name: "ListModelImportJobs"},
	{Name: "ListModelInvocationJobs"},
	{Name: "ListPromptRouters"},
	{Name: "ListProvisionedModelThroughputs"},
	{Name: "ListTagsForResource"},
	{Name: "PutEnforcedGuardrailConfiguration"},
	{Name: "PutModelInvocationLoggingConfiguration"},
	{Name: "PutUseCaseForModelAccess"},
	{Name: "RegisterMarketplaceModelEndpoint"},
	{Name: "StartAutomatedReasoningPolicyBuildWorkflow"},
	{Name: "StartAutomatedReasoningPolicyTestWorkflow"},
	{Name: "StopEvaluationJob"},
	{Name: "StopModelCustomizationJob"},
	{Name: "StopModelInvocationJob"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateAutomatedReasoningPolicy"},
	{Name: "UpdateAutomatedReasoningPolicyAnnotations"},
	{Name: "UpdateAutomatedReasoningPolicyTestCase"},
	{Name: "UpdateCustomModelDeployment"},
	{Name: "UpdateGuardrail"},
	{Name: "UpdateMarketplaceModelEndpoint"},
	{Name: "UpdateProvisionedModelThroughput"},
}

var bedrockOperationByName = func() map[string]bedrockOperation {
	out := make(map[string]bedrockOperation, len(bedrockOperations))
	for _, op := range bedrockOperations {
		out[op.Name] = op
	}
	return out
}()
