package server

type cloudWatchLogsOperation struct {
	Name   string
	Method string
	URI    string
}

// Amazon CloudWatch Logs operations sourced from:
// https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Operations.html
var cloudWatchLogsOperations = []cloudWatchLogsOperation{
	{Name: "AssociateKmsKey", Method: "POST", URI: "/AssociateKmsKey"},
	{Name: "AssociateSourceToS3TableIntegration", Method: "POST", URI: "/AssociateSourceToS3TableIntegration"},
	{Name: "CancelExportTask", Method: "POST", URI: "/CancelExportTask"},
	{Name: "CancelImportTask", Method: "POST", URI: "/CancelImportTask"},
	{Name: "CreateDelivery", Method: "POST", URI: "/CreateDelivery"},
	{Name: "CreateExportTask", Method: "POST", URI: "/CreateExportTask"},
	{Name: "CreateImportTask", Method: "POST", URI: "/CreateImportTask"},
	{Name: "CreateLogAnomalyDetector", Method: "POST", URI: "/CreateLogAnomalyDetector"},
	{Name: "CreateLogGroup", Method: "POST", URI: "/CreateLogGroup"},
	{Name: "CreateLogStream", Method: "POST", URI: "/CreateLogStream"},
	{Name: "CreateScheduledQuery", Method: "POST", URI: "/CreateScheduledQuery"},
	{Name: "DeleteAccountPolicy", Method: "POST", URI: "/DeleteAccountPolicy"},
	{Name: "DeleteDataProtectionPolicy", Method: "POST", URI: "/DeleteDataProtectionPolicy"},
	{Name: "DeleteDelivery", Method: "POST", URI: "/DeleteDelivery"},
	{Name: "DeleteDeliveryDestination", Method: "POST", URI: "/DeleteDeliveryDestination"},
	{Name: "DeleteDeliveryDestinationPolicy", Method: "POST", URI: "/DeleteDeliveryDestinationPolicy"},
	{Name: "DeleteDeliverySource", Method: "POST", URI: "/DeleteDeliverySource"},
	{Name: "DeleteDestination", Method: "POST", URI: "/DeleteDestination"},
	{Name: "DeleteIndexPolicy", Method: "POST", URI: "/DeleteIndexPolicy"},
	{Name: "DeleteIntegration", Method: "POST", URI: "/DeleteIntegration"},
	{Name: "DeleteLogAnomalyDetector", Method: "POST", URI: "/DeleteLogAnomalyDetector"},
	{Name: "DeleteLogGroup", Method: "POST", URI: "/DeleteLogGroup"},
	{Name: "DeleteLogStream", Method: "POST", URI: "/DeleteLogStream"},
	{Name: "DeleteMetricFilter", Method: "POST", URI: "/DeleteMetricFilter"},
	{Name: "DeleteQueryDefinition", Method: "POST", URI: "/DeleteQueryDefinition"},
	{Name: "DeleteResourcePolicy", Method: "POST", URI: "/DeleteResourcePolicy"},
	{Name: "DeleteRetentionPolicy", Method: "POST", URI: "/DeleteRetentionPolicy"},
	{Name: "DeleteScheduledQuery", Method: "POST", URI: "/DeleteScheduledQuery"},
	{Name: "DeleteSubscriptionFilter", Method: "POST", URI: "/DeleteSubscriptionFilter"},
	{Name: "DeleteTransformer", Method: "POST", URI: "/DeleteTransformer"},
	{Name: "DescribeAccountPolicies", Method: "POST", URI: "/DescribeAccountPolicies"},
	{Name: "DescribeConfigurationTemplates", Method: "POST", URI: "/DescribeConfigurationTemplates"},
	{Name: "DescribeDeliveries", Method: "POST", URI: "/DescribeDeliveries"},
	{Name: "DescribeDeliveryDestinations", Method: "POST", URI: "/DescribeDeliveryDestinations"},
	{Name: "DescribeDeliverySources", Method: "POST", URI: "/DescribeDeliverySources"},
	{Name: "DescribeDestinations", Method: "POST", URI: "/DescribeDestinations"},
	{Name: "DescribeExportTasks", Method: "POST", URI: "/DescribeExportTasks"},
	{Name: "DescribeFieldIndexes", Method: "POST", URI: "/DescribeFieldIndexes"},
	{Name: "DescribeImportTaskBatches", Method: "POST", URI: "/DescribeImportTaskBatches"},
	{Name: "DescribeImportTasks", Method: "POST", URI: "/DescribeImportTasks"},
	{Name: "DescribeIndexPolicies", Method: "POST", URI: "/DescribeIndexPolicies"},
	{Name: "DescribeLogGroups", Method: "POST", URI: "/DescribeLogGroups"},
	{Name: "DescribeLogStreams", Method: "POST", URI: "/DescribeLogStreams"},
	{Name: "DescribeMetricFilters", Method: "POST", URI: "/DescribeMetricFilters"},
	{Name: "DescribeQueries", Method: "POST", URI: "/DescribeQueries"},
	{Name: "DescribeQueryDefinitions", Method: "POST", URI: "/DescribeQueryDefinitions"},
	{Name: "DescribeResourcePolicies", Method: "POST", URI: "/DescribeResourcePolicies"},
	{Name: "DescribeSubscriptionFilters", Method: "POST", URI: "/DescribeSubscriptionFilters"},
	{Name: "DisassociateKmsKey", Method: "POST", URI: "/DisassociateKmsKey"},
	{Name: "DisassociateSourceFromS3TableIntegration", Method: "POST", URI: "/DisassociateSourceFromS3TableIntegration"},
	{Name: "FilterLogEvents", Method: "POST", URI: "/FilterLogEvents"},
	{Name: "GetDataProtectionPolicy", Method: "POST", URI: "/GetDataProtectionPolicy"},
	{Name: "GetDelivery", Method: "POST", URI: "/GetDelivery"},
	{Name: "GetDeliveryDestination", Method: "POST", URI: "/GetDeliveryDestination"},
	{Name: "GetDeliveryDestinationPolicy", Method: "POST", URI: "/GetDeliveryDestinationPolicy"},
	{Name: "GetDeliverySource", Method: "POST", URI: "/GetDeliverySource"},
	{Name: "GetIntegration", Method: "POST", URI: "/GetIntegration"},
	{Name: "GetLogAnomalyDetector", Method: "POST", URI: "/GetLogAnomalyDetector"},
	{Name: "GetLogEvents", Method: "POST", URI: "/GetLogEvents"},
	{Name: "GetLogFields", Method: "POST", URI: "/GetLogFields"},
	{Name: "GetLogGroupFields", Method: "POST", URI: "/GetLogGroupFields"},
	{Name: "GetLogObject", Method: "POST", URI: "/GetLogObject"},
	{Name: "GetLogRecord", Method: "POST", URI: "/GetLogRecord"},
	{Name: "GetQueryResults", Method: "POST", URI: "/GetQueryResults"},
	{Name: "GetScheduledQuery", Method: "POST", URI: "/GetScheduledQuery"},
	{Name: "GetScheduledQueryHistory", Method: "POST", URI: "/GetScheduledQueryHistory"},
	{Name: "GetTransformer", Method: "POST", URI: "/GetTransformer"},
	{Name: "ListAggregateLogGroupSummaries", Method: "POST", URI: "/ListAggregateLogGroupSummaries"},
	{Name: "ListAnomalies", Method: "POST", URI: "/ListAnomalies"},
	{Name: "ListIntegrations", Method: "POST", URI: "/ListIntegrations"},
	{Name: "ListLogAnomalyDetectors", Method: "POST", URI: "/ListLogAnomalyDetectors"},
	{Name: "ListLogGroups", Method: "POST", URI: "/ListLogGroups"},
	{Name: "ListLogGroupsForQuery", Method: "POST", URI: "/ListLogGroupsForQuery"},
	{Name: "ListScheduledQueries", Method: "POST", URI: "/ListScheduledQueries"},
	{Name: "ListSourcesForS3TableIntegration", Method: "POST", URI: "/ListSourcesForS3TableIntegration"},
	{Name: "ListTagsForResource", Method: "POST", URI: "/ListTagsForResource"},
	{Name: "ListTagsLogGroup", Method: "POST", URI: "/ListTagsLogGroup"},
	{Name: "PutAccountPolicy", Method: "POST", URI: "/PutAccountPolicy"},
	{Name: "PutDataProtectionPolicy", Method: "POST", URI: "/PutDataProtectionPolicy"},
	{Name: "PutDeliveryDestination", Method: "POST", URI: "/PutDeliveryDestination"},
	{Name: "PutDeliveryDestinationPolicy", Method: "POST", URI: "/PutDeliveryDestinationPolicy"},
	{Name: "PutDeliverySource", Method: "POST", URI: "/PutDeliverySource"},
	{Name: "PutDestination", Method: "POST", URI: "/PutDestination"},
	{Name: "PutDestinationPolicy", Method: "POST", URI: "/PutDestinationPolicy"},
	{Name: "PutIndexPolicy", Method: "POST", URI: "/PutIndexPolicy"},
	{Name: "PutIntegration", Method: "POST", URI: "/PutIntegration"},
	{Name: "PutLogEvents", Method: "POST", URI: "/PutLogEvents"},
	{Name: "PutLogGroupDeletionProtection", Method: "POST", URI: "/PutLogGroupDeletionProtection"},
	{Name: "PutMetricFilter", Method: "POST", URI: "/PutMetricFilter"},
	{Name: "PutQueryDefinition", Method: "POST", URI: "/PutQueryDefinition"},
	{Name: "PutResourcePolicy", Method: "POST", URI: "/PutResourcePolicy"},
	{Name: "PutRetentionPolicy", Method: "POST", URI: "/PutRetentionPolicy"},
	{Name: "PutSubscriptionFilter", Method: "POST", URI: "/PutSubscriptionFilter"},
	{Name: "PutTransformer", Method: "POST", URI: "/PutTransformer"},
	{Name: "StartLiveTail", Method: "POST", URI: "/StartLiveTail"},
	{Name: "StartQuery", Method: "POST", URI: "/StartQuery"},
	{Name: "StopQuery", Method: "POST", URI: "/StopQuery"},
	{Name: "TagLogGroup", Method: "POST", URI: "/TagLogGroup"},
	{Name: "TagResource", Method: "POST", URI: "/TagResource"},
	{Name: "TestMetricFilter", Method: "POST", URI: "/TestMetricFilter"},
	{Name: "TestTransformer", Method: "POST", URI: "/TestTransformer"},
	{Name: "UntagLogGroup", Method: "POST", URI: "/UntagLogGroup"},
	{Name: "UntagResource", Method: "POST", URI: "/UntagResource"},
	{Name: "UpdateAnomaly", Method: "POST", URI: "/UpdateAnomaly"},
	{Name: "UpdateDeliveryConfiguration", Method: "POST", URI: "/UpdateDeliveryConfiguration"},
	{Name: "UpdateLogAnomalyDetector", Method: "POST", URI: "/UpdateLogAnomalyDetector"},
	{Name: "UpdateScheduledQuery", Method: "POST", URI: "/UpdateScheduledQuery"},
}

var cloudWatchLogsOperationByName = func() map[string]cloudWatchLogsOperation {
	out := make(map[string]cloudWatchLogsOperation, len(cloudWatchLogsOperations))
	for _, op := range cloudWatchLogsOperations {
		out[op.Name] = op
	}
	return out
}()
