package server

type cloudFormationDataType struct {
	Name string
}

// AWS CloudFormation data types sourced from:
// https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Types.html
var cloudFormationDataTypes = []cloudFormationDataType{
	{Name: "AccountGateResult"},
	{Name: "AccountLimit"},
	{Name: "Annotation"},
	{Name: "AutoDeployment"},
	{Name: "BatchDescribeTypeConfigurationsError"},
	{Name: "Change"},
	{Name: "ChangeSetHook"},
	{Name: "ChangeSetHookResourceTargetDetails"},
	{Name: "ChangeSetHookTargetDetails"},
	{Name: "ChangeSetSummary"},
	{Name: "DeploymentTargets"},
	{Name: "EventFilter"},
	{Name: "Export"},
	{Name: "HookResultSummary"},
	{Name: "HookTarget"},
	{Name: "LiveResourceDrift"},
	{Name: "LoggingConfig"},
	{Name: "ManagedExecution"},
	{Name: "ModuleInfo"},
	{Name: "OperationEntry"},
	{Name: "OperationEvent"},
	{Name: "OperationResultFilter"},
	{Name: "Output"},
	{Name: "Parameter"},
	{Name: "ParameterConstraints"},
	{Name: "ParameterDeclaration"},
	{Name: "PhysicalResourceIdContextKeyValuePair"},
	{Name: "PropertyDifference"},
	{Name: "RequiredActivatedType"},
	{Name: "ResourceChange"},
	{Name: "ResourceChangeDetail"},
	{Name: "ResourceDefinition"},
	{Name: "ResourceDetail"},
	{Name: "ResourceDriftIgnoredAttribute"},
	{Name: "ResourceIdentifierSummary"},
	{Name: "ResourceLocation"},
	{Name: "ResourceMapping"},
	{Name: "ResourceScanSummary"},
	{Name: "ResourceTargetDefinition"},
	{Name: "ResourceToImport"},
	{Name: "RollbackConfiguration"},
	{Name: "RollbackTrigger"},
	{Name: "ScanFilter"},
	{Name: "ScannedResource"},
	{Name: "ScannedResourceIdentifier"},
	{Name: "Stack"},
	{Name: "StackDefinition"},
	{Name: "StackDriftInformation"},
	{Name: "StackDriftInformationSummary"},
	{Name: "StackEvent"},
	{Name: "StackInstance"},
	{Name: "StackInstanceComprehensiveStatus"},
	{Name: "StackInstanceFilter"},
	{Name: "StackInstanceResourceDriftsSummary"},
	{Name: "StackInstanceSummary"},
	{Name: "StackRefactorAction"},
	{Name: "StackRefactorSummary"},
	{Name: "StackResource"},
	{Name: "StackResourceDetail"},
	{Name: "StackResourceDrift"},
	{Name: "StackResourceDriftInformation"},
	{Name: "StackResourceDriftInformationSummary"},
	{Name: "StackResourceSummary"},
	{Name: "StackSet"},
	{Name: "StackSetAutoDeploymentTargetSummary"},
	{Name: "StackSetDriftDetectionDetails"},
	{Name: "StackSetOperation"},
	{Name: "StackSetOperationPreferences"},
	{Name: "StackSetOperationResultSummary"},
	{Name: "StackSetOperationStatusDetails"},
	{Name: "StackSetOperationSummary"},
	{Name: "StackSetSummary"},
	{Name: "StackSummary"},
	{Name: "Tag"},
	{Name: "TemplateConfiguration"},
	{Name: "TemplateParameter"},
	{Name: "TemplateProgress"},
	{Name: "TemplateSummary"},
	{Name: "TemplateSummaryConfig"},
	{Name: "TypeConfigurationDetails"},
	{Name: "TypeConfigurationIdentifier"},
	{Name: "TypeFilters"},
	{Name: "TypeSummary"},
	{Name: "TypeVersionSummary"},
	{Name: "WarningDetail"},
	{Name: "WarningProperty"},
	{Name: "Warnings"},
	{Name: "ValidateTemplate"},
}

var cloudFormationDataTypeByName = func() map[string]cloudFormationDataType {
	out := make(map[string]cloudFormationDataType, len(cloudFormationDataTypes))
	for _, dt := range cloudFormationDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
