package server

type cloudDirectoryAPIType struct {
	Name string
}

// Amazon Cloud Directory data types sourced from:
// https://docs.aws.amazon.com/clouddirectory/latest/APIReference/API_Types.html
var cloudDirectoryAPITypes = []cloudDirectoryAPIType{
	{Name: "AttributeKey"},
	{Name: "AttributeKeyAndValue"},
	{Name: "AttributeNameAndValue"},
	{Name: "BatchAddFacetToObject"},
	{Name: "BatchAddFacetToObjectResponse"},
	{Name: "BatchAttachObject"},
	{Name: "BatchAttachObjectResponse"},
	{Name: "BatchAttachPolicy"},
	{Name: "BatchAttachPolicyResponse"},
	{Name: "BatchAttachToIndex"},
	{Name: "BatchAttachToIndexResponse"},
	{Name: "BatchAttachTypedLink"},
	{Name: "BatchAttachTypedLinkResponse"},
	{Name: "BatchCreateIndex"},
	{Name: "BatchCreateIndexResponse"},
	{Name: "BatchCreateObject"},
	{Name: "BatchCreateObjectResponse"},
	{Name: "BatchDeleteObject"},
	{Name: "BatchDeleteObjectResponse"},
	{Name: "BatchDetachFromIndex"},
	{Name: "BatchDetachFromIndexResponse"},
	{Name: "BatchDetachObject"},
	{Name: "BatchDetachObjectResponse"},
	{Name: "BatchDetachPolicy"},
	{Name: "BatchDetachPolicyResponse"},
	{Name: "BatchDetachTypedLink"},
	{Name: "BatchDetachTypedLinkResponse"},
	{Name: "BatchGetLinkAttributes"},
	{Name: "BatchGetLinkAttributesResponse"},
	{Name: "BatchGetObjectAttributes"},
	{Name: "BatchGetObjectAttributesResponse"},
	{Name: "BatchGetObjectInformation"},
	{Name: "BatchGetObjectInformationResponse"},
	{Name: "BatchListAttachedIndices"},
	{Name: "BatchListAttachedIndicesResponse"},
	{Name: "BatchListIncomingTypedLinks"},
	{Name: "BatchListIncomingTypedLinksResponse"},
	{Name: "BatchListIndex"},
	{Name: "BatchListIndexResponse"},
	{Name: "BatchListObjectAttributes"},
	{Name: "BatchListObjectAttributesResponse"},
	{Name: "BatchListObjectChildren"},
	{Name: "BatchListObjectChildrenResponse"},
	{Name: "BatchListObjectParentPaths"},
	{Name: "BatchListObjectParentPathsResponse"},
	{Name: "BatchListObjectParents"},
	{Name: "BatchListObjectParentsResponse"},
	{Name: "BatchListObjectPolicies"},
	{Name: "BatchListObjectPoliciesResponse"},
	{Name: "BatchListOutgoingTypedLinks"},
	{Name: "BatchListOutgoingTypedLinksResponse"},
	{Name: "BatchListPolicyAttachments"},
	{Name: "BatchListPolicyAttachmentsResponse"},
	{Name: "BatchLookupPolicy"},
	{Name: "BatchLookupPolicyResponse"},
	{Name: "BatchReadException"},
	{Name: "BatchReadOperation"},
	{Name: "BatchReadOperationResponse"},
	{Name: "BatchReadSuccessfulResponse"},
	{Name: "BatchRemoveFacetFromObject"},
	{Name: "BatchRemoveFacetFromObjectResponse"},
	{Name: "BatchUpdateLinkAttributes"},
	{Name: "BatchUpdateLinkAttributesResponse"},
	{Name: "BatchUpdateObjectAttributes"},
	{Name: "BatchUpdateObjectAttributesResponse"},
	{Name: "BatchWriteOperation"},
	{Name: "BatchWriteOperationResponse"},
	{Name: "Directory"},
	{Name: "Facet"},
	{Name: "FacetAttribute"},
	{Name: "FacetAttributeDefinition"},
	{Name: "FacetAttributeReference"},
	{Name: "FacetAttributeUpdate"},
	{Name: "IndexAttachment"},
	{Name: "LinkAttributeAction"},
	{Name: "LinkAttributeUpdate"},
	{Name: "ObjectAttributeAction"},
	{Name: "ObjectAttributeRange"},
	{Name: "ObjectAttributeUpdate"},
	{Name: "ObjectIdentifierAndLinkNameTuple"},
	{Name: "ObjectReference"},
	{Name: "PathToObjectIdentifiers"},
	{Name: "PolicyAttachment"},
	{Name: "PolicyToPath"},
	{Name: "Rule"},
	{Name: "SchemaFacet"},
	{Name: "Tag"},
	{Name: "TypedAttributeValue"},
	{Name: "TypedAttributeValueRange"},
	{Name: "TypedLinkAttributeDefinition"},
	{Name: "TypedLinkAttributeRange"},
	{Name: "TypedLinkFacet"},
	{Name: "TypedLinkFacetAttributeUpdate"},
	{Name: "TypedLinkSchemaAndFacetName"},
	{Name: "TypedLinkSpecifier"},
	{Name: "UpgradePublishedSchema"},
}

var cloudDirectoryAPITypeByName = func() map[string]cloudDirectoryAPIType {
	out := make(map[string]cloudDirectoryAPIType, len(cloudDirectoryAPITypes))
	for _, dt := range cloudDirectoryAPITypes {
		out[dt.Name] = dt
	}
	return out
}()
