package server

type cloudFormationOperation struct {
	Name string
}

// AWS CloudFormation operations sourced from:
// https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Operations.html
var cloudFormationOperations = []cloudFormationOperation{
	{Name: "ActivateOrganizationsAccess"},
	{Name: "ActivateType"},
	{Name: "BatchDescribeTypeConfigurations"},
	{Name: "CancelUpdateStack"},
	{Name: "ContinueUpdateRollback"},
	{Name: "CreateChangeSet"},
	{Name: "CreateGeneratedTemplate"},
	{Name: "CreateStack"},
	{Name: "CreateStackInstances"},
	{Name: "CreateStackRefactor"},
	{Name: "CreateStackSet"},
	{Name: "DeactivateOrganizationsAccess"},
	{Name: "DeactivateType"},
	{Name: "DeleteChangeSet"},
	{Name: "DeleteGeneratedTemplate"},
	{Name: "DeleteStack"},
	{Name: "DeleteStackInstances"},
	{Name: "DeleteStackSet"},
	{Name: "DeregisterType"},
	{Name: "DescribeAccountLimits"},
	{Name: "DescribeChangeSet"},
	{Name: "DescribeChangeSetHooks"},
	{Name: "DescribeEvents"},
	{Name: "DescribeGeneratedTemplate"},
	{Name: "DescribeOrganizationsAccess"},
	{Name: "DescribePublisher"},
	{Name: "DescribeResourceScan"},
	{Name: "DescribeStackDriftDetectionStatus"},
	{Name: "DescribeStackEvents"},
	{Name: "DescribeStackInstance"},
	{Name: "DescribeStackRefactor"},
	{Name: "DescribeStackResource"},
	{Name: "DescribeStackResourceDrifts"},
	{Name: "DescribeStackResources"},
	{Name: "DescribeStacks"},
	{Name: "DescribeStackSet"},
	{Name: "DescribeStackSetOperation"},
	{Name: "DescribeType"},
	{Name: "DescribeTypeRegistration"},
	{Name: "DetectStackDrift"},
	{Name: "DetectStackResourceDrift"},
	{Name: "DetectStackSetDrift"},
	{Name: "EstimateTemplateCost"},
	{Name: "ExecuteChangeSet"},
	{Name: "ExecuteStackRefactor"},
	{Name: "GetGeneratedTemplate"},
	{Name: "GetHookResult"},
	{Name: "GetStackPolicy"},
	{Name: "GetTemplate"},
	{Name: "GetTemplateSummary"},
	{Name: "ImportStacksToStackSet"},
	{Name: "ListChangeSets"},
	{Name: "ListExports"},
	{Name: "ListGeneratedTemplates"},
	{Name: "ListHookResults"},
	{Name: "ListImports"},
	{Name: "ListResourceScanRelatedResources"},
	{Name: "ListResourceScanResources"},
	{Name: "ListResourceScans"},
	{Name: "ListStackInstanceResourceDrifts"},
	{Name: "ListStackInstances"},
	{Name: "ListStackRefactorActions"},
	{Name: "ListStackRefactors"},
	{Name: "ListStackResources"},
	{Name: "ListStacks"},
	{Name: "ListStackSetAutoDeploymentTargets"},
	{Name: "ListStackSetOperationResults"},
	{Name: "ListStackSetOperations"},
	{Name: "ListStackSets"},
	{Name: "ListTypeRegistrations"},
	{Name: "ListTypes"},
	{Name: "ListTypeVersions"},
	{Name: "PublishType"},
	{Name: "RecordHandlerProgress"},
	{Name: "RegisterPublisher"},
	{Name: "RegisterType"},
	{Name: "RollbackStack"},
	{Name: "SetStackPolicy"},
	{Name: "SetTypeConfiguration"},
	{Name: "SetTypeDefaultVersion"},
	{Name: "SignalResource"},
	{Name: "StartResourceScan"},
	{Name: "StopStackSetOperation"},
	{Name: "TestType"},
	{Name: "UpdateGeneratedTemplate"},
	{Name: "UpdateStack"},
	{Name: "UpdateStackInstances"},
	{Name: "UpdateStackSet"},
	{Name: "UpdateTerminationProtection"},
	{Name: "ValidateTemplate"},
}

var cloudFormationOperationByName = func() map[string]cloudFormationOperation {
	out := make(map[string]cloudFormationOperation, len(cloudFormationOperations))
	for _, op := range cloudFormationOperations {
		out[op.Name] = op
	}
	return out
}()
