package server

type cloudWatchLogsDataType struct {
	Name string
}

// Amazon CloudWatch Logs data types sourced from:
// https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Types.html
var cloudWatchLogsDataTypes = []cloudWatchLogsDataType{
	{Name: "AccountPolicy"},
	{Name: "AddKeyEntry"},
	{Name: "AddKeys"},
	{Name: "AggregateLogGroupSummary"},
	{Name: "Anomaly"},
	{Name: "AnomalyDetector"},
	{Name: "CSV"},
	{Name: "ConfigurationTemplate"},
	{Name: "ConfigurationTemplateDeliveryConfigValues"},
	{Name: "CopyValue"},
	{Name: "CopyValueEntry"},
	{Name: "DataSource"},
	{Name: "DataSourceFilter"},
	{Name: "DateTimeConverter"},
	{Name: "DeleteKeys"},
	{Name: "Delivery"},
	{Name: "DeliveryDestination"},
	{Name: "DeliveryDestinationConfiguration"},
	{Name: "DeliverySource"},
	{Name: "Destination"},
	{Name: "DestinationConfiguration"},
	{Name: "Entity"},
	{Name: "ExportTask"},
	{Name: "ExportTaskExecutionInfo"},
	{Name: "ExportTaskStatus"},
	{Name: "FieldIndex"},
	{Name: "FieldsData"},
	{Name: "FilteredLogEvent"},
	{Name: "GetLogObjectResponseStream"},
	{Name: "Grok"},
	{Name: "GroupingIdentifier"},
	{Name: "Import"},
	{Name: "ImportBatch"},
	{Name: "ImportFilter"},
	{Name: "ImportStatistics"},
	{Name: "IndexPolicy"},
	{Name: "InputLogEvent"},
	{Name: "IntegrationDetails"},
	{Name: "IntegrationSummary"},
	{Name: "ListToMap"},
	{Name: "LiveTailSessionLogEvent"},
	{Name: "LiveTailSessionMetadata"},
	{Name: "LiveTailSessionStart"},
	{Name: "LiveTailSessionUpdate"},
	{Name: "LogEvent"},
	{Name: "LogFieldType"},
	{Name: "LogFieldsListItem"},
	{Name: "LogGroup"},
	{Name: "LogGroupField"},
	{Name: "LogGroupSummary"},
	{Name: "LogStream"},
	{Name: "LowerCaseString"},
	{Name: "MetricFilter"},
	{Name: "MetricFilterMatchRecord"},
	{Name: "MetricTransformation"},
	{Name: "MoveKeyEntry"},
	{Name: "MoveKeys"},
	{Name: "OpenSearchApplication"},
	{Name: "OpenSearchCollection"},
	{Name: "OpenSearchDataAccessPolicy"},
	{Name: "OpenSearchDataSource"},
	{Name: "OpenSearchEncryptionPolicy"},
	{Name: "OpenSearchIntegrationDetails"},
	{Name: "OpenSearchLifecyclePolicy"},
	{Name: "OpenSearchNetworkPolicy"},
	{Name: "OpenSearchResourceConfig"},
	{Name: "OpenSearchResourceStatus"},
	{Name: "OpenSearchWorkspace"},
	{Name: "OutputLogEvent"},
	{Name: "ParseCloudfront"},
	{Name: "ParseJSON"},
	{Name: "ParseKeyValue"},
	{Name: "ParsePostgres"},
	{Name: "ParseRoute53"},
	{Name: "ParseToOCSF"},
	{Name: "ParseVPC"},
	{Name: "ParseWAF"},
	{Name: "PatternToken"},
	{Name: "Policy"},
	{Name: "Processor"},
	{Name: "QueryCompileError"},
	{Name: "QueryCompileErrorLocation"},
	{Name: "QueryDefinition"},
	{Name: "QueryInfo"},
	{Name: "QueryStatistics"},
	{Name: "RecordField"},
	{Name: "RejectedEntityInfo"},
	{Name: "RejectedLogEventsInfo"},
	{Name: "RenameKeyEntry"},
	{Name: "RenameKeys"},
	{Name: "ResourceConfig"},
	{Name: "ResourcePolicy"},
	{Name: "ResultField"},
	{Name: "S3Configuration"},
	{Name: "S3DeliveryConfiguration"},
	{Name: "S3TableIntegrationSource"},
	{Name: "ScheduledQueryDestination"},
	{Name: "ScheduledQuerySummary"},
	{Name: "SearchedLogStream"},
	{Name: "SplitString"},
	{Name: "SplitStringEntry"},
	{Name: "StartLiveTailResponseStream"},
	{Name: "SubscriptionFilter"},
	{Name: "SubstituteString"},
	{Name: "SubstituteStringEntry"},
	{Name: "SuppressionPeriod"},
	{Name: "TransformedLogRecord"},
	{Name: "TriggerHistoryRecord"},
	{Name: "TrimString"},
	{Name: "TypeConverter"},
	{Name: "TypeConverterEntry"},
	{Name: "UpdateScheduledQuery"},
	{Name: "UpperCaseString"},
}

var cloudWatchLogsDataTypeByName = func() map[string]cloudWatchLogsDataType {
	out := make(map[string]cloudWatchLogsDataType, len(cloudWatchLogsDataTypes))
	for _, dt := range cloudWatchLogsDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
