package server

type cloudFrontOperation struct {
	Name   string
	Method string
	URI    string
}

// Amazon CloudFront operations sourced from:
// https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Operations.html
var cloudFrontOperations = []cloudFrontOperation{
	{Name: "AssociateAlias", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "AssociateDistributionTenantWebACL", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "AssociateDistributionWebACL", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CopyDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateAnycastIpList", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateCachePolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateCloudFrontOriginAccessIdentity", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateConnectionGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateContinuousDeploymentPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateDistributionWithTags", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateFieldLevelEncryptionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateFieldLevelEncryptionProfile", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateInvalidation", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateInvalidationForDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateKeyGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateKeyValueStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateMonitoringSubscription", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateOriginAccessControl", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateOriginRequestPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreatePublicKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateRealtimeLogConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateResponseHeadersPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateStreamingDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateStreamingDistributionWithTags", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateTrustStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "CreateVpcOrigin", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteAnycastIpList", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteCachePolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteCloudFrontOriginAccessIdentity", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteConnectionGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteContinuousDeploymentPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteFieldLevelEncryptionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteFieldLevelEncryptionProfile", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteKeyGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteKeyValueStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteMonitoringSubscription", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteOriginAccessControl", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteOriginRequestPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeletePublicKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteRealtimeLogConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteResponseHeadersPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteStreamingDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteTrustStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteVpcOrigin", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DescribeConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DescribeFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DescribeKeyValueStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DisassociateDistributionTenantWebACL", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DisassociateDistributionWebACL", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetAnycastIpList", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetCachePolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetCachePolicyConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetCloudFrontOriginAccessIdentity", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetCloudFrontOriginAccessIdentityConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetConnectionGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetConnectionGroupByRoutingEndpoint", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetContinuousDeploymentPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetContinuousDeploymentPolicyConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetDistributionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetDistributionTenantByDomain", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetFieldLevelEncryption", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetFieldLevelEncryptionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetFieldLevelEncryptionProfile", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetFieldLevelEncryptionProfileConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetInvalidation", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetInvalidationForDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetKeyGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetKeyGroupConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetManagedCertificateDetails", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetMonitoringSubscription", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetOriginAccessControl", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetOriginAccessControlConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetOriginRequestPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetOriginRequestPolicyConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetPublicKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetPublicKeyConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetRealtimeLogConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetResponseHeadersPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetResponseHeadersPolicyConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetStreamingDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetStreamingDistributionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetTrustStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetVpcOrigin", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListAnycastIpLists", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListCachePolicies", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListCloudFrontOriginAccessIdentities", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListConflictingAliases", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListConnectionFunctions", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListConnectionGroups", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListContinuousDeploymentPolicies", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributions", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByAnycastIpListId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByCachePolicyId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByConnectionMode", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByKeyGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByOriginRequestPolicyId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByRealtimeLogConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByResponseHeadersPolicyId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByTrustStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByVpcOriginId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionsByWebACLId", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionTenants", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDistributionTenantsByCustomization", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListDomainConflicts", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListFieldLevelEncryptionConfigs", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListFieldLevelEncryptionProfiles", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListFunctions", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListInvalidations", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListInvalidationsForDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListKeyGroups", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListKeyValueStores", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListOriginAccessControls", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListOriginRequestPolicies", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListPublicKeys", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListRealtimeLogConfigs", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListResponseHeadersPolicies", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListStreamingDistributions", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListTagsForResource", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListTrustStores", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListVpcOrigins", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "PublishConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "PublishFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "TagResource", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "TestConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "TestFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UntagResource", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateAnycastIpList", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateCachePolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateCloudFrontOriginAccessIdentity", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateConnectionFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateConnectionGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateContinuousDeploymentPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateDistributionTenant", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateDistributionWithStagingConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateDomainAssociation", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateFieldLevelEncryptionConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateFieldLevelEncryptionProfile", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateFunction", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateKeyGroup", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateKeyValueStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateOriginAccessControl", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateOriginRequestPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdatePublicKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateRealtimeLogConfig", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateResponseHeadersPolicy", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateStreamingDistribution", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateTrustStore", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateVpcOrigin", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "VerifyDnsConfiguration", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "DeleteKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "GetKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "ListKeys", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "PutKey", Method: "POST", URI: "/2020-05-31/cloudfront"},
	{Name: "UpdateKeys", Method: "POST", URI: "/2020-05-31/cloudfront"},
}

var cloudFrontOperationByName = func() map[string]cloudFrontOperation {
	out := make(map[string]cloudFrontOperation, len(cloudFrontOperations))
	for _, op := range cloudFrontOperations {
		out[op.Name] = op
	}
	return out
}()
