package server

type codePipelineDataType struct {
	Name string
}

// AWS CodePipeline data types sourced from:
// https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_Types.html
var codePipelineDataTypes = []codePipelineDataType{
	{Name: "ActionConfiguration"},
	{Name: "ActionConfigurationProperty"},
	{Name: "ActionContext"},
	{Name: "ActionDeclaration"},
	{Name: "ActionExecution"},
	{Name: "ActionExecutionDetail"},
	{Name: "ActionExecutionFilter"},
	{Name: "ActionExecutionInput"},
	{Name: "ActionExecutionOutput"},
	{Name: "ActionExecutionResult"},
	{Name: "ActionRevision"},
	{Name: "ActionState"},
	{Name: "ActionType"},
	{Name: "ActionTypeArtifactDetails"},
	{Name: "ActionTypeDeclaration"},
	{Name: "ActionTypeExecutor"},
	{Name: "ActionTypeId"},
	{Name: "ActionTypeIdentifier"},
	{Name: "ActionTypePermissions"},
	{Name: "ActionTypeProperty"},
	{Name: "ActionTypeSettings"},
	{Name: "ActionTypeUrls"},
	{Name: "ApprovalResult"},
	{Name: "Artifact"},
	{Name: "ArtifactDetail"},
	{Name: "ArtifactDetails"},
	{Name: "ArtifactLocation"},
	{Name: "ArtifactRevision"},
	{Name: "ArtifactStore"},
	{Name: "AWSSessionCredentials"},
	{Name: "BeforeEntryConditions"},
	{Name: "BlockerDeclaration"},
	{Name: "Condition"},
	{Name: "ConditionExecution"},
	{Name: "ConditionState"},
	{Name: "CurrentRevision"},
	{Name: "DeployActionExecutionTarget"},
	{Name: "DeployTargetEvent"},
	{Name: "DeployTargetEventContext"},
	{Name: "EncryptionKey"},
	{Name: "EnvironmentVariable"},
	{Name: "ErrorDetails"},
	{Name: "ExecutionDetails"},
	{Name: "ExecutionTrigger"},
	{Name: "ExecutorConfiguration"},
	{Name: "FailureConditions"},
	{Name: "FailureDetails"},
	{Name: "GitBranchFilterCriteria"},
	{Name: "GitConfiguration"},
	{Name: "GitFilePathFilterCriteria"},
	{Name: "GitPullRequestFilter"},
	{Name: "GitPushFilter"},
	{Name: "GitTagFilterCriteria"},
	{Name: "InputArtifact"},
	{Name: "Job"},
	{Name: "JobData"},
	{Name: "JobDetails"},
	{Name: "JobWorkerExecutorConfiguration"},
	{Name: "LambdaExecutorConfiguration"},
	{Name: "LatestInPipelineExecutionFilter"},
	{Name: "ListWebhookItem"},
	{Name: "OutputArtifact"},
	{Name: "PipelineContext"},
	{Name: "PipelineDeclaration"},
	{Name: "PipelineExecution"},
	{Name: "PipelineExecutionFilter"},
	{Name: "PipelineExecutionSummary"},
	{Name: "PipelineMetadata"},
	{Name: "PipelineRollbackMetadata"},
	{Name: "PipelineSummary"},
	{Name: "PipelineTriggerDeclaration"},
	{Name: "PipelineVariable"},
	{Name: "PipelineVariableDeclaration"},
	{Name: "ResolvedPipelineVariable"},
	{Name: "RetryConfiguration"},
	{Name: "RetryStageMetadata"},
	{Name: "RuleConfigurationProperty"},
	{Name: "RuleDeclaration"},
	{Name: "RuleExecution"},
	{Name: "RuleExecutionDetail"},
	{Name: "RuleExecutionFilter"},
	{Name: "RuleExecutionInput"},
	{Name: "RuleExecutionOutput"},
	{Name: "RuleExecutionResult"},
	{Name: "RuleRevision"},
	{Name: "RuleState"},
	{Name: "RuleType"},
	{Name: "RuleTypeId"},
	{Name: "RuleTypeSettings"},
	{Name: "S3ArtifactLocation"},
	{Name: "S3Location"},
	{Name: "SourceRevision"},
	{Name: "SourceRevisionOverride"},
	{Name: "StageConditionsExecution"},
	{Name: "StageConditionState"},
	{Name: "StageContext"},
	{Name: "StageDeclaration"},
	{Name: "StageExecution"},
	{Name: "StageState"},
	{Name: "StopExecutionTrigger"},
	{Name: "SucceededInStageFilter"},
	{Name: "SuccessConditions"},
	{Name: "Tag"},
	{Name: "TargetFilter"},
	{Name: "ThirdPartyJob"},
	{Name: "ThirdPartyJobData"},
	{Name: "ThirdPartyJobDetails"},
	{Name: "TransitionState"},
	{Name: "WebhookAuthConfiguration"},
	{Name: "WebhookDefinition"},
	{Name: "WebhookFilterRule"},
	{Name: "UpdatePipeline"},
}

var codePipelineDataTypeByName = func() map[string]codePipelineDataType {
	out := make(map[string]codePipelineDataType, len(codePipelineDataTypes))
	for _, dt := range codePipelineDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
