package server

type cognitoUserPoolsOperation struct {
	Name string
}

// Amazon Cognito User Pools operations sourced from:
// https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html
var cognitoUserPoolsOperations = []cognitoUserPoolsOperation{
	{Name: "AddCustomAttributes"},
	{Name: "AdminAddUserToGroup"},
	{Name: "AdminConfirmSignUp"},
	{Name: "AdminCreateUser"},
	{Name: "AdminDeleteUser"},
	{Name: "AdminDeleteUserAttributes"},
	{Name: "AdminDisableProviderForUser"},
	{Name: "AdminDisableUser"},
	{Name: "AdminEnableUser"},
	{Name: "AdminForgetDevice"},
	{Name: "AdminGetDevice"},
	{Name: "AdminGetUser"},
	{Name: "AdminInitiateAuth"},
	{Name: "AdminLinkProviderForUser"},
	{Name: "AdminListDevices"},
	{Name: "AdminListGroupsForUser"},
	{Name: "AdminListUserAuthEvents"},
	{Name: "AdminRemoveUserFromGroup"},
	{Name: "AdminResetUserPassword"},
	{Name: "AdminRespondToAuthChallenge"},
	{Name: "AdminSetUserMFAPreference"},
	{Name: "AdminSetUserPassword"},
	{Name: "AdminSetUserSettings"},
	{Name: "AdminUpdateAuthEventFeedback"},
	{Name: "AdminUpdateDeviceStatus"},
	{Name: "AdminUpdateUserAttributes"},
	{Name: "AdminUserGlobalSignOut"},
	{Name: "AssociateSoftwareToken"},
	{Name: "ChangePassword"},
	{Name: "CompleteWebAuthnRegistration"},
	{Name: "ConfirmDevice"},
	{Name: "ConfirmForgotPassword"},
	{Name: "ConfirmSignUp"},
	{Name: "CreateGroup"},
	{Name: "CreateIdentityProvider"},
	{Name: "CreateManagedLoginBranding"},
	{Name: "CreateResourceServer"},
	{Name: "CreateTerms"},
	{Name: "CreateUserImportJob"},
	{Name: "CreateUserPool"},
	{Name: "CreateUserPoolClient"},
	{Name: "CreateUserPoolDomain"},
	{Name: "DeleteGroup"},
	{Name: "DeleteIdentityProvider"},
	{Name: "DeleteManagedLoginBranding"},
	{Name: "DeleteResourceServer"},
	{Name: "DeleteTerms"},
	{Name: "DeleteUser"},
	{Name: "DeleteUserAttributes"},
	{Name: "DeleteUserPool"},
	{Name: "DeleteUserPoolClient"},
	{Name: "DeleteUserPoolDomain"},
	{Name: "DeleteWebAuthnCredential"},
	{Name: "DescribeIdentityProvider"},
	{Name: "DescribeManagedLoginBranding"},
	{Name: "DescribeManagedLoginBrandingByClient"},
	{Name: "DescribeResourceServer"},
	{Name: "DescribeRiskConfiguration"},
	{Name: "DescribeTerms"},
	{Name: "DescribeUserImportJob"},
	{Name: "DescribeUserPool"},
	{Name: "DescribeUserPoolClient"},
	{Name: "DescribeUserPoolDomain"},
	{Name: "ForgetDevice"},
	{Name: "ForgotPassword"},
	{Name: "GetCSVHeader"},
	{Name: "GetDevice"},
	{Name: "GetGroup"},
	{Name: "GetIdentityProviderByIdentifier"},
	{Name: "GetLogDeliveryConfiguration"},
	{Name: "GetSigningCertificate"},
	{Name: "GetTokensFromRefreshToken"},
	{Name: "GetUICustomization"},
	{Name: "GetUser"},
	{Name: "GetUserAttributeVerificationCode"},
	{Name: "GetUserAuthFactors"},
	{Name: "GetUserPoolMfaConfig"},
	{Name: "GlobalSignOut"},
	{Name: "InitiateAuth"},
	{Name: "ListDevices"},
	{Name: "ListGroups"},
	{Name: "ListIdentityProviders"},
	{Name: "ListResourceServers"},
	{Name: "ListTagsForResource"},
	{Name: "ListTerms"},
	{Name: "ListUserImportJobs"},
	{Name: "ListUserPoolClients"},
	{Name: "ListUserPools"},
	{Name: "ListUsers"},
	{Name: "ListUsersInGroup"},
	{Name: "ListWebAuthnCredentials"},
	{Name: "ResendConfirmationCode"},
	{Name: "RespondToAuthChallenge"},
	{Name: "RevokeToken"},
	{Name: "SetLogDeliveryConfiguration"},
	{Name: "SetRiskConfiguration"},
	{Name: "SetUICustomization"},
	{Name: "SetUserMFAPreference"},
	{Name: "SetUserPoolMfaConfig"},
	{Name: "SetUserSettings"},
	{Name: "SignUp"},
	{Name: "StartUserImportJob"},
	{Name: "StartWebAuthnRegistration"},
	{Name: "StopUserImportJob"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateAuthEventFeedback"},
	{Name: "UpdateDeviceStatus"},
	{Name: "UpdateGroup"},
	{Name: "UpdateIdentityProvider"},
	{Name: "UpdateManagedLoginBranding"},
	{Name: "UpdateResourceServer"},
	{Name: "UpdateTerms"},
	{Name: "UpdateUserAttributes"},
	{Name: "UpdateUserPool"},
	{Name: "UpdateUserPoolClient"},
	{Name: "UpdateUserPoolDomain"},
	{Name: "VerifySoftwareToken"},
	{Name: "VerifyUserAttribute"},
}

var cognitoUserPoolsOperationByName = func() map[string]cognitoUserPoolsOperation {
	out := make(map[string]cognitoUserPoolsOperation, len(cognitoUserPoolsOperations))
	for _, op := range cognitoUserPoolsOperations {
		out[op.Name] = op
	}
	return out
}()
