package server

type cognitoUserPoolsDataType struct {
	Name string
}

// Amazon Cognito User Pools data types sourced from:
// https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Types.html
var cognitoUserPoolsDataTypes = []cognitoUserPoolsDataType{
	{Name: "AccountRecoverySettingType"},
	{Name: "AccountTakeoverActionType"},
	{Name: "AccountTakeoverActionsType"},
	{Name: "AccountTakeoverRiskConfigurationType"},
	{Name: "AdminCreateUserConfigType"},
	{Name: "AdvancedSecurityAdditionalFlowsType"},
	{Name: "AnalyticsConfigurationType"},
	{Name: "AnalyticsMetadataType"},
	{Name: "AssetType"},
	{Name: "AttributeType"},
	{Name: "AuthEventType"},
	{Name: "AuthenticationResultType"},
	{Name: "ChallengeResponseType"},
	{Name: "CloudWatchLogsConfigurationType"},
	{Name: "CodeDeliveryDetailsType"},
	{Name: "CompromisedCredentialsActionsType"},
	{Name: "CompromisedCredentialsRiskConfigurationType"},
	{Name: "ContextDataType"},
	{Name: "CustomDomainConfigType"},
	{Name: "CustomEmailLambdaVersionConfigType"},
	{Name: "CustomSMSLambdaVersionConfigType"},
	{Name: "DeviceConfigurationType"},
	{Name: "DeviceSecretVerifierConfigType"},
	{Name: "DeviceType"},
	{Name: "DomainDescriptionType"},
	{Name: "EmailConfigurationType"},
	{Name: "EmailMfaConfigType"},
	{Name: "EmailMfaSettingsType"},
	{Name: "EventContextDataType"},
	{Name: "EventFeedbackType"},
	{Name: "EventRiskType"},
	{Name: "FirehoseConfigurationType"},
	{Name: "GroupType"},
	{Name: "HttpHeader"},
	{Name: "IdentityProviderType"},
	{Name: "InboundFederationLambdaType"},
	{Name: "LambdaConfigType"},
	{Name: "LogConfigurationType"},
	{Name: "LogDeliveryConfigurationType"},
	{Name: "MFAOptionType"},
	{Name: "ManagedLoginBrandingType"},
	{Name: "MessageTemplateType"},
	{Name: "NewDeviceMetadataType"},
	{Name: "NotifyConfigurationType"},
	{Name: "NotifyEmailType"},
	{Name: "NumberAttributeConstraintsType"},
	{Name: "PasswordPolicyType"},
	{Name: "PreTokenGenerationVersionConfigType"},
	{Name: "ProviderDescription"},
	{Name: "ProviderUserIdentifierType"},
	{Name: "RecoveryOptionType"},
	{Name: "RefreshTokenRotationType"},
	{Name: "ResourceServerScopeType"},
	{Name: "ResourceServerType"},
	{Name: "RiskConfigurationType"},
	{Name: "RiskExceptionConfigurationType"},
	{Name: "S3ConfigurationType"},
	{Name: "SMSMfaSettingsType"},
	{Name: "SchemaAttributeType"},
	{Name: "SignInPolicyType"},
	{Name: "SmsConfigurationType"},
	{Name: "SmsMfaConfigType"},
	{Name: "SoftwareTokenMfaConfigType"},
	{Name: "SoftwareTokenMfaSettingsType"},
	{Name: "StringAttributeConstraintsType"},
	{Name: "TermsDescriptionType"},
	{Name: "TermsType"},
	{Name: "TokenValidityUnitsType"},
	{Name: "UICustomizationType"},
	{Name: "UserAttributeUpdateSettingsType"},
	{Name: "UserContextDataType"},
	{Name: "UserImportJobType"},
	{Name: "UserPoolAddOnsType"},
	{Name: "UserPoolClientDescription"},
	{Name: "UserPoolClientType"},
	{Name: "UserPoolDescriptionType"},
	{Name: "UserPoolPolicyType"},
	{Name: "UserPoolType"},
	{Name: "UserType"},
	{Name: "UsernameConfigurationType"},
	{Name: "VerificationMessageTemplateType"},
	{Name: "VerifyUserAttribute"},
	{Name: "WebAuthnConfigurationType"},
	{Name: "WebAuthnCredentialDescription"},
}

var cognitoUserPoolsDataTypeByName = func() map[string]cognitoUserPoolsDataType {
	out := make(map[string]cognitoUserPoolsDataType, len(cognitoUserPoolsDataTypes))
	for _, dt := range cognitoUserPoolsDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
