package server

type comprehendDataType struct {
	Name string
}

// Amazon Comprehend data types sourced from:
// https://docs.aws.amazon.com/comprehend/latest/APIReference/API_Types.html
var comprehendDataTypes = []comprehendDataType{
	{Name: "AugmentedManifestsListItem"},
	{Name: "BatchDetectDominantLanguageItemResult"},
	{Name: "BatchDetectEntitiesItemResult"},
	{Name: "BatchDetectKeyPhrasesItemResult"},
	{Name: "BatchDetectSentimentItemResult"},
	{Name: "BatchDetectSyntaxItemResult"},
	{Name: "BatchDetectTargetedSentimentItemResult"},
	{Name: "BatchItemError"},
	{Name: "Block"},
	{Name: "BlockReference"},
	{Name: "BoundingBox"},
	{Name: "ChildBlock"},
	{Name: "ClassifierEvaluationMetrics"},
	{Name: "ClassifierMetadata"},
	{Name: "DataSecurityConfig"},
	{Name: "DatasetAugmentedManifestsListItem"},
	{Name: "DatasetDocumentClassifierInputDataConfig"},
	{Name: "DatasetEntityRecognizerAnnotations"},
	{Name: "DatasetEntityRecognizerDocuments"},
	{Name: "DatasetEntityRecognizerEntityList"},
	{Name: "DatasetEntityRecognizerInputDataConfig"},
	{Name: "DatasetFilter"},
	{Name: "DatasetInputDataConfig"},
	{Name: "DatasetProperties"},
	{Name: "DocumentClass"},
	{Name: "DocumentClassificationConfig"},
	{Name: "DocumentClassificationJobFilter"},
	{Name: "DocumentClassificationJobProperties"},
	{Name: "DocumentClassifierDocuments"},
	{Name: "DocumentClassifierFilter"},
	{Name: "DocumentClassifierInputDataConfig"},
	{Name: "DocumentClassifierOutputDataConfig"},
	{Name: "DocumentClassifierProperties"},
	{Name: "DocumentClassifierSummary"},
	{Name: "DocumentLabel"},
	{Name: "DocumentMetadata"},
	{Name: "DocumentReaderConfig"},
	{Name: "DocumentTypeListItem"},
	{Name: "DominantLanguage"},
	{Name: "DominantLanguageDetectionJobFilter"},
	{Name: "DominantLanguageDetectionJobProperties"},
	{Name: "EndpointFilter"},
	{Name: "EndpointProperties"},
	{Name: "EntitiesDetectionJobFilter"},
	{Name: "EntitiesDetectionJobProperties"},
	{Name: "Entity"},
	{Name: "EntityLabel"},
	{Name: "EntityRecognitionConfig"},
	{Name: "EntityRecognizerAnnotations"},
	{Name: "EntityRecognizerDocuments"},
	{Name: "EntityRecognizerEntityList"},
	{Name: "EntityRecognizerEvaluationMetrics"},
	{Name: "EntityRecognizerFilter"},
	{Name: "EntityRecognizerInputDataConfig"},
	{Name: "EntityRecognizerMetadata"},
	{Name: "EntityRecognizerMetadataEntityTypesListItem"},
	{Name: "EntityRecognizerOutputDataConfig"},
	{Name: "EntityRecognizerProperties"},
	{Name: "EntityRecognizerSummary"},
	{Name: "EntityTypesEvaluationMetrics"},
	{Name: "EntityTypesListItem"},
	{Name: "ErrorsListItem"},
	{Name: "EventsDetectionJobFilter"},
	{Name: "EventsDetectionJobProperties"},
	{Name: "ExtractedCharactersListItem"},
	{Name: "FlywheelFilter"},
	{Name: "FlywheelIterationFilter"},
	{Name: "FlywheelIterationProperties"},
	{Name: "FlywheelModelEvaluationMetrics"},
	{Name: "FlywheelProperties"},
	{Name: "FlywheelSummary"},
	{Name: "Geometry"},
	{Name: "InputDataConfig"},
	{Name: "InvalidRequestDetail"},
	{Name: "KeyPhrase"},
	{Name: "KeyPhrasesDetectionJobFilter"},
	{Name: "KeyPhrasesDetectionJobProperties"},
	{Name: "MentionSentiment"},
	{Name: "OutputDataConfig"},
	{Name: "PartOfSpeechTag"},
	{Name: "PiiEntitiesDetectionJobFilter"},
	{Name: "PiiEntitiesDetectionJobProperties"},
	{Name: "PiiEntity"},
	{Name: "PiiOutputDataConfig"},
	{Name: "Point"},
	{Name: "RedactionConfig"},
	{Name: "RelationshipsListItem"},
	{Name: "SentimentDetectionJobFilter"},
	{Name: "SentimentDetectionJobProperties"},
	{Name: "SentimentScore"},
	{Name: "SyntaxToken"},
	{Name: "Tag"},
	{Name: "TargetedSentimentDetectionJobFilter"},
	{Name: "TargetedSentimentDetectionJobProperties"},
	{Name: "TargetedSentimentEntity"},
	{Name: "TargetedSentimentMention"},
	{Name: "TaskConfig"},
	{Name: "TextSegment"},
	{Name: "TopicsDetectionJobFilter"},
	{Name: "TopicsDetectionJobProperties"},
	{Name: "ToxicContent"},
	{Name: "ToxicLabels"},
	{Name: "UpdateDataSecurityConfig"},
	{Name: "UpdateFlywheel"},
	{Name: "VpcConfig"},
	{Name: "WarningsListItem"},
}

var comprehendDataTypeByName = func() map[string]comprehendDataType {
	out := make(map[string]comprehendDataType, len(comprehendDataTypes))
	for _, dt := range comprehendDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
