package server

type comprehendOperation struct {
	Name string
}

// Amazon Comprehend operations sourced from:
// https://docs.aws.amazon.com/comprehend/latest/APIReference/API_Operations.html
var comprehendOperations = []comprehendOperation{
	{Name: "BatchDetectDominantLanguage"},
	{Name: "BatchDetectEntities"},
	{Name: "BatchDetectKeyPhrases"},
	{Name: "BatchDetectSentiment"},
	{Name: "BatchDetectSyntax"},
	{Name: "BatchDetectTargetedSentiment"},
	{Name: "ClassifyDocument"},
	{Name: "ContainsPiiEntities"},
	{Name: "CreateDataset"},
	{Name: "CreateDocumentClassifier"},
	{Name: "CreateEndpoint"},
	{Name: "CreateEntityRecognizer"},
	{Name: "CreateFlywheel"},
	{Name: "DeleteDocumentClassifier"},
	{Name: "DeleteEndpoint"},
	{Name: "DeleteEntityRecognizer"},
	{Name: "DeleteFlywheel"},
	{Name: "DeleteResourcePolicy"},
	{Name: "DescribeDataset"},
	{Name: "DescribeDocumentClassificationJob"},
	{Name: "DescribeDocumentClassifier"},
	{Name: "DescribeDominantLanguageDetectionJob"},
	{Name: "DescribeEndpoint"},
	{Name: "DescribeEntitiesDetectionJob"},
	{Name: "DescribeEntityRecognizer"},
	{Name: "DescribeEventsDetectionJob"},
	{Name: "DescribeFlywheel"},
	{Name: "DescribeFlywheelIteration"},
	{Name: "DescribeKeyPhrasesDetectionJob"},
	{Name: "DescribePiiEntitiesDetectionJob"},
	{Name: "DescribeResourcePolicy"},
	{Name: "DescribeSentimentDetectionJob"},
	{Name: "DescribeTargetedSentimentDetectionJob"},
	{Name: "DescribeTopicsDetectionJob"},
	{Name: "DetectDominantLanguage"},
	{Name: "DetectEntities"},
	{Name: "DetectKeyPhrases"},
	{Name: "DetectPiiEntities"},
	{Name: "DetectSentiment"},
	{Name: "DetectSyntax"},
	{Name: "DetectTargetedSentiment"},
	{Name: "DetectToxicContent"},
	{Name: "ImportModel"},
	{Name: "ListDatasets"},
	{Name: "ListDocumentClassificationJobs"},
	{Name: "ListDocumentClassifierSummaries"},
	{Name: "ListDocumentClassifiers"},
	{Name: "ListDominantLanguageDetectionJobs"},
	{Name: "ListEndpoints"},
	{Name: "ListEntitiesDetectionJobs"},
	{Name: "ListEntityRecognizerSummaries"},
	{Name: "ListEntityRecognizers"},
	{Name: "ListEventsDetectionJobs"},
	{Name: "ListFlywheelIterationHistory"},
	{Name: "ListFlywheels"},
	{Name: "ListKeyPhrasesDetectionJobs"},
	{Name: "ListPiiEntitiesDetectionJobs"},
	{Name: "ListSentimentDetectionJobs"},
	{Name: "ListTagsForResource"},
	{Name: "ListTargetedSentimentDetectionJobs"},
	{Name: "ListTopicsDetectionJobs"},
	{Name: "PutResourcePolicy"},
	{Name: "StartDocumentClassificationJob"},
	{Name: "StartDominantLanguageDetectionJob"},
	{Name: "StartEntitiesDetectionJob"},
	{Name: "StartEventsDetectionJob"},
	{Name: "StartFlywheelIteration"},
	{Name: "StartKeyPhrasesDetectionJob"},
	{Name: "StartPiiEntitiesDetectionJob"},
	{Name: "StartSentimentDetectionJob"},
	{Name: "StartTargetedSentimentDetectionJob"},
	{Name: "StartTopicsDetectionJob"},
	{Name: "StopDominantLanguageDetectionJob"},
	{Name: "StopEntitiesDetectionJob"},
	{Name: "StopEventsDetectionJob"},
	{Name: "StopKeyPhrasesDetectionJob"},
	{Name: "StopPiiEntitiesDetectionJob"},
	{Name: "StopSentimentDetectionJob"},
	{Name: "StopTargetedSentimentDetectionJob"},
	{Name: "StopTrainingDocumentClassifier"},
	{Name: "StopTrainingEntityRecognizer"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateEndpoint"},
	{Name: "UpdateFlywheel"},
}

var comprehendOperationByName = func() map[string]comprehendOperation {
	out := make(map[string]comprehendOperation, len(comprehendOperations))
	for _, op := range comprehendOperations {
		out[op.Name] = op
	}
	return out
}()
