package server

type configDataType struct {
	Name string
}

// AWS Config data types sourced from:
// https://docs.aws.amazon.com/config/latest/APIReference/API_Types.html
var configDataTypes = []configDataType{
	{Name: "AccountAggregationSource"},
	{Name: "AggregateComplianceByConfigRule"},
	{Name: "AggregateComplianceByConformancePack"},
	{Name: "AggregateComplianceCount"},
	{Name: "AggregateConformancePackCompliance"},
	{Name: "AggregateConformancePackComplianceCount"},
	{Name: "AggregateConformancePackComplianceFilters"},
	{Name: "AggregateConformancePackComplianceSummary"},
	{Name: "AggregateConformancePackComplianceSummaryFilters"},
	{Name: "AggregateEvaluationResult"},
	{Name: "AggregateResourceIdentifier"},
	{Name: "AggregatedSourceStatus"},
	{Name: "AggregationAuthorization"},
	{Name: "AggregatorFilterResourceType"},
	{Name: "AggregatorFilterServicePrincipal"},
	{Name: "AggregatorFilters"},
	{Name: "BaseConfigurationItem"},
	{Name: "Compliance"},
	{Name: "ComplianceByConfigRule"},
	{Name: "ComplianceByResource"},
	{Name: "ComplianceContributorCount"},
	{Name: "ComplianceSummary"},
	{Name: "ComplianceSummaryByResourceType"},
	{Name: "ConfigExportDeliveryInfo"},
	{Name: "ConfigRule"},
	{Name: "ConfigRuleComplianceFilters"},
	{Name: "ConfigRuleComplianceSummaryFilters"},
	{Name: "ConfigRuleEvaluationStatus"},
	{Name: "ConfigSnapshotDeliveryProperties"},
	{Name: "ConfigStreamDeliveryInfo"},
	{Name: "ConfigurationAggregator"},
	{Name: "ConfigurationItem"},
	{Name: "ConfigurationRecorder"},
	{Name: "ConfigurationRecorderFilter"},
	{Name: "ConfigurationRecorderStatus"},
	{Name: "ConfigurationRecorderSummary"},
	{Name: "ConformancePackComplianceFilters"},
	{Name: "ConformancePackComplianceScore"},
	{Name: "ConformancePackComplianceScoresFilters"},
	{Name: "ConformancePackComplianceSummary"},
	{Name: "ConformancePackDetail"},
	{Name: "ConformancePackEvaluationFilters"},
	{Name: "ConformancePackEvaluationResult"},
	{Name: "ConformancePackInputParameter"},
	{Name: "ConformancePackRuleCompliance"},
	{Name: "ConformancePackStatusDetail"},
	{Name: "CustomPolicyDetails"},
	{Name: "DeliveryChannel"},
	{Name: "DeliveryChannelStatus"},
	{Name: "DescribeConfigRulesFilters"},
	{Name: "Evaluation"},
	{Name: "EvaluationContext"},
	{Name: "EvaluationModeConfiguration"},
	{Name: "EvaluationResult"},
	{Name: "EvaluationResultIdentifier"},
	{Name: "EvaluationResultQualifier"},
	{Name: "EvaluationStatus"},
	{Name: "ExclusionByResourceTypes"},
	{Name: "ExecutionControls"},
	{Name: "ExternalEvaluation"},
	{Name: "FailedDeleteRemediationExceptionsBatch"},
	{Name: "FailedRemediationBatch"},
	{Name: "FailedRemediationExceptionBatch"},
	{Name: "FieldInfo"},
	{Name: "GroupedResourceCount"},
	{Name: "MemberAccountStatus"},
	{Name: "OrganizationAggregationSource"},
	{Name: "OrganizationConfigRule"},
	{Name: "OrganizationConfigRuleStatus"},
	{Name: "OrganizationConformancePack"},
	{Name: "OrganizationConformancePackDetailedStatus"},
	{Name: "OrganizationConformancePackStatus"},
	{Name: "OrganizationCustomPolicyRuleMetadata"},
	{Name: "OrganizationCustomPolicyRuleMetadataNoPolicy"},
	{Name: "OrganizationCustomRuleMetadata"},
	{Name: "OrganizationManagedRuleMetadata"},
	{Name: "OrganizationResourceDetailedStatusFilters"},
	{Name: "PendingAggregationRequest"},
	{Name: "QueryInfo"},
	{Name: "RecordingGroup"},
	{Name: "RecordingMode"},
	{Name: "RecordingModeOverride"},
	{Name: "RecordingStrategy"},
	{Name: "Relationship"},
	{Name: "RemediationConfiguration"},
	{Name: "RemediationException"},
	{Name: "RemediationExceptionResourceKey"},
	{Name: "RemediationExecutionStatus"},
	{Name: "RemediationExecutionStep"},
	{Name: "RemediationParameterValue"},
	{Name: "ResourceCount"},
	{Name: "ResourceCountFilters"},
	{Name: "ResourceDetails"},
	{Name: "ResourceEvaluation"},
	{Name: "ResourceEvaluationFilters"},
	{Name: "ResourceFilters"},
	{Name: "ResourceIdentifier"},
	{Name: "ResourceKey"},
	{Name: "ResourceValue"},
	{Name: "RetentionConfiguration"},
	{Name: "Scope"},
	{Name: "Source"},
	{Name: "SourceDetail"},
	{Name: "SsmControls"},
	{Name: "StaticValue"},
	{Name: "StatusDetailFilters"},
	{Name: "StoredQuery"},
	{Name: "StoredQueryMetadata"},
	{Name: "Tag"},
	{Name: "TemplateSSMDocumentDetails"},
	{Name: "TimeWindow"},
	{Name: "UntagResource"},
}

var configDataTypeByName = func() map[string]configDataType {
	out := make(map[string]configDataType, len(configDataTypes))
	for _, dt := range configDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
