package server

type configOperation struct {
	Name string
}

// AWS Config actions sourced from:
// https://docs.aws.amazon.com/config/latest/APIReference/API_Operations.html
var configOperations = []configOperation{
	{Name: "AssociateResourceTypes"},
	{Name: "BatchGetAggregateResourceConfig"},
	{Name: "BatchGetResourceConfig"},
	{Name: "DeleteAggregationAuthorization"},
	{Name: "DeleteConfigRule"},
	{Name: "DeleteConfigurationAggregator"},
	{Name: "DeleteConfigurationRecorder"},
	{Name: "DeleteConformancePack"},
	{Name: "DeleteDeliveryChannel"},
	{Name: "DeleteEvaluationResults"},
	{Name: "DeleteOrganizationConfigRule"},
	{Name: "DeleteOrganizationConformancePack"},
	{Name: "DeletePendingAggregationRequest"},
	{Name: "DeleteRemediationConfiguration"},
	{Name: "DeleteRemediationExceptions"},
	{Name: "DeleteResourceConfig"},
	{Name: "DeleteRetentionConfiguration"},
	{Name: "DeleteServiceLinkedConfigurationRecorder"},
	{Name: "DeleteStoredQuery"},
	{Name: "DeliverConfigSnapshot"},
	{Name: "DescribeAggregateComplianceByConfigRules"},
	{Name: "DescribeAggregateComplianceByConformancePacks"},
	{Name: "DescribeAggregationAuthorizations"},
	{Name: "DescribeComplianceByConfigRule"},
	{Name: "DescribeComplianceByResource"},
	{Name: "DescribeConfigRuleEvaluationStatus"},
	{Name: "DescribeConfigRules"},
	{Name: "DescribeConfigurationAggregatorSourcesStatus"},
	{Name: "DescribeConfigurationAggregators"},
	{Name: "DescribeConfigurationRecorderStatus"},
	{Name: "DescribeConfigurationRecorders"},
	{Name: "DescribeConformancePackCompliance"},
	{Name: "DescribeConformancePackStatus"},
	{Name: "DescribeConformancePacks"},
	{Name: "DescribeDeliveryChannelStatus"},
	{Name: "DescribeDeliveryChannels"},
	{Name: "DescribeOrganizationConfigRuleStatuses"},
	{Name: "DescribeOrganizationConfigRules"},
	{Name: "DescribeOrganizationConformancePackStatuses"},
	{Name: "DescribeOrganizationConformancePacks"},
	{Name: "DescribePendingAggregationRequests"},
	{Name: "DescribeRemediationConfigurations"},
	{Name: "DescribeRemediationExceptions"},
	{Name: "DescribeRemediationExecutionStatus"},
	{Name: "DescribeRetentionConfigurations"},
	{Name: "DisassociateResourceTypes"},
	{Name: "GetAggregateComplianceDetailsByConfigRule"},
	{Name: "GetAggregateConfigRuleComplianceSummary"},
	{Name: "GetAggregateConformancePackComplianceSummary"},
	{Name: "GetAggregateDiscoveredResourceCounts"},
	{Name: "GetAggregateResourceConfig"},
	{Name: "GetComplianceDetailsByConfigRule"},
	{Name: "GetComplianceDetailsByResource"},
	{Name: "GetComplianceSummaryByConfigRule"},
	{Name: "GetComplianceSummaryByResourceType"},
	{Name: "GetConformancePackComplianceDetails"},
	{Name: "GetConformancePackComplianceSummary"},
	{Name: "GetCustomRulePolicy"},
	{Name: "GetDiscoveredResourceCounts"},
	{Name: "GetOrganizationConfigRuleDetailedStatus"},
	{Name: "GetOrganizationConformancePackDetailedStatus"},
	{Name: "GetOrganizationCustomRulePolicy"},
	{Name: "GetResourceConfigHistory"},
	{Name: "GetResourceEvaluationSummary"},
	{Name: "GetStoredQuery"},
	{Name: "ListAggregateDiscoveredResources"},
	{Name: "ListConfigurationRecorders"},
	{Name: "ListConformancePackComplianceScores"},
	{Name: "ListDiscoveredResources"},
	{Name: "ListResourceEvaluations"},
	{Name: "ListStoredQueries"},
	{Name: "ListTagsForResource"},
	{Name: "PutAggregationAuthorization"},
	{Name: "PutConfigRule"},
	{Name: "PutConfigurationAggregator"},
	{Name: "PutConfigurationRecorder"},
	{Name: "PutConformancePack"},
	{Name: "PutDeliveryChannel"},
	{Name: "PutEvaluations"},
	{Name: "PutExternalEvaluation"},
	{Name: "PutOrganizationConfigRule"},
	{Name: "PutOrganizationConformancePack"},
	{Name: "PutRemediationConfigurations"},
	{Name: "PutRemediationExceptions"},
	{Name: "PutResourceConfig"},
	{Name: "PutRetentionConfiguration"},
	{Name: "PutServiceLinkedConfigurationRecorder"},
	{Name: "PutStoredQuery"},
	{Name: "SelectAggregateResourceConfig"},
	{Name: "SelectResourceConfig"},
	{Name: "StartConfigRulesEvaluation"},
	{Name: "StartConfigurationRecorder"},
	{Name: "StartRemediationExecution"},
	{Name: "StartResourceEvaluation"},
	{Name: "StopConfigurationRecorder"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
}

var configOperationByName = func() map[string]configOperation {
	out := make(map[string]configOperation, len(configOperations))
	for _, op := range configOperations {
		out[op.Name] = op
	}
	return out
}()
