package server

type deadlineOperation struct {
	Name   string
	Method string
	URI    string
}

// AWS Deadline Cloud operations sourced from:
// https://docs.aws.amazon.com/deadline-cloud/latest/APIReference/API_Operations.html
var deadlineOperations = []deadlineOperation{
	{Name: "AssociateMemberToFarm", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/members/{principalId}"},
	{Name: "AssociateMemberToFleet", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/members/{principalId}"},
	{Name: "AssociateMemberToJob", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/members/{principalId}"},
	{Name: "AssociateMemberToQueue", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/members/{principalId}"},
	{Name: "AssumeFleetRoleForRead", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/read-roles"},
	{Name: "AssumeFleetRoleForWorker", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}/fleet-roles"},
	{Name: "AssumeQueueRoleForRead", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/read-roles"},
	{Name: "AssumeQueueRoleForUser", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/user-roles"},
	{Name: "AssumeQueueRoleForWorker", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}/queue-roles"},
	{Name: "BatchGetJobEntity", Method: "POST", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}/batchGetJobEntity"},
	{Name: "CopyJobTemplate", Method: "POST", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/template"},
	{Name: "CreateBudget", Method: "POST", URI: "/2023-10-12/farms/{farmId}/budgets"},
	{Name: "CreateFarm", Method: "POST", URI: "/2023-10-12/farms"},
	{Name: "CreateFleet", Method: "POST", URI: "/2023-10-12/farms/{farmId}/fleets"},
	{Name: "CreateJob", Method: "POST", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs"},
	{Name: "CreateLicenseEndpoint", Method: "POST", URI: "/2023-10-12/license-endpoints"},
	{Name: "CreateLimit", Method: "POST", URI: "/2023-10-12/farms/{farmId}/limits"},
	{Name: "CreateMonitor", Method: "POST", URI: "/2023-10-12/monitors"},
	{Name: "CreateQueue", Method: "POST", URI: "/2023-10-12/farms/{farmId}/queues"},
	{Name: "CreateQueueEnvironment", Method: "POST", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/environments"},
	{Name: "CreateQueueFleetAssociation", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/queue-fleet-associations"},
	{Name: "CreateQueueLimitAssociation", Method: "PUT", URI: "/2023-10-12/farms/{farmId}/queue-limit-associations"},
	{Name: "CreateStorageProfile", Method: "POST", URI: "/2023-10-12/farms/{farmId}/storage-profiles"},
	{Name: "CreateWorker", Method: "POST", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers"},
	{Name: "DeleteBudget", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/budgets/{budgetId}"},
	{Name: "DeleteFarm", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}"},
	{Name: "DeleteFleet", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}"},
	{Name: "DeleteLicenseEndpoint", Method: "DELETE", URI: "/2023-10-12/license-endpoints/{licenseEndpointId}"},
	{Name: "DeleteLimit", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/limits/{limitId}"},
	{Name: "DeleteMeteredProduct", Method: "DELETE", URI: "/2023-10-12/license-endpoints/{licenseEndpointId}/metered-products/{productId}"},
	{Name: "DeleteMonitor", Method: "DELETE", URI: "/2023-10-12/monitors/{monitorId}"},
	{Name: "DeleteQueue", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}"},
	{Name: "DeleteQueueEnvironment", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/environments/{queueEnvironmentId}"},
	{Name: "DeleteQueueFleetAssociation", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}"},
	{Name: "DeleteQueueLimitAssociation", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}"},
	{Name: "DeleteStorageProfile", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/storage-profiles/{storageProfileId}"},
	{Name: "DeleteWorker", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}"},
	{Name: "DisassociateMemberFromFarm", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/members/{principalId}"},
	{Name: "DisassociateMemberFromFleet", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/members/{principalId}"},
	{Name: "DisassociateMemberFromJob", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/members/{principalId}"},
	{Name: "DisassociateMemberFromQueue", Method: "DELETE", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/members/{principalId}"},
	{Name: "GetBudget", Method: "GET", URI: "/2023-10-12/farms/{farmId}/budgets/{budgetId}"},
	{Name: "GetFarm", Method: "GET", URI: "/2023-10-12/farms/{farmId}"},
	{Name: "GetFleet", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}"},
	{Name: "GetJob", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}"},
	{Name: "GetLicenseEndpoint", Method: "GET", URI: "/2023-10-12/license-endpoints/{licenseEndpointId}"},
	{Name: "GetLimit", Method: "GET", URI: "/2023-10-12/farms/{farmId}/limits/{limitId}"},
	{Name: "GetMonitor", Method: "GET", URI: "/2023-10-12/monitors/{monitorId}"},
	{Name: "GetQueue", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}"},
	{Name: "GetQueueEnvironment", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/environments/{queueEnvironmentId}"},
	{Name: "GetQueueFleetAssociation", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}"},
	{Name: "GetQueueLimitAssociation", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}"},
	{Name: "GetSession", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/sessions/{sessionId}"},
	{Name: "GetSessionAction", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/session-actions/{sessionActionId}"},
	{Name: "GetSessionsStatisticsAggregation", Method: "GET", URI: "/2023-10-12/farms/{farmId}/sessions-statistics-aggregation"},
	{Name: "GetStep", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}"},
	{Name: "GetStorageProfile", Method: "GET", URI: "/2023-10-12/farms/{farmId}/storage-profiles/{storageProfileId}"},
	{Name: "GetStorageProfileForQueue", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/storage-profiles/{storageProfileId}"},
	{Name: "GetTask", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}/tasks/{taskId}"},
	{Name: "GetWorker", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}"},
	{Name: "ListAvailableMeteredProducts", Method: "GET", URI: "/2023-10-12/metered-products"},
	{Name: "ListBudgets", Method: "GET", URI: "/2023-10-12/farms/{farmId}/budgets"},
	{Name: "ListFarmMembers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/members"},
	{Name: "ListFarms", Method: "GET", URI: "/2023-10-12/farms"},
	{Name: "ListFleetMembers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/members"},
	{Name: "ListFleets", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets"},
	{Name: "ListJobMembers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/members"},
	{Name: "ListJobParameterDefinitions", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/parameter-definitions"},
	{Name: "ListJobs", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs"},
	{Name: "ListLicenseEndpoints", Method: "GET", URI: "/2023-10-12/license-endpoints"},
	{Name: "ListLimits", Method: "GET", URI: "/2023-10-12/farms/{farmId}/limits"},
	{Name: "ListMeteredProducts", Method: "GET", URI: "/2023-10-12/license-endpoints/{licenseEndpointId}/metered-products"},
	{Name: "ListMonitors", Method: "GET", URI: "/2023-10-12/monitors"},
	{Name: "ListQueueEnvironments", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/environments"},
	{Name: "ListQueueFleetAssociations", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queue-fleet-associations"},
	{Name: "ListQueueLimitAssociations", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queue-limit-associations"},
	{Name: "ListQueueMembers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/members"},
	{Name: "ListQueues", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues"},
	{Name: "ListSessionActions", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/session-actions"},
	{Name: "ListSessions", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/sessions"},
	{Name: "ListSessionsForWorker", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}/sessions"},
	{Name: "ListStepConsumers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}/consumers"},
	{Name: "ListStepDependencies", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}/dependencies"},
	{Name: "ListSteps", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps"},
	{Name: "ListStorageProfiles", Method: "GET", URI: "/2023-10-12/farms/{farmId}/storage-profiles"},
	{Name: "ListStorageProfilesForQueue", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/storage-profiles"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/2023-10-12/tags/{resourceArn}"},
	{Name: "ListTasks", Method: "GET", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}/tasks"},
	{Name: "ListWorkers", Method: "GET", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers"},
	{Name: "PutMeteredProduct", Method: "PUT", URI: "/2023-10-12/license-endpoints/{licenseEndpointId}/metered-products/{productId}"},
	{Name: "SearchJobs", Method: "POST", URI: "/2023-10-12/farms/{farmId}/search/jobs"},
	{Name: "SearchSteps", Method: "POST", URI: "/2023-10-12/farms/{farmId}/search/steps"},
	{Name: "SearchTasks", Method: "POST", URI: "/2023-10-12/farms/{farmId}/search/tasks"},
	{Name: "SearchWorkers", Method: "POST", URI: "/2023-10-12/farms/{farmId}/search/workers"},
	{Name: "StartSessionsStatisticsAggregation", Method: "POST", URI: "/2023-10-12/farms/{farmId}/sessions-statistics-aggregation"},
	{Name: "TagResource", Method: "POST", URI: "/2023-10-12/tags/{resourceArn}"},
	{Name: "UntagResource", Method: "DELETE", URI: "/2023-10-12/tags/{resourceArn}"},
	{Name: "UpdateBudget", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/budgets/{budgetId}"},
	{Name: "UpdateFarm", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}"},
	{Name: "UpdateFleet", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}"},
	{Name: "UpdateJob", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}"},
	{Name: "UpdateLimit", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/limits/{limitId}"},
	{Name: "UpdateMonitor", Method: "PATCH", URI: "/2023-10-12/monitors/{monitorId}"},
	{Name: "UpdateQueue", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}"},
	{Name: "UpdateQueueEnvironment", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/environments/{queueEnvironmentId}"},
	{Name: "UpdateQueueFleetAssociation", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queue-fleet-associations/{queueId}/{fleetId}"},
	{Name: "UpdateQueueLimitAssociation", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queue-limit-associations/{queueId}/{limitId}"},
	{Name: "UpdateSession", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/sessions/{sessionId}"},
	{Name: "UpdateStep", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}"},
	{Name: "UpdateStorageProfile", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/storage-profiles/{storageProfileId}"},
	{Name: "UpdateTask", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/queues/{queueId}/jobs/{jobId}/steps/{stepId}/tasks/{taskId}"},
	{Name: "UpdateWorker", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}"},
	{Name: "UpdateWorkerSchedule", Method: "PATCH", URI: "/2023-10-12/farms/{farmId}/fleets/{fleetId}/workers/{workerId}/schedule"},
}

var deadlineOperationByName = func() map[string]deadlineOperation {
	out := make(map[string]deadlineOperation, len(deadlineOperations))
	for _, op := range deadlineOperations {
		out[op.Name] = op
	}
	return out
}()
