package server

type devOpsGuruDataType struct {
	Name string
}

// Amazon DevOps Guru data types sourced from:
// https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_Types.html
var devOpsGuruDataTypes = []devOpsGuruDataType{
	{Name: "AccountHealth"},
	{Name: "AccountInsightHealth"},
	{Name: "AmazonCodeGuruProfilerIntegration"},
	{Name: "AnomalousLogGroup"},
	{Name: "AnomalyReportedTimeRange"},
	{Name: "AnomalyResource"},
	{Name: "AnomalySourceDetails"},
	{Name: "AnomalySourceMetadata"},
	{Name: "AnomalyTimeRange"},
	{Name: "CloudFormationCollection"},
	{Name: "CloudFormationCollectionFilter"},
	{Name: "CloudFormationCostEstimationResourceCollectionFilter"},
	{Name: "CloudFormationHealth"},
	{Name: "CloudWatchMetricsDataSummary"},
	{Name: "CloudWatchMetricsDetail"},
	{Name: "CloudWatchMetricsDimension"},
	{Name: "CostEstimationResourceCollectionFilter"},
	{Name: "CostEstimationTimeRange"},
	{Name: "EndTimeRange"},
	{Name: "Event"},
	{Name: "EventResource"},
	{Name: "EventSourcesConfig"},
	{Name: "EventTimeRange"},
	{Name: "InsightFeedback"},
	{Name: "InsightHealth"},
	{Name: "InsightTimeRange"},
	{Name: "KMSServerSideEncryptionIntegration"},
	{Name: "KMSServerSideEncryptionIntegrationConfig"},
	{Name: "ListAnomaliesForInsightFilters"},
	{Name: "ListEventsFilters"},
	{Name: "ListInsightsAnyStatusFilter"},
	{Name: "ListInsightsClosedStatusFilter"},
	{Name: "ListInsightsOngoingStatusFilter"},
	{Name: "ListInsightsStatusFilter"},
	{Name: "ListMonitoredResourcesFilters"},
	{Name: "LogAnomalyClass"},
	{Name: "LogAnomalyShowcase"},
	{Name: "LogsAnomalyDetectionIntegration"},
	{Name: "LogsAnomalyDetectionIntegrationConfig"},
	{Name: "MonitoredResourceIdentifier"},
	{Name: "NotificationChannel"},
	{Name: "NotificationChannelConfig"},
	{Name: "NotificationFilterConfig"},
	{Name: "OpsCenterIntegration"},
	{Name: "OpsCenterIntegrationConfig"},
	{Name: "PerformanceInsightsMetricDimensionGroup"},
	{Name: "PerformanceInsightsMetricQuery"},
	{Name: "PerformanceInsightsMetricsDetail"},
	{Name: "PerformanceInsightsReferenceComparisonValues"},
	{Name: "PerformanceInsightsReferenceData"},
	{Name: "PerformanceInsightsReferenceMetric"},
	{Name: "PerformanceInsightsReferenceScalar"},
	{Name: "PerformanceInsightsStat"},
	{Name: "PredictionTimeRange"},
	{Name: "ProactiveAnomaly"},
	{Name: "ProactiveAnomalySummary"},
	{Name: "ProactiveInsight"},
	{Name: "ProactiveInsightSummary"},
	{Name: "ProactiveOrganizationInsightSummary"},
	{Name: "ReactiveAnomaly"},
	{Name: "ReactiveAnomalySummary"},
	{Name: "ReactiveInsight"},
	{Name: "ReactiveInsightSummary"},
	{Name: "ReactiveOrganizationInsightSummary"},
	{Name: "Recommendation"},
	{Name: "RecommendationRelatedAnomaly"},
	{Name: "RecommendationRelatedAnomalyResource"},
	{Name: "RecommendationRelatedAnomalySourceDetail"},
	{Name: "RecommendationRelatedCloudWatchMetricsSourceDetail"},
	{Name: "RecommendationRelatedEvent"},
	{Name: "RecommendationRelatedEventResource"},
	{Name: "ResourceCollection"},
	{Name: "ResourceCollectionFilter"},
	{Name: "SearchInsightsFilters"},
	{Name: "SearchOrganizationInsightsFilters"},
	{Name: "ServiceCollection"},
	{Name: "ServiceHealth"},
	{Name: "ServiceInsightHealth"},
	{Name: "ServiceIntegrationConfig"},
	{Name: "ServiceResourceCost"},
	{Name: "SnsChannelConfig"},
	{Name: "StartTimeRange"},
	{Name: "TagCollection"},
	{Name: "TagCollectionFilter"},
	{Name: "TagCostEstimationResourceCollectionFilter"},
	{Name: "TagHealth"},
	{Name: "TimestampMetricValuePair"},
	{Name: "UpdateCloudFormationCollectionFilter"},
	{Name: "UpdateResourceCollectionFilter"},
	{Name: "UpdateServiceIntegration"},
	{Name: "UpdateServiceIntegrationConfig"},
	{Name: "UpdateTagCollectionFilter"},
	{Name: "ValidationExceptionField"},
}

var devOpsGuruDataTypeByName = func() map[string]devOpsGuruDataType {
	out := make(map[string]devOpsGuruDataType, len(devOpsGuruDataTypes))
	for _, dt := range devOpsGuruDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
