package server

type dmsDataType struct {
	Name string
}

// AWS Database Migration Service (DMS) data types sourced from:
// https://docs.aws.amazon.com/dms/latest/APIReference/API_Types.html
var dmsDataTypes = []dmsDataType{
	{Name: "AccountQuota"},
	{Name: "AvailabilityZone"},
	{Name: "BatchStartRecommendationsErrorEntry"},
	{Name: "Certificate"},
	{Name: "CollectorHealthCheck"},
	{Name: "CollectorResponse"},
	{Name: "CollectorShortInfoResponse"},
	{Name: "ComputeConfig"},
	{Name: "Connection"},
	{Name: "DataMigration"},
	{Name: "DataMigrationSettings"},
	{Name: "DataMigrationStatistics"},
	{Name: "DataProvider"},
	{Name: "DataProviderDescriptor"},
	{Name: "DataProviderDescriptorDefinition"},
	{Name: "DataProviderSettings"},
	{Name: "DatabaseInstanceSoftwareDetailsResponse"},
	{Name: "DatabaseResponse"},
	{Name: "DatabaseShortInfoResponse"},
	{Name: "DefaultErrorDetails"},
	{Name: "DmsTransferSettings"},
	{Name: "DocDbDataProviderSettings"},
	{Name: "DocDbSettings"},
	{Name: "DynamoDbSettings"},
	{Name: "ElasticsearchSettings"},
	{Name: "Endpoint"},
	{Name: "EndpointSetting"},
	{Name: "EngineVersion"},
	{Name: "ErrorDetails"},
	{Name: "Event"},
	{Name: "EventCategoryGroup"},
	{Name: "EventSubscription"},
	{Name: "ExportMetadataModelAssessmentResultEntry"},
	{Name: "ExportSqlDetails"},
	{Name: "Filter"},
	{Name: "FleetAdvisorLsaAnalysisResponse"},
	{Name: "FleetAdvisorSchemaObjectResponse"},
	{Name: "GcpMySQLSettings"},
	{Name: "IBMDb2Settings"},
	{Name: "IbmDb2LuwDataProviderSettings"},
	{Name: "IbmDb2zOsDataProviderSettings"},
	{Name: "InstanceProfile"},
	{Name: "InventoryData"},
	{Name: "KafkaSettings"},
	{Name: "KerberosAuthenticationSettings"},
	{Name: "KinesisSettings"},
	{Name: "LakehouseSettings"},
	{Name: "Limitation"},
	{Name: "MariaDbDataProviderSettings"},
	{Name: "MetadataModelProperties"},
	{Name: "MetadataModelReference"},
	{Name: "MicrosoftSQLServerSettings"},
	{Name: "MicrosoftSqlServerDataProviderSettings"},
	{Name: "MigrationProject"},
	{Name: "MongoDbDataProviderSettings"},
	{Name: "MongoDbSettings"},
	{Name: "MySQLSettings"},
	{Name: "MySqlDataProviderSettings"},
	{Name: "NeptuneSettings"},
	{Name: "OracleDataProviderSettings"},
	{Name: "OracleSettings"},
	{Name: "OrderableReplicationInstance"},
	{Name: "PendingMaintenanceAction"},
	{Name: "PostgreSQLSettings"},
	{Name: "PostgreSqlDataProviderSettings"},
	{Name: "PremigrationAssessmentStatus"},
	{Name: "ProcessedObject"},
	{Name: "Progress"},
	{Name: "ProvisionData"},
	{Name: "RdsConfiguration"},
	{Name: "RdsRecommendation"},
	{Name: "RdsRequirements"},
	{Name: "Recommendation"},
	{Name: "RecommendationData"},
	{Name: "RecommendationSettings"},
	{Name: "RedisSettings"},
	{Name: "RedshiftDataProviderSettings"},
	{Name: "RedshiftSettings"},
	{Name: "RefreshSchemasStatus"},
	{Name: "Replication"},
	{Name: "ReplicationConfig"},
	{Name: "ReplicationInstance"},
	{Name: "ReplicationInstanceTaskLog"},
	{Name: "ReplicationPendingModifiedValues"},
	{Name: "ReplicationStats"},
	{Name: "ReplicationSubnetGroup"},
	{Name: "ReplicationTask"},
	{Name: "ReplicationTaskAssessmentResult"},
	{Name: "ReplicationTaskAssessmentRun"},
	{Name: "ReplicationTaskAssessmentRunProgress"},
	{Name: "ReplicationTaskAssessmentRunResultStatistic"},
	{Name: "ReplicationTaskIndividualAssessment"},
	{Name: "ReplicationTaskStats"},
	{Name: "ResourcePendingMaintenanceActions"},
	{Name: "S3Settings"},
	{Name: "SCApplicationAttributes"},
	{Name: "SchemaConversionRequest"},
	{Name: "SchemaResponse"},
	{Name: "SchemaShortInfoResponse"},
	{Name: "ServerShortInfoResponse"},
	{Name: "SourceDataSetting"},
	{Name: "StartRecommendationsRequestEntry"},
	{Name: "StatementProperties"},
	{Name: "Subnet"},
	{Name: "SupportedEndpointType"},
	{Name: "SybaseAseDataProviderSettings"},
	{Name: "SybaseSettings"},
	{Name: "TableStatistics"},
	{Name: "TableToReload"},
	{Name: "Tag"},
	{Name: "TargetDataSetting"},
	{Name: "TimestreamSettings"},
	{Name: "UpdateSubscriptionsToEventBridge"},
	{Name: "VpcSecurityGroupMembership"},
}

var dmsDataTypeByName = func() map[string]dmsDataType {
	out := make(map[string]dmsDataType, len(dmsDataTypes))
	for _, dt := range dmsDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
