package server

type dmsOperation struct {
	Name string
}

// AWS Database Migration Service (DMS) operations sourced from:
// https://docs.aws.amazon.com/dms/latest/APIReference/API_Operations.html
var dmsOperations = []dmsOperation{
	{Name: "AddTagsToResource"},
	{Name: "ApplyPendingMaintenanceAction"},
	{Name: "BatchStartRecommendations"},
	{Name: "CancelMetadataModelConversion"},
	{Name: "CancelMetadataModelCreation"},
	{Name: "CancelReplicationTaskAssessmentRun"},
	{Name: "CreateDataMigration"},
	{Name: "CreateDataProvider"},
	{Name: "CreateEndpoint"},
	{Name: "CreateEventSubscription"},
	{Name: "CreateFleetAdvisorCollector"},
	{Name: "CreateInstanceProfile"},
	{Name: "CreateMigrationProject"},
	{Name: "CreateReplicationConfig"},
	{Name: "CreateReplicationInstance"},
	{Name: "CreateReplicationSubnetGroup"},
	{Name: "CreateReplicationTask"},
	{Name: "DeleteCertificate"},
	{Name: "DeleteConnection"},
	{Name: "DeleteDataMigration"},
	{Name: "DeleteDataProvider"},
	{Name: "DeleteEndpoint"},
	{Name: "DeleteEventSubscription"},
	{Name: "DeleteFleetAdvisorCollector"},
	{Name: "DeleteFleetAdvisorDatabases"},
	{Name: "DeleteInstanceProfile"},
	{Name: "DeleteMigrationProject"},
	{Name: "DeleteReplicationConfig"},
	{Name: "DeleteReplicationInstance"},
	{Name: "DeleteReplicationSubnetGroup"},
	{Name: "DeleteReplicationTask"},
	{Name: "DeleteReplicationTaskAssessmentRun"},
	{Name: "DescribeAccountAttributes"},
	{Name: "DescribeApplicableIndividualAssessments"},
	{Name: "DescribeCertificates"},
	{Name: "DescribeConnections"},
	{Name: "DescribeConversionConfiguration"},
	{Name: "DescribeDataMigrations"},
	{Name: "DescribeDataProviders"},
	{Name: "DescribeEndpointSettings"},
	{Name: "DescribeEndpointTypes"},
	{Name: "DescribeEndpoints"},
	{Name: "DescribeEngineVersions"},
	{Name: "DescribeEventCategories"},
	{Name: "DescribeEventSubscriptions"},
	{Name: "DescribeEvents"},
	{Name: "DescribeExtensionPackAssociations"},
	{Name: "DescribeFleetAdvisorCollectors"},
	{Name: "DescribeFleetAdvisorDatabases"},
	{Name: "DescribeFleetAdvisorLsaAnalysis"},
	{Name: "DescribeFleetAdvisorSchemaObjectSummary"},
	{Name: "DescribeFleetAdvisorSchemas"},
	{Name: "DescribeInstanceProfiles"},
	{Name: "DescribeMetadataModel"},
	{Name: "DescribeMetadataModelAssessments"},
	{Name: "DescribeMetadataModelChildren"},
	{Name: "DescribeMetadataModelConversions"},
	{Name: "DescribeMetadataModelCreations"},
	{Name: "DescribeMetadataModelExportsAsScript"},
	{Name: "DescribeMetadataModelExportsToTarget"},
	{Name: "DescribeMetadataModelImports"},
	{Name: "DescribeMigrationProjects"},
	{Name: "DescribeOrderableReplicationInstances"},
	{Name: "DescribePendingMaintenanceActions"},
	{Name: "DescribeRecommendationLimitations"},
	{Name: "DescribeRecommendations"},
	{Name: "DescribeRefreshSchemasStatus"},
	{Name: "DescribeReplicationConfigs"},
	{Name: "DescribeReplicationInstanceTaskLogs"},
	{Name: "DescribeReplicationInstances"},
	{Name: "DescribeReplicationSubnetGroups"},
	{Name: "DescribeReplicationTableStatistics"},
	{Name: "DescribeReplicationTaskAssessmentResults"},
	{Name: "DescribeReplicationTaskAssessmentRuns"},
	{Name: "DescribeReplicationTaskIndividualAssessments"},
	{Name: "DescribeReplicationTasks"},
	{Name: "DescribeReplications"},
	{Name: "DescribeSchemas"},
	{Name: "DescribeTableStatistics"},
	{Name: "ExportMetadataModelAssessment"},
	{Name: "GetTargetSelectionRules"},
	{Name: "ImportCertificate"},
	{Name: "ListTagsForResource"},
	{Name: "ModifyConversionConfiguration"},
	{Name: "ModifyDataMigration"},
	{Name: "ModifyDataProvider"},
	{Name: "ModifyEndpoint"},
	{Name: "ModifyEventSubscription"},
	{Name: "ModifyInstanceProfile"},
	{Name: "ModifyMigrationProject"},
	{Name: "ModifyReplicationConfig"},
	{Name: "ModifyReplicationInstance"},
	{Name: "ModifyReplicationSubnetGroup"},
	{Name: "ModifyReplicationTask"},
	{Name: "MoveReplicationTask"},
	{Name: "RebootReplicationInstance"},
	{Name: "RefreshSchemas"},
	{Name: "ReloadReplicationTables"},
	{Name: "ReloadTables"},
	{Name: "RemoveTagsFromResource"},
	{Name: "RunFleetAdvisorLsaAnalysis"},
	{Name: "StartDataMigration"},
	{Name: "StartExtensionPackAssociation"},
	{Name: "StartMetadataModelAssessment"},
	{Name: "StartMetadataModelConversion"},
	{Name: "StartMetadataModelCreation"},
	{Name: "StartMetadataModelExportAsScript"},
	{Name: "StartMetadataModelExportToTarget"},
	{Name: "StartMetadataModelImport"},
	{Name: "StartRecommendations"},
	{Name: "StartReplication"},
	{Name: "StartReplicationTask"},
	{Name: "StartReplicationTaskAssessment"},
	{Name: "StartReplicationTaskAssessmentRun"},
	{Name: "StopDataMigration"},
	{Name: "StopReplication"},
	{Name: "StopReplicationTask"},
	{Name: "TestConnection"},
	{Name: "UpdateSubscriptionsToEventBridge"},
}

var dmsOperationByName = func() map[string]dmsOperation {
	out := make(map[string]dmsOperation, len(dmsOperations))
	for _, op := range dmsOperations {
		out[op.Name] = op
	}
	return out
}()
