package server

type ec2AutoScalingDataType struct {
	Name string
}

// Amazon EC2 Auto Scaling data types sourced from:
// https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_Types.html
var ec2AutoScalingDataTypes = []ec2AutoScalingDataType{
	{Name: "AcceleratorCountRequest"},
	{Name: "AcceleratorTotalMemoryMiBRequest"},
	{Name: "Activity"},
	{Name: "AdjustmentType"},
	{Name: "Alarm"},
	{Name: "AlarmSpecification"},
	{Name: "AutoScalingGroup"},
	{Name: "AutoScalingInstanceDetails"},
	{Name: "AvailabilityZoneDistribution"},
	{Name: "AvailabilityZoneImpairmentPolicy"},
	{Name: "BaselineEbsBandwidthMbpsRequest"},
	{Name: "BaselinePerformanceFactorsRequest"},
	{Name: "BlockDeviceMapping"},
	{Name: "CapacityForecast"},
	{Name: "CapacityReservationSpecification"},
	{Name: "CapacityReservationTarget"},
	{Name: "CpuPerformanceFactorRequest"},
	{Name: "CustomizedMetricSpecification"},
	{Name: "DesiredConfiguration"},
	{Name: "Ebs"},
	{Name: "EnabledMetric"},
	{Name: "FailedScheduledUpdateGroupActionRequest"},
	{Name: "Filter"},
	{Name: "Instance"},
	{Name: "InstanceCollection"},
	{Name: "InstanceLifecyclePolicy"},
	{Name: "InstanceMaintenancePolicy"},
	{Name: "InstanceMetadataOptions"},
	{Name: "InstanceMonitoring"},
	{Name: "InstanceRefresh"},
	{Name: "InstanceRefreshLivePoolProgress"},
	{Name: "InstanceRefreshProgressDetails"},
	{Name: "InstanceRefreshWarmPoolProgress"},
	{Name: "InstanceRequirements"},
	{Name: "InstanceReusePolicy"},
	{Name: "InstancesDistribution"},
	{Name: "LaunchConfiguration"},
	{Name: "LaunchInstancesError"},
	{Name: "LaunchTemplate"},
	{Name: "LaunchTemplateOverrides"},
	{Name: "LaunchTemplateSpecification"},
	{Name: "LifecycleHook"},
	{Name: "LifecycleHookSpecification"},
	{Name: "LoadBalancerState"},
	{Name: "LoadBalancerTargetGroupState"},
	{Name: "LoadForecast"},
	{Name: "MemoryGiBPerVCpuRequest"},
	{Name: "MemoryMiBRequest"},
	{Name: "Metric"},
	{Name: "MetricCollectionType"},
	{Name: "MetricDataQuery"},
	{Name: "MetricDimension"},
	{Name: "MetricGranularityType"},
	{Name: "MetricStat"},
	{Name: "MixedInstancesPolicy"},
	{Name: "NetworkBandwidthGbpsRequest"},
	{Name: "NetworkInterfaceCountRequest"},
	{Name: "NotificationConfiguration"},
	{Name: "PerformanceFactorReferenceRequest"},
	{Name: "PredefinedMetricSpecification"},
	{Name: "PredictiveScalingConfiguration"},
	{Name: "PredictiveScalingCustomizedCapacityMetric"},
	{Name: "PredictiveScalingCustomizedLoadMetric"},
	{Name: "PredictiveScalingCustomizedScalingMetric"},
	{Name: "PredictiveScalingMetricSpecification"},
	{Name: "PredictiveScalingPredefinedLoadMetric"},
	{Name: "PredictiveScalingPredefinedMetricPair"},
	{Name: "PredictiveScalingPredefinedScalingMetric"},
	{Name: "ProcessType"},
	{Name: "RefreshPreferences"},
	{Name: "RetentionTriggers"},
	{Name: "RollbackDetails"},
	{Name: "ScalingPolicy"},
	{Name: "ScheduledUpdateGroupAction"},
	{Name: "ScheduledUpdateGroupActionRequest"},
	{Name: "StepAdjustment"},
	{Name: "SuspendedProcess"},
	{Name: "Tag"},
	{Name: "TagDescription"},
	{Name: "TargetTrackingConfiguration"},
	{Name: "TargetTrackingMetricDataQuery"},
	{Name: "TargetTrackingMetricStat"},
	{Name: "TotalLocalStorageGBRequest"},
	{Name: "TrafficSourceIdentifier"},
	{Name: "TrafficSourceState"},
	{Name: "UpdateAutoScalingGroup"},
	{Name: "VCpuCountRequest"},
	{Name: "WarmPoolConfiguration"},
}

var ec2AutoScalingDataTypeByName = func() map[string]ec2AutoScalingDataType {
	out := make(map[string]ec2AutoScalingDataType, len(ec2AutoScalingDataTypes))
	for _, dt := range ec2AutoScalingDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
