package server

type emrDataType struct {
	Name string
}

// Amazon EMR data types sourced from:
// https://docs.aws.amazon.com/emr/latest/APIReference/API_Types.html
var emrDataTypes = []emrDataType{
	{Name: "Application"},
	{Name: "AutoScalingPolicy"},
	{Name: "AutoScalingPolicyDescription"},
	{Name: "AutoScalingPolicyStateChangeReason"},
	{Name: "AutoScalingPolicyStatus"},
	{Name: "AutoTerminationPolicy"},
	{Name: "BlockPublicAccessConfiguration"},
	{Name: "BlockPublicAccessConfigurationMetadata"},
	{Name: "BootstrapActionConfig"},
	{Name: "BootstrapActionDetail"},
	{Name: "CancelStepsInfo"},
	{Name: "CloudWatchAlarmDefinition"},
	{Name: "Cluster"},
	{Name: "ClusterStateChangeReason"},
	{Name: "ClusterStatus"},
	{Name: "ClusterSummary"},
	{Name: "ClusterTimeline"},
	{Name: "Command"},
	{Name: "ComputeLimits"},
	{Name: "Configuration"},
	{Name: "Credentials"},
	{Name: "EbsBlockDevice"},
	{Name: "EbsBlockDeviceConfig"},
	{Name: "EbsConfiguration"},
	{Name: "EbsVolume"},
	{Name: "Ec2InstanceAttributes"},
	{Name: "EMRContainersConfig"},
	{Name: "ErrorDetail"},
	{Name: "ExecutionEngineConfig"},
	{Name: "FailureDetails"},
	{Name: "HadoopJarStepConfig"},
	{Name: "HadoopStepConfig"},
	{Name: "Instance"},
	{Name: "InstanceFleet"},
	{Name: "InstanceFleetConfig"},
	{Name: "InstanceFleetModifyConfig"},
	{Name: "InstanceFleetProvisioningSpecifications"},
	{Name: "InstanceFleetResizingSpecifications"},
	{Name: "InstanceFleetStateChangeReason"},
	{Name: "InstanceFleetStatus"},
	{Name: "InstanceFleetTimeline"},
	{Name: "InstanceGroup"},
	{Name: "InstanceGroupConfig"},
	{Name: "InstanceGroupDetail"},
	{Name: "InstanceGroupModifyConfig"},
	{Name: "InstanceGroupStateChangeReason"},
	{Name: "InstanceGroupStatus"},
	{Name: "InstanceGroupTimeline"},
	{Name: "InstanceResizePolicy"},
	{Name: "InstanceStateChangeReason"},
	{Name: "InstanceStatus"},
	{Name: "InstanceTimeline"},
	{Name: "InstanceTypeConfig"},
	{Name: "InstanceTypeSpecification"},
	{Name: "JobFlowDetail"},
	{Name: "JobFlowExecutionStatusDetail"},
	{Name: "JobFlowInstancesConfig"},
	{Name: "JobFlowInstancesDetail"},
	{Name: "KerberosAttributes"},
	{Name: "KeyValue"},
	{Name: "ManagedScalingPolicy"},
	{Name: "MetricDimension"},
	{Name: "NotebookExecution"},
	{Name: "NotebookExecutionSummary"},
	{Name: "NotebookS3LocationForOutput"},
	{Name: "NotebookS3LocationFromInput"},
	{Name: "OnDemandCapacityReservationOptions"},
	{Name: "OnDemandProvisioningSpecification"},
	{Name: "OnDemandResizingSpecification"},
	{Name: "OSRelease"},
	{Name: "OutputNotebookS3LocationForOutput"},
	{Name: "OutputNotebookS3LocationFromInput"},
	{Name: "PersistentAppUI"},
	{Name: "PlacementGroupConfig"},
	{Name: "PlacementType"},
	{Name: "PortRange"},
	{Name: "ReleaseLabelFilter"},
	{Name: "ScalingAction"},
	{Name: "ScalingConstraints"},
	{Name: "ScalingRule"},
	{Name: "ScalingTrigger"},
	{Name: "ScriptBootstrapActionConfig"},
	{Name: "SecurityConfigurationSummary"},
	{Name: "SessionMappingDetail"},
	{Name: "SessionMappingSummary"},
	{Name: "ShrinkPolicy"},
	{Name: "SimpleScalingPolicyConfiguration"},
	{Name: "SimplifiedApplication"},
	{Name: "SpotProvisioningSpecification"},
	{Name: "SpotResizingSpecification"},
	{Name: "Step"},
	{Name: "StepConfig"},
	{Name: "StepDetail"},
	{Name: "StepExecutionStatusDetail"},
	{Name: "StepStateChangeReason"},
	{Name: "StepStatus"},
	{Name: "StepSummary"},
	{Name: "StepTimeline"},
	{Name: "Studio"},
	{Name: "StudioSummary"},
	{Name: "SupportedInstanceType"},
	{Name: "SupportedProductConfig"},
	{Name: "Tag"},
	{Name: "UsernamePassword"},
	{Name: "VolumeSpecification"},
	{Name: "UpdateStudioSessionMapping"},
}

var emrDataTypeByName = func() map[string]emrDataType {
	out := make(map[string]emrDataType, len(emrDataTypes))
	for _, dt := range emrDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
