package server

type firehoseType struct {
	Name string
}

// Amazon Data Firehose data types sourced from:
// https://docs.aws.amazon.com/firehose/latest/APIReference/API_Types.html
var firehoseTypes = []firehoseType{
	{Name: "AmazonOpenSearchServerlessBufferingHints"},
	{Name: "AmazonOpenSearchServerlessDestinationConfiguration"},
	{Name: "AmazonOpenSearchServerlessDestinationDescription"},
	{Name: "AmazonOpenSearchServerlessDestinationUpdate"},
	{Name: "AmazonOpenSearchServerlessRetryOptions"},
	{Name: "AmazonopensearchserviceBufferingHints"},
	{Name: "AmazonopensearchserviceDestinationConfiguration"},
	{Name: "AmazonopensearchserviceDestinationDescription"},
	{Name: "AmazonopensearchserviceDestinationUpdate"},
	{Name: "AmazonopensearchserviceRetryOptions"},
	{Name: "AuthenticationConfiguration"},
	{Name: "BufferingHints"},
	{Name: "CatalogConfiguration"},
	{Name: "CloudWatchLoggingOptions"},
	{Name: "CopyCommand"},
	{Name: "DatabaseColumnList"},
	{Name: "DatabaseList"},
	{Name: "DatabaseSnapshotInfo"},
	{Name: "DatabaseSourceAuthenticationConfiguration"},
	{Name: "DatabaseSourceConfiguration"},
	{Name: "DatabaseSourceDescription"},
	{Name: "DatabaseSourceVPCConfiguration"},
	{Name: "DatabaseTableList"},
	{Name: "DataFormatConversionConfiguration"},
	{Name: "DeliveryStreamDescription"},
	{Name: "DeliveryStreamEncryptionConfiguration"},
	{Name: "DeliveryStreamEncryptionConfigurationInput"},
	{Name: "Deserializer"},
	{Name: "DestinationDescription"},
	{Name: "DestinationTableConfiguration"},
	{Name: "DirectPutSourceConfiguration"},
	{Name: "DirectPutSourceDescription"},
	{Name: "DocumentIdOptions"},
	{Name: "DynamicPartitioningConfiguration"},
	{Name: "ElasticsearchBufferingHints"},
	{Name: "ElasticsearchDestinationConfiguration"},
	{Name: "ElasticsearchDestinationDescription"},
	{Name: "ElasticsearchDestinationUpdate"},
	{Name: "ElasticsearchRetryOptions"},
	{Name: "EncryptionConfiguration"},
	{Name: "ExtendedS3DestinationConfiguration"},
	{Name: "ExtendedS3DestinationDescription"},
	{Name: "ExtendedS3DestinationUpdate"},
	{Name: "FailureDescription"},
	{Name: "HiveJsonSerDe"},
	{Name: "HttpEndpointBufferingHints"},
	{Name: "HttpEndpointCommonAttribute"},
	{Name: "HttpEndpointConfiguration"},
	{Name: "HttpEndpointDescription"},
	{Name: "HttpEndpointDestinationConfiguration"},
	{Name: "HttpEndpointDestinationDescription"},
	{Name: "HttpEndpointDestinationUpdate"},
	{Name: "HttpEndpointRequestConfiguration"},
	{Name: "HttpEndpointRetryOptions"},
	{Name: "IcebergDestinationConfiguration"},
	{Name: "IcebergDestinationDescription"},
	{Name: "IcebergDestinationUpdate"},
	{Name: "InputFormatConfiguration"},
	{Name: "KinesisStreamSourceConfiguration"},
	{Name: "KinesisStreamSourceDescription"},
	{Name: "KMSEncryptionConfig"},
	{Name: "MSKSourceConfiguration"},
	{Name: "MSKSourceDescription"},
	{Name: "OpenXJsonSerDe"},
	{Name: "OrcSerDe"},
	{Name: "OutputFormatConfiguration"},
	{Name: "ParquetSerDe"},
	{Name: "PartitionField"},
	{Name: "PartitionSpec"},
	{Name: "ProcessingConfiguration"},
	{Name: "Processor"},
	{Name: "ProcessorParameter"},
	{Name: "PutRecordBatchResponseEntry"},
	{Name: "Record"},
	{Name: "RedshiftDestinationConfiguration"},
	{Name: "RedshiftDestinationDescription"},
	{Name: "RedshiftDestinationUpdate"},
	{Name: "RedshiftRetryOptions"},
	{Name: "RetryOptions"},
	{Name: "S3DestinationConfiguration"},
	{Name: "S3DestinationDescription"},
	{Name: "S3DestinationUpdate"},
	{Name: "SchemaConfiguration"},
	{Name: "SchemaEvolutionConfiguration"},
	{Name: "SecretsManagerConfiguration"},
	{Name: "Serializer"},
	{Name: "SnowflakeBufferingHints"},
	{Name: "SnowflakeDestinationConfiguration"},
	{Name: "SnowflakeDestinationDescription"},
	{Name: "SnowflakeDestinationUpdate"},
	{Name: "SnowflakeRetryOptions"},
	{Name: "SnowflakeRoleConfiguration"},
	{Name: "SnowflakeVpcConfiguration"},
	{Name: "SourceDescription"},
	{Name: "SplunkBufferingHints"},
	{Name: "SplunkDestinationConfiguration"},
	{Name: "SplunkDestinationDescription"},
	{Name: "SplunkDestinationUpdate"},
	{Name: "SplunkRetryOptions"},
	{Name: "TableCreationConfiguration"},
	{Name: "Tag"},
	{Name: "VpcConfiguration"},
	{Name: "VpcConfigurationDescription"},
}

var firehoseTypeByName = func() map[string]firehoseType {
	out := make(map[string]firehoseType, len(firehoseTypes))
	for _, dt := range firehoseTypes {
		out[dt.Name] = dt
	}
	return out
}()
