package server

type fmsDataType struct {
	Name string
}

// AWS Firewall Manager data types sourced from:
// https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_Types.html
var fmsDataTypes = []fmsDataType{
	{Name: "AccountScope"},
	{Name: "ActionTarget"},
	{Name: "AdminAccountSummary"},
	{Name: "AdminScope"},
	{Name: "App"},
	{Name: "AppsListData"},
	{Name: "AppsListDataSummary"},
	{Name: "AwsEc2InstanceViolation"},
	{Name: "AwsEc2NetworkInterfaceViolation"},
	{Name: "AwsVPCSecurityGroupViolation"},
	{Name: "ComplianceViolator"},
	{Name: "CreateNetworkAclAction"},
	{Name: "CreateNetworkAclEntriesAction"},
	{Name: "DeleteNetworkAclEntriesAction"},
	{Name: "DiscoveredResource"},
	{Name: "DnsDuplicateRuleGroupViolation"},
	{Name: "DnsRuleGroupLimitExceededViolation"},
	{Name: "DnsRuleGroupPriorityConflictViolation"},
	{Name: "EC2AssociateRouteTableAction"},
	{Name: "EC2CopyRouteTableAction"},
	{Name: "EC2CreateRouteAction"},
	{Name: "EC2CreateRouteTableAction"},
	{Name: "EC2DeleteRouteAction"},
	{Name: "EC2ReplaceRouteAction"},
	{Name: "EC2ReplaceRouteTableAssociationAction"},
	{Name: "EntryDescription"},
	{Name: "EntryViolation"},
	{Name: "EvaluationResult"},
	{Name: "ExpectedRoute"},
	{Name: "FMSPolicyUpdateFirewallCreationConfigAction"},
	{Name: "FailedItem"},
	{Name: "FirewallSubnetIsOutOfScopeViolation"},
	{Name: "FirewallSubnetMissingVPCEndpointViolation"},
	{Name: "InvalidNetworkAclEntriesViolation"},
	{Name: "NetworkAclCommonPolicy"},
	{Name: "NetworkAclEntry"},
	{Name: "NetworkAclEntrySet"},
	{Name: "NetworkAclIcmpTypeCode"},
	{Name: "NetworkAclPortRange"},
	{Name: "NetworkFirewallBlackHoleRouteDetectedViolation"},
	{Name: "NetworkFirewallInternetTrafficNotInspectedViolation"},
	{Name: "NetworkFirewallInvalidRouteConfigurationViolation"},
	{Name: "NetworkFirewallMissingExpectedRTViolation"},
	{Name: "NetworkFirewallMissingExpectedRoutesViolation"},
	{Name: "NetworkFirewallMissingFirewallViolation"},
	{Name: "NetworkFirewallMissingSubnetViolation"},
	{Name: "NetworkFirewallPolicy"},
	{Name: "NetworkFirewallPolicyDescription"},
	{Name: "NetworkFirewallPolicyModifiedViolation"},
	{Name: "NetworkFirewallStatefulRuleGroupOverride"},
	{Name: "NetworkFirewallUnexpectedFirewallRoutesViolation"},
	{Name: "NetworkFirewallUnexpectedGatewayRoutesViolation"},
	{Name: "OrganizationalUnitScope"},
	{Name: "PartialMatch"},
	{Name: "Policy"},
	{Name: "PolicyComplianceDetail"},
	{Name: "PolicyComplianceStatus"},
	{Name: "PolicyOption"},
	{Name: "PolicySummary"},
	{Name: "PolicyTypeScope"},
	{Name: "PossibleRemediationAction"},
	{Name: "PossibleRemediationActions"},
	{Name: "ProtocolsListData"},
	{Name: "ProtocolsListDataSummary"},
	{Name: "RegionScope"},
	{Name: "RemediationAction"},
	{Name: "RemediationActionWithOrder"},
	{Name: "ReplaceNetworkAclAssociationAction"},
	{Name: "Resource"},
	{Name: "ResourceSet"},
	{Name: "ResourceSetSummary"},
	{Name: "ResourceTag"},
	{Name: "ResourceViolation"},
	{Name: "Route"},
	{Name: "RouteHasOutOfScopeEndpointViolation"},
	{Name: "SecurityGroupRemediationAction"},
	{Name: "SecurityGroupRuleDescription"},
	{Name: "SecurityServicePolicyData"},
	{Name: "StatefulEngineOptions"},
	{Name: "StatefulRuleGroup"},
	{Name: "StatelessRuleGroup"},
	{Name: "Tag"},
	{Name: "ThirdPartyFirewallFirewallPolicy"},
	{Name: "ThirdPartyFirewallMissingExpectedRouteTableViolation"},
	{Name: "ThirdPartyFirewallMissingFirewallViolation"},
	{Name: "ThirdPartyFirewallMissingSubnetViolation"},
	{Name: "ThirdPartyFirewallPolicy"},
	{Name: "ViolationDetail"},
	{Name: "WebACLHasIncompatibleConfigurationViolation"},
	{Name: "WebACLHasOutOfScopeResourcesViolation"},
}

var fmsDataTypeByName = func() map[string]fmsDataType {
	out := make(map[string]fmsDataType, len(fmsDataTypes))
	for _, dt := range fmsDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
