package server

type fsxDataType struct {
	Name string
}

// Amazon FSx data types sourced from:
// https://docs.aws.amazon.com/fsx/latest/APIReference/API_Types.html
var fsxDataTypes = []fsxDataType{
	{Name: "ActiveDirectoryBackupAttributes"},
	{Name: "AdministrativeAction"},
	{Name: "AdministrativeActionFailureDetails"},
	{Name: "AggregateConfiguration"},
	{Name: "Alias"},
	{Name: "AutoExportPolicy"},
	{Name: "AutoImportPolicy"},
	{Name: "AutocommitPeriod"},
	{Name: "Backup"},
	{Name: "BackupFailureDetails"},
	{Name: "CompletionReport"},
	{Name: "CreateAggregateConfiguration"},
	{Name: "CreateAndAttachS3AccessPointOntapConfiguration"},
	{Name: "CreateAndAttachS3AccessPointOpenZFSConfiguration"},
	{Name: "CreateAndAttachS3AccessPointS3Configuration"},
	{Name: "CreateFileCacheLustreConfiguration"},
	{Name: "CreateFileSystemLustreConfiguration"},
	{Name: "CreateFileSystemLustreMetadataConfiguration"},
	{Name: "CreateFileSystemOntapConfiguration"},
	{Name: "CreateFileSystemOpenZFSConfiguration"},
	{Name: "CreateFileSystemWindowsConfiguration"},
	{Name: "CreateOntapVolumeConfiguration"},
	{Name: "CreateOpenZFSOriginSnapshotConfiguration"},
	{Name: "CreateOpenZFSVolumeConfiguration"},
	{Name: "CreateSnaplockConfiguration"},
	{Name: "CreateSvmActiveDirectoryConfiguration"},
	{Name: "DataRepositoryAssociation"},
	{Name: "DataRepositoryConfiguration"},
	{Name: "DataRepositoryFailureDetails"},
	{Name: "DataRepositoryTask"},
	{Name: "DataRepositoryTaskFailureDetails"},
	{Name: "DataRepositoryTaskFilter"},
	{Name: "DataRepositoryTaskStatus"},
	{Name: "DeleteFileSystemLustreConfiguration"},
	{Name: "DeleteFileSystemLustreResponse"},
	{Name: "DeleteFileSystemOpenZFSConfiguration"},
	{Name: "DeleteFileSystemOpenZFSResponse"},
	{Name: "DeleteFileSystemWindowsConfiguration"},
	{Name: "DeleteFileSystemWindowsResponse"},
	{Name: "DeleteVolumeOntapConfiguration"},
	{Name: "DeleteVolumeOntapResponse"},
	{Name: "DeleteVolumeOpenZFSConfiguration"},
	{Name: "DiskIopsConfiguration"},
	{Name: "DurationSinceLastAccess"},
	{Name: "FileCache"},
	{Name: "FileCacheCreating"},
	{Name: "FileCacheDataRepositoryAssociation"},
	{Name: "FileCacheFailureDetails"},
	{Name: "FileCacheLustreConfiguration"},
	{Name: "FileCacheLustreMetadataConfiguration"},
	{Name: "FileCacheNFSConfiguration"},
	{Name: "FileSystem"},
	{Name: "FileSystemEndpoint"},
	{Name: "FileSystemEndpoints"},
	{Name: "FileSystemFailureDetails"},
	{Name: "FileSystemLustreMetadataConfiguration"},
	{Name: "Filter"},
	{Name: "LifecycleTransitionReason"},
	{Name: "LustreFileSystemConfiguration"},
	{Name: "LustreLogConfiguration"},
	{Name: "LustreLogCreateConfiguration"},
	{Name: "LustreReadCacheConfiguration"},
	{Name: "LustreRootSquashConfiguration"},
	{Name: "NFSDataRepositoryConfiguration"},
	{Name: "OntapFileSystemConfiguration"},
	{Name: "OntapFileSystemIdentity"},
	{Name: "OntapUnixFileSystemUser"},
	{Name: "OntapVolumeConfiguration"},
	{Name: "OntapWindowsFileSystemUser"},
	{Name: "OpenZFSClientConfiguration"},
	{Name: "OpenZFSCreateRootVolumeConfiguration"},
	{Name: "OpenZFSFileSystemConfiguration"},
	{Name: "OpenZFSFileSystemIdentity"},
	{Name: "OpenZFSNfsExport"},
	{Name: "OpenZFSOriginSnapshotConfiguration"},
	{Name: "OpenZFSPosixFileSystemUser"},
	{Name: "OpenZFSReadCacheConfiguration"},
	{Name: "OpenZFSUserOrGroupQuota"},
	{Name: "OpenZFSVolumeConfiguration"},
	{Name: "ReleaseConfiguration"},
	{Name: "RetentionPeriod"},
	{Name: "S3AccessPoint"},
	{Name: "S3AccessPointAttachment"},
	{Name: "S3AccessPointAttachmentsFilter"},
	{Name: "S3AccessPointOntapConfiguration"},
	{Name: "S3AccessPointOpenZFSConfiguration"},
	{Name: "S3AccessPointVpcConfiguration"},
	{Name: "S3DataRepositoryConfiguration"},
	{Name: "SelfManagedActiveDirectoryAttributes"},
	{Name: "SelfManagedActiveDirectoryConfiguration"},
	{Name: "SelfManagedActiveDirectoryConfigurationUpdates"},
	{Name: "SnaplockConfiguration"},
	{Name: "SnaplockRetentionPeriod"},
	{Name: "Snapshot"},
	{Name: "SnapshotFilter"},
	{Name: "StorageVirtualMachine"},
	{Name: "StorageVirtualMachineFilter"},
	{Name: "SvmActiveDirectoryConfiguration"},
	{Name: "SvmEndpoint"},
	{Name: "SvmEndpoints"},
	{Name: "Tag"},
	{Name: "TieringPolicy"},
	{Name: "UpdateFileCacheLustreConfiguration"},
	{Name: "UpdateFileSystemLustreConfiguration"},
	{Name: "UpdateFileSystemLustreMetadataConfiguration"},
	{Name: "UpdateFileSystemOntapConfiguration"},
	{Name: "UpdateFileSystemOpenZFSConfiguration"},
	{Name: "UpdateFileSystemWindowsConfiguration"},
	{Name: "UpdateOntapVolumeConfiguration"},
	{Name: "UpdateOpenZFSVolumeConfiguration"},
	{Name: "UpdateSnaplockConfiguration"},
	{Name: "UpdateSvmActiveDirectoryConfiguration"},
	{Name: "UpdateVolume"},
	{Name: "Volume"},
	{Name: "VolumeFilter"},
	{Name: "WindowsAuditLogConfiguration"},
	{Name: "WindowsAuditLogCreateConfiguration"},
	{Name: "WindowsFileSystemConfiguration"},
	{Name: "WindowsFsrmConfiguration"},
}

var fsxDataTypeByName = func() map[string]fsxDataType {
	out := make(map[string]fsxDataType, len(fsxDataTypes))
	for _, dt := range fsxDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
