package server

type imageBuilderDataType struct {
	Name string
}

// AWS EC2 Image Builder data types sourced from:
// https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_Types.html
var imageBuilderDataTypes = []imageBuilderDataType{
	{Name: "AccountAggregation"},
	{Name: "AdditionalInstanceConfiguration"},
	{Name: "Ami"},
	{Name: "AmiDistributionConfiguration"},
	{Name: "AutoDisablePolicy"},
	{Name: "Component"},
	{Name: "ComponentConfiguration"},
	{Name: "ComponentParameter"},
	{Name: "ComponentParameterDetail"},
	{Name: "ComponentState"},
	{Name: "ComponentSummary"},
	{Name: "ComponentVersion"},
	{Name: "Container"},
	{Name: "ContainerDistributionConfiguration"},
	{Name: "ContainerRecipe"},
	{Name: "ContainerRecipeSummary"},
	{Name: "CvssScore"},
	{Name: "CvssScoreAdjustment"},
	{Name: "CvssScoreDetails"},
	{Name: "Distribution"},
	{Name: "DistributionConfiguration"},
	{Name: "DistributionConfigurationSummary"},
	{Name: "EbsInstanceBlockDeviceSpecification"},
	{Name: "EcrConfiguration"},
	{Name: "FastLaunchConfiguration"},
	{Name: "FastLaunchLaunchTemplateSpecification"},
	{Name: "FastLaunchSnapshotConfiguration"},
	{Name: "Filter"},
	{Name: "Image"},
	{Name: "ImageAggregation"},
	{Name: "ImageLoggingConfiguration"},
	{Name: "ImagePackage"},
	{Name: "ImagePipeline"},
	{Name: "ImagePipelineAggregation"},
	{Name: "ImageRecipe"},
	{Name: "ImageRecipeSummary"},
	{Name: "ImageScanFinding"},
	{Name: "ImageScanFindingAggregation"},
	{Name: "ImageScanFindingsFilter"},
	{Name: "ImageScanState"},
	{Name: "ImageScanningConfiguration"},
	{Name: "ImageState"},
	{Name: "ImageSummary"},
	{Name: "ImageTestsConfiguration"},
	{Name: "ImageVersion"},
	{Name: "InfrastructureConfiguration"},
	{Name: "InfrastructureConfigurationSummary"},
	{Name: "InspectorScoreDetails"},
	{Name: "InstanceBlockDeviceMapping"},
	{Name: "InstanceConfiguration"},
	{Name: "InstanceMetadataOptions"},
	{Name: "LatestVersionReferences"},
	{Name: "LaunchPermissionConfiguration"},
	{Name: "LaunchTemplateConfiguration"},
	{Name: "LifecycleExecution"},
	{Name: "LifecycleExecutionResource"},
	{Name: "LifecycleExecutionResourceAction"},
	{Name: "LifecycleExecutionResourceState"},
	{Name: "LifecycleExecutionResourcesImpactedSummary"},
	{Name: "LifecycleExecutionSnapshotResource"},
	{Name: "LifecycleExecutionState"},
	{Name: "LifecyclePolicy"},
	{Name: "LifecyclePolicyDetail"},
	{Name: "LifecyclePolicyDetailAction"},
	{Name: "LifecyclePolicyDetailActionIncludeResources"},
	{Name: "LifecyclePolicyDetailExclusionRules"},
	{Name: "LifecyclePolicyDetailExclusionRulesAmis"},
	{Name: "LifecyclePolicyDetailExclusionRulesAmisLastLaunched"},
	{Name: "LifecyclePolicyDetailFilter"},
	{Name: "LifecyclePolicyResourceSelection"},
	{Name: "LifecyclePolicyResourceSelectionRecipe"},
	{Name: "LifecyclePolicySummary"},
	{Name: "Logging"},
	{Name: "OutputResources"},
	{Name: "PackageVulnerabilityDetails"},
	{Name: "PipelineLoggingConfiguration"},
	{Name: "Placement"},
	{Name: "ProductCodeListItem"},
	{Name: "Remediation"},
	{Name: "RemediationRecommendation"},
	{Name: "ResourceState"},
	{Name: "ResourceStateUpdateExclusionRules"},
	{Name: "ResourceStateUpdateIncludeResources"},
	{Name: "S3ExportConfiguration"},
	{Name: "S3Logs"},
	{Name: "Schedule"},
	{Name: "SeverityCounts"},
	{Name: "SsmParameterConfiguration"},
	{Name: "SystemsManagerAgent"},
	{Name: "TargetContainerRepository"},
	{Name: "UpdateLifecyclePolicy"},
	{Name: "VulnerabilityIdAggregation"},
	{Name: "VulnerablePackage"},
	{Name: "Workflow"},
	{Name: "WorkflowConfiguration"},
	{Name: "WorkflowExecutionMetadata"},
	{Name: "WorkflowParameter"},
	{Name: "WorkflowParameterDetail"},
	{Name: "WorkflowState"},
	{Name: "WorkflowStepExecution"},
	{Name: "WorkflowStepMetadata"},
	{Name: "WorkflowSummary"},
	{Name: "WorkflowVersion"},
}

var imageBuilderDataTypeByName = func() map[string]imageBuilderDataType {
	out := make(map[string]imageBuilderDataType, len(imageBuilderDataTypes))
	for _, dt := range imageBuilderDataTypes {
		out[dt.Name] = dt
	}
	return out
}()
