package server

type iotSiteWiseOperation struct {
	Name   string
	Method string
	URI    string
}

// AWS IoT SiteWise operations sourced from:
// https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_Operations.html
var iotSiteWiseOperations = []iotSiteWiseOperation{
	{Name: "AssociateAssets", Method: "POST", URI: "/assets/{assetId}/associate"},
	{Name: "AssociateTimeSeriesToAssetProperty", Method: "POST", URI: "/timeseries/associate/"},
	{Name: "BatchAssociateProjectAssets", Method: "POST", URI: "/projects/{projectId}/assets/associate"},
	{Name: "BatchDisassociateProjectAssets", Method: "POST", URI: "/projects/{projectId}/assets/disassociate"},
	{Name: "BatchGetAssetPropertyAggregates", Method: "POST", URI: "/properties/batch/aggregates"},
	{Name: "BatchGetAssetPropertyValue", Method: "POST", URI: "/properties/batch/latest"},
	{Name: "BatchGetAssetPropertyValueHistory", Method: "POST", URI: "/properties/batch/history"},
	{Name: "BatchPutAssetPropertyValue", Method: "POST", URI: "/properties"},
	{Name: "CreateAccessPolicy", Method: "POST", URI: "/access-policies"},
	{Name: "CreateAsset", Method: "POST", URI: "/assets"},
	{Name: "CreateAssetModel", Method: "POST", URI: "/asset-models"},
	{Name: "CreateAssetModelCompositeModel", Method: "POST", URI: "/asset-models/{assetModelId}/composite-models"},
	{Name: "CreateBulkImportJob", Method: "POST", URI: "/jobs"},
	{Name: "CreateComputationModel", Method: "POST", URI: "/computation-models"},
	{Name: "CreateDashboard", Method: "POST", URI: "/dashboards"},
	{Name: "CreateDataset", Method: "POST", URI: "/datasets"},
	{Name: "CreateGateway", Method: "POST", URI: "/20200301/gateways"},
	{Name: "CreatePortal", Method: "POST", URI: "/portals"},
	{Name: "CreateProject", Method: "POST", URI: "/projects"},
	{Name: "DeleteAccessPolicy", Method: "DELETE", URI: "/access-policies/{accessPolicyId}"},
	{Name: "DeleteAsset", Method: "DELETE", URI: "/assets/{assetId}"},
	{Name: "DeleteAssetModel", Method: "DELETE", URI: "/asset-models/{assetModelId}"},
	{Name: "DeleteAssetModelCompositeModel", Method: "DELETE", URI: "/asset-models/{assetModelId}/composite-models/{assetModelCompositeModelId}"},
	{Name: "DeleteAssetModelInterfaceRelationship", Method: "DELETE", URI: "/asset-models/{assetModelId}/interface/{interfaceAssetModelId}/asset-model-interface-relationship"},
	{Name: "DeleteComputationModel", Method: "DELETE", URI: "/computation-models/{computationModelId}"},
	{Name: "DeleteDashboard", Method: "DELETE", URI: "/dashboards/{dashboardId}"},
	{Name: "DeleteDataset", Method: "DELETE", URI: "/datasets/{datasetId}"},
	{Name: "DeleteGateway", Method: "DELETE", URI: "/20200301/gateways/{gatewayId}"},
	{Name: "DeletePortal", Method: "DELETE", URI: "/portals/{portalId}"},
	{Name: "DeleteProject", Method: "DELETE", URI: "/projects/{projectId}"},
	{Name: "DeleteTimeSeries", Method: "POST", URI: "/timeseries/delete/"},
	{Name: "DescribeAccessPolicy", Method: "GET", URI: "/access-policies/{accessPolicyId}"},
	{Name: "DescribeAction", Method: "GET", URI: "/actions/{actionId}"},
	{Name: "DescribeAsset", Method: "GET", URI: "/assets/{assetId}"},
	{Name: "DescribeAssetCompositeModel", Method: "GET", URI: "/assets/{assetId}/composite-models/{assetCompositeModelId}"},
	{Name: "DescribeAssetModel", Method: "GET", URI: "/asset-models/{assetModelId}"},
	{Name: "DescribeAssetModelCompositeModel", Method: "GET", URI: "/asset-models/{assetModelId}/composite-models/{assetModelCompositeModelId}"},
	{Name: "DescribeAssetModelInterfaceRelationship", Method: "GET", URI: "/asset-models/{assetModelId}/interface/{interfaceAssetModelId}/asset-model-interface-relationship"},
	{Name: "DescribeAssetProperty", Method: "GET", URI: "/assets/{assetId}/properties/{propertyId}"},
	{Name: "DescribeBulkImportJob", Method: "GET", URI: "/jobs/{jobId}"},
	{Name: "DescribeComputationModel", Method: "GET", URI: "/computation-models/{computationModelId}"},
	{Name: "DescribeComputationModelExecutionSummary", Method: "GET", URI: "/computation-models/{computationModelId}/execution-summary"},
	{Name: "DescribeDashboard", Method: "GET", URI: "/dashboards/{dashboardId}"},
	{Name: "DescribeDataset", Method: "GET", URI: "/datasets/{datasetId}"},
	{Name: "DescribeDefaultEncryptionConfiguration", Method: "GET", URI: "/configuration/account/encryption"},
	{Name: "DescribeExecution", Method: "GET", URI: "/executions/{executionId}"},
	{Name: "DescribeGateway", Method: "GET", URI: "/20200301/gateways/{gatewayId}"},
	{Name: "DescribeGatewayCapabilityConfiguration", Method: "GET", URI: "/20200301/gateways/{gatewayId}/capability/{capabilityNamespace}"},
	{Name: "DescribeLoggingOptions", Method: "GET", URI: "/logging"},
	{Name: "DescribePortal", Method: "GET", URI: "/portals/{portalId}"},
	{Name: "DescribeProject", Method: "GET", URI: "/projects/{projectId}"},
	{Name: "DescribeStorageConfiguration", Method: "GET", URI: "/configuration/account/storage"},
	{Name: "DescribeTimeSeries", Method: "GET", URI: "/timeseries/describe/"},
	{Name: "DisassociateAssets", Method: "POST", URI: "/assets/{assetId}/disassociate"},
	{Name: "DisassociateTimeSeriesFromAssetProperty", Method: "POST", URI: "/timeseries/disassociate/"},
	{Name: "ExecuteAction", Method: "POST", URI: "/actions"},
	{Name: "ExecuteQuery", Method: "POST", URI: "/queries/execution"},
	{Name: "GetAssetPropertyAggregates", Method: "GET", URI: "/properties/aggregates"},
	{Name: "GetAssetPropertyValue", Method: "GET", URI: "/properties/latest"},
	{Name: "GetAssetPropertyValueHistory", Method: "GET", URI: "/properties/history"},
	{Name: "GetInterpolatedAssetPropertyValues", Method: "GET", URI: "/properties/interpolated"},
	{Name: "InvokeAssistant", Method: "POST", URI: "/assistant/invocation"},
	{Name: "ListAccessPolicies", Method: "GET", URI: "/access-policies"},
	{Name: "ListActions", Method: "GET", URI: "/actions"},
	{Name: "ListAssetModelCompositeModels", Method: "GET", URI: "/asset-models/{assetModelId}/composite-models"},
	{Name: "ListAssetModelProperties", Method: "GET", URI: "/asset-models/{assetModelId}/properties"},
	{Name: "ListAssetModels", Method: "GET", URI: "/asset-models"},
	{Name: "ListAssetProperties", Method: "GET", URI: "/assets/{assetId}/properties"},
	{Name: "ListAssetRelationships", Method: "GET", URI: "/assets/{assetId}/assetRelationships"},
	{Name: "ListAssets", Method: "GET", URI: "/assets"},
	{Name: "ListAssociatedAssets", Method: "GET", URI: "/assets/{assetId}/hierarchies"},
	{Name: "ListBulkImportJobs", Method: "GET", URI: "/jobs"},
	{Name: "ListCompositionRelationships", Method: "GET", URI: "/asset-models/{assetModelId}/composition-relationships"},
	{Name: "ListComputationModelDataBindingUsages", Method: "POST", URI: "/computation-models/data-binding-usages"},
	{Name: "ListComputationModelResolveToResources", Method: "GET", URI: "/computation-models/{computationModelId}/resolve-to-resources"},
	{Name: "ListComputationModels", Method: "GET", URI: "/computation-models"},
	{Name: "ListDashboards", Method: "GET", URI: "/dashboards"},
	{Name: "ListDatasets", Method: "GET", URI: "/datasets"},
	{Name: "ListExecutions", Method: "GET", URI: "/executions"},
	{Name: "ListGateways", Method: "GET", URI: "/20200301/gateways"},
	{Name: "ListInterfaceRelationships", Method: "GET", URI: "/interface/{interfaceAssetModelId}/asset-models"},
	{Name: "ListPortals", Method: "GET", URI: "/portals"},
	{Name: "ListProjectAssets", Method: "GET", URI: "/projects/{projectId}/assets"},
	{Name: "ListProjects", Method: "GET", URI: "/projects"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/tags"},
	{Name: "ListTimeSeries", Method: "GET", URI: "/timeseries/"},
	{Name: "PutAssetModelInterfaceRelationship", Method: "PUT", URI: "/asset-models/{assetModelId}/interface/{interfaceAssetModelId}/asset-model-interface-relationship"},
	{Name: "PutDefaultEncryptionConfiguration", Method: "POST", URI: "/configuration/account/encryption"},
	{Name: "PutLoggingOptions", Method: "PUT", URI: "/logging"},
	{Name: "PutStorageConfiguration", Method: "POST", URI: "/configuration/account/storage"},
	{Name: "TagResource", Method: "POST", URI: "/tags"},
	{Name: "UntagResource", Method: "DELETE", URI: "/tags"},
	{Name: "UpdateAccessPolicy", Method: "PUT", URI: "/access-policies/{accessPolicyId}"},
	{Name: "UpdateAsset", Method: "PUT", URI: "/assets/{assetId}"},
	{Name: "UpdateAssetModel", Method: "PUT", URI: "/asset-models/{assetModelId}"},
	{Name: "UpdateAssetModelCompositeModel", Method: "PUT", URI: "/asset-models/{assetModelId}/composite-models/{assetModelCompositeModelId}"},
	{Name: "UpdateAssetProperty", Method: "PUT", URI: "/assets/{assetId}/properties/{propertyId}"},
	{Name: "UpdateComputationModel", Method: "POST", URI: "/computation-models/{computationModelId}"},
	{Name: "UpdateDashboard", Method: "PUT", URI: "/dashboards/{dashboardId}"},
	{Name: "UpdateDataset", Method: "PUT", URI: "/datasets/{datasetId}"},
	{Name: "UpdateGateway", Method: "PUT", URI: "/20200301/gateways/{gatewayId}"},
	{Name: "UpdateGatewayCapabilityConfiguration", Method: "POST", URI: "/20200301/gateways/{gatewayId}/capability"},
	{Name: "UpdatePortal", Method: "PUT", URI: "/portals/{portalId}"},
	{Name: "UpdateProject", Method: "PUT", URI: "/projects/{projectId}"},
}

var iotSiteWiseOperationByName = func() map[string]iotSiteWiseOperation {
	out := make(map[string]iotSiteWiseOperation, len(iotSiteWiseOperations))
	for _, op := range iotSiteWiseOperations {
		out[op.Name] = op
	}
	return out
}()
