package server

type iotWirelessOperation struct {
	Name   string
	Method string
	URI    string
}

// AWS IoT Wireless operations sourced from:
// https://docs.aws.amazon.com/iot-wireless/latest/apireference/API_Operations.html
var iotWirelessOperations = []iotWirelessOperation{
	{Name: "AssociateAwsAccountWithPartnerAccount", Method: "POST", URI: "/partner-accounts"},
	{Name: "AssociateMulticastGroupWithFuotaTask", Method: "PUT", URI: "/fuota-tasks/{Id}/multicast-group"},
	{Name: "AssociateWirelessDeviceWithFuotaTask", Method: "PUT", URI: "/fuota-tasks/{Id}/wireless-device"},
	{Name: "AssociateWirelessDeviceWithMulticastGroup", Method: "PUT", URI: "/multicast-groups/{Id}/wireless-device"},
	{Name: "AssociateWirelessDeviceWithThing", Method: "PUT", URI: "/wireless-devices/{Id}/thing"},
	{Name: "AssociateWirelessGatewayWithCertificate", Method: "PUT", URI: "/wireless-gateways/{Id}/certificate"},
	{Name: "AssociateWirelessGatewayWithThing", Method: "PUT", URI: "/wireless-gateways/{Id}/thing"},
	{Name: "CancelMulticastGroupSession", Method: "DELETE", URI: "/multicast-groups/{Id}/session"},
	{Name: "CreateDestination", Method: "POST", URI: "/destinations"},
	{Name: "CreateDeviceProfile", Method: "POST", URI: "/device-profiles"},
	{Name: "CreateFuotaTask", Method: "POST", URI: "/fuota-tasks"},
	{Name: "CreateMulticastGroup", Method: "POST", URI: "/multicast-groups"},
	{Name: "CreateNetworkAnalyzerConfiguration", Method: "POST", URI: "/network-analyzer-configurations"},
	{Name: "CreateServiceProfile", Method: "POST", URI: "/service-profiles"},
	{Name: "CreateWirelessDevice", Method: "POST", URI: "/wireless-devices"},
	{Name: "CreateWirelessGateway", Method: "POST", URI: "/wireless-gateways"},
	{Name: "CreateWirelessGatewayTask", Method: "POST", URI: "/wireless-gateways/{Id}/tasks"},
	{Name: "CreateWirelessGatewayTaskDefinition", Method: "POST", URI: "/wireless-gateway-task-definitions"},
	{Name: "DeleteDestination", Method: "DELETE", URI: "/destinations/{Name}"},
	{Name: "DeleteDeviceProfile", Method: "DELETE", URI: "/device-profiles/{Id}"},
	{Name: "DeleteFuotaTask", Method: "DELETE", URI: "/fuota-tasks/{Id}"},
	{Name: "DeleteMulticastGroup", Method: "DELETE", URI: "/multicast-groups/{Id}"},
	{Name: "DeleteNetworkAnalyzerConfiguration", Method: "DELETE", URI: "/network-analyzer-configurations/{ConfigurationName}"},
	{Name: "DeleteQueuedMessages", Method: "DELETE", URI: "/wireless-devices/{Id}/data"},
	{Name: "DeleteServiceProfile", Method: "DELETE", URI: "/service-profiles/{Id}"},
	{Name: "DeleteWirelessDevice", Method: "DELETE", URI: "/wireless-devices/{Id}"},
	{Name: "DeleteWirelessDeviceImportTask", Method: "DELETE", URI: "/wireless_device_import_task/{Id}"},
	{Name: "DeleteWirelessGateway", Method: "DELETE", URI: "/wireless-gateways/{Id}"},
	{Name: "DeleteWirelessGatewayTask", Method: "DELETE", URI: "/wireless-gateways/{Id}/tasks"},
	{Name: "DeleteWirelessGatewayTaskDefinition", Method: "DELETE", URI: "/wireless-gateway-task-definitions/{Id}"},
	{Name: "DeregisterWirelessDevice", Method: "PATCH", URI: "/wireless-devices/{Identifier}/deregister"},
	{Name: "DisassociateAwsAccountFromPartnerAccount", Method: "DELETE", URI: "/partner-accounts/{PartnerAccountId}"},
	{Name: "DisassociateMulticastGroupFromFuotaTask", Method: "DELETE", URI: "/fuota-tasks/{Id}/multicast-groups/{MulticastGroupId}"},
	{Name: "DisassociateWirelessDeviceFromFuotaTask", Method: "DELETE", URI: "/fuota-tasks/{Id}/wireless-devices/{WirelessDeviceId}"},
	{Name: "DisassociateWirelessDeviceFromMulticastGroup", Method: "DELETE", URI: "/multicast-groups/{Id}/wireless-devices/{WirelessDeviceId}"},
	{Name: "DisassociateWirelessDeviceFromThing", Method: "DELETE", URI: "/wireless-devices/{Id}/thing"},
	{Name: "DisassociateWirelessGatewayFromCertificate", Method: "DELETE", URI: "/wireless-gateways/{Id}/certificate"},
	{Name: "DisassociateWirelessGatewayFromThing", Method: "DELETE", URI: "/wireless-gateways/{Id}/thing"},
	{Name: "GetDestination", Method: "GET", URI: "/destinations/{Name}"},
	{Name: "GetDeviceProfile", Method: "GET", URI: "/device-profiles/{Id}"},
	{Name: "GetEventConfigurationByResourceTypes", Method: "GET", URI: "/event-configurations-resource-types"},
	{Name: "GetFuotaTask", Method: "GET", URI: "/fuota-tasks/{Id}"},
	{Name: "GetLogLevelsByResourceTypes", Method: "GET", URI: "/log-levels"},
	{Name: "GetMetricConfiguration", Method: "GET", URI: "/metric-configuration"},
	{Name: "GetMetrics", Method: "POST", URI: "/metrics"},
	{Name: "GetMulticastGroup", Method: "GET", URI: "/multicast-groups/{Id}"},
	{Name: "GetMulticastGroupSession", Method: "GET", URI: "/multicast-groups/{Id}/session"},
	{Name: "GetNetworkAnalyzerConfiguration", Method: "GET", URI: "/network-analyzer-configurations/{ConfigurationName}"},
	{Name: "GetPartnerAccount", Method: "GET", URI: "/partner-accounts/{PartnerAccountId}"},
	{Name: "GetPosition", Method: "GET", URI: "/positions/{ResourceIdentifier}"},
	{Name: "GetPositionConfiguration", Method: "GET", URI: "/position-configurations/{ResourceIdentifier}"},
	{Name: "GetPositionEstimate", Method: "POST", URI: "/position-estimate"},
	{Name: "GetResourceEventConfiguration", Method: "GET", URI: "/event-configurations/{Identifier}"},
	{Name: "GetResourceLogLevel", Method: "GET", URI: "/log-levels/{ResourceIdentifier}"},
	{Name: "GetResourcePosition", Method: "GET", URI: "/resource-positions/{ResourceIdentifier}"},
	{Name: "GetServiceEndpoint", Method: "GET", URI: "/service-endpoint"},
	{Name: "GetServiceProfile", Method: "GET", URI: "/service-profiles/{Id}"},
	{Name: "GetWirelessDevice", Method: "GET", URI: "/wireless-devices/{Identifier}"},
	{Name: "GetWirelessDeviceImportTask", Method: "GET", URI: "/wireless_device_import_task/{Id}"},
	{Name: "GetWirelessDeviceStatistics", Method: "GET", URI: "/wireless-devices/{Id}/statistics"},
	{Name: "GetWirelessGateway", Method: "GET", URI: "/wireless-gateways/{Identifier}"},
	{Name: "GetWirelessGatewayCertificate", Method: "GET", URI: "/wireless-gateways/{Id}/certificate"},
	{Name: "GetWirelessGatewayFirmwareInformation", Method: "GET", URI: "/wireless-gateways/{Id}/firmware-information"},
	{Name: "GetWirelessGatewayStatistics", Method: "GET", URI: "/wireless-gateways/{Id}/statistics"},
	{Name: "GetWirelessGatewayTask", Method: "GET", URI: "/wireless-gateways/{Id}/tasks"},
	{Name: "GetWirelessGatewayTaskDefinition", Method: "GET", URI: "/wireless-gateway-task-definitions/{Id}"},
	{Name: "ListDestinations", Method: "GET", URI: "/destinations"},
	{Name: "ListDeviceProfiles", Method: "GET", URI: "/device-profiles"},
	{Name: "ListDevicesForWirelessDeviceImportTask", Method: "GET", URI: "/wireless_device_import_task"},
	{Name: "ListEventConfigurations", Method: "GET", URI: "/event-configurations"},
	{Name: "ListFuotaTasks", Method: "GET", URI: "/fuota-tasks"},
	{Name: "ListMulticastGroups", Method: "GET", URI: "/multicast-groups"},
	{Name: "ListMulticastGroupsByFuotaTask", Method: "GET", URI: "/fuota-tasks/{Id}/multicast-groups"},
	{Name: "ListNetworkAnalyzerConfigurations", Method: "GET", URI: "/network-analyzer-configurations"},
	{Name: "ListPartnerAccounts", Method: "GET", URI: "/partner-accounts"},
	{Name: "ListPositionConfigurations", Method: "GET", URI: "/position-configurations"},
	{Name: "ListQueuedMessages", Method: "GET", URI: "/wireless-devices/{Id}/data"},
	{Name: "ListServiceProfiles", Method: "GET", URI: "/service-profiles"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/tags"},
	{Name: "ListWirelessDeviceImportTasks", Method: "GET", URI: "/wireless_device_import_tasks"},
	{Name: "ListWirelessDevices", Method: "GET", URI: "/wireless-devices"},
	{Name: "ListWirelessGatewayTaskDefinitions", Method: "GET", URI: "/wireless-gateway-task-definitions"},
	{Name: "ListWirelessGateways", Method: "GET", URI: "/wireless-gateways"},
	{Name: "PutPositionConfiguration", Method: "PUT", URI: "/position-configurations/{ResourceIdentifier}"},
	{Name: "PutResourceLogLevel", Method: "PUT", URI: "/log-levels/{ResourceIdentifier}"},
	{Name: "ResetAllResourceLogLevels", Method: "DELETE", URI: "/log-levels"},
	{Name: "ResetResourceLogLevel", Method: "DELETE", URI: "/log-levels/{ResourceIdentifier}"},
	{Name: "SendDataToMulticastGroup", Method: "POST", URI: "/multicast-groups/{Id}/data"},
	{Name: "SendDataToWirelessDevice", Method: "POST", URI: "/wireless-devices/{Id}/data"},
	{Name: "StartBulkAssociateWirelessDeviceWithMulticastGroup", Method: "PATCH", URI: "/multicast-groups/{Id}/bulk"},
	{Name: "StartBulkDisassociateWirelessDeviceFromMulticastGroup", Method: "POST", URI: "/multicast-groups/{Id}/bulk"},
	{Name: "StartFuotaTask", Method: "PUT", URI: "/fuota-tasks/{Id}"},
	{Name: "StartMulticastGroupSession", Method: "PUT", URI: "/multicast-groups/{Id}/session"},
	{Name: "StartSingleWirelessDeviceImportTask", Method: "POST", URI: "/wireless_single_device_import_task"},
	{Name: "StartWirelessDeviceImportTask", Method: "POST", URI: "/wireless_device_import_task"},
	{Name: "TagResource", Method: "POST", URI: "/tags"},
	{Name: "TestWirelessDevice", Method: "POST", URI: "/wireless-devices/{Id}/test"},
	{Name: "UntagResource", Method: "DELETE", URI: "/tags"},
	{Name: "UpdateDestination", Method: "PATCH", URI: "/destinations/{Name}"},
	{Name: "UpdateEventConfigurationByResourceTypes", Method: "PATCH", URI: "/event-configurations-resource-types"},
	{Name: "UpdateFuotaTask", Method: "PATCH", URI: "/fuota-tasks/{Id}"},
	{Name: "UpdateLogLevelsByResourceTypes", Method: "POST", URI: "/log-levels"},
	{Name: "UpdateMetricConfiguration", Method: "PUT", URI: "/metric-configuration"},
	{Name: "UpdateMulticastGroup", Method: "PATCH", URI: "/multicast-groups/{Id}"},
	{Name: "UpdateNetworkAnalyzerConfiguration", Method: "PATCH", URI: "/network-analyzer-configurations/{ConfigurationName}"},
	{Name: "UpdatePartnerAccount", Method: "PATCH", URI: "/partner-accounts/{PartnerAccountId}"},
	{Name: "UpdatePosition", Method: "PATCH", URI: "/positions/{ResourceIdentifier}"},
	{Name: "UpdateResourceEventConfiguration", Method: "PATCH", URI: "/event-configurations/{Identifier}"},
	{Name: "UpdateResourcePosition", Method: "PATCH", URI: "/resource-positions/{ResourceIdentifier}"},
	{Name: "UpdateWirelessDevice", Method: "PATCH", URI: "/wireless-devices/{Id}"},
	{Name: "UpdateWirelessDeviceImportTask", Method: "PATCH", URI: "/wireless_device_import_task/{Id}"},
	{Name: "UpdateWirelessGateway", Method: "PATCH", URI: "/wireless-gateways/{Id}"},
}

var iotWirelessOperationByName = func() map[string]iotWirelessOperation {
	out := make(map[string]iotWirelessOperation, len(iotWirelessOperations))
	for _, op := range iotWirelessOperations {
		out[op.Name] = op
	}
	return out
}()
