package server

type lambdaOperation struct {
	Name string
}

var lambdaOperations = []lambdaOperation{
	{Name: "AddLayerVersionPermission"},
	{Name: "AddPermission"},
	{Name: "CheckpointDurableExecution"},
	{Name: "CreateAlias"},
	{Name: "CreateCapacityProvider"},
	{Name: "CreateCodeSigningConfig"},
	{Name: "CreateEventSourceMapping"},
	{Name: "CreateFunction"},
	{Name: "CreateFunctionUrlConfig"},
	{Name: "DeleteAlias"},
	{Name: "DeleteCapacityProvider"},
	{Name: "DeleteCodeSigningConfig"},
	{Name: "DeleteEventSourceMapping"},
	{Name: "DeleteFunction"},
	{Name: "DeleteFunctionCodeSigningConfig"},
	{Name: "DeleteFunctionConcurrency"},
	{Name: "DeleteFunctionEventInvokeConfig"},
	{Name: "DeleteFunctionUrlConfig"},
	{Name: "DeleteLayerVersion"},
	{Name: "DeleteProvisionedConcurrencyConfig"},
	{Name: "GetAccountSettings"},
	{Name: "GetAlias"},
	{Name: "GetCapacityProvider"},
	{Name: "GetCodeSigningConfig"},
	{Name: "GetDurableExecution"},
	{Name: "GetDurableExecutionHistory"},
	{Name: "GetDurableExecutionState"},
	{Name: "GetEventSourceMapping"},
	{Name: "GetFunction"},
	{Name: "GetFunctionCodeSigningConfig"},
	{Name: "GetFunctionConcurrency"},
	{Name: "GetFunctionConfiguration"},
	{Name: "GetFunctionEventInvokeConfig"},
	{Name: "GetFunctionRecursionConfig"},
	{Name: "GetFunctionScalingConfig"},
	{Name: "GetFunctionUrlConfig"},
	{Name: "GetLayerVersion"},
	{Name: "GetLayerVersionByArn"},
	{Name: "GetLayerVersionPolicy"},
	{Name: "GetPolicy"},
	{Name: "GetProvisionedConcurrencyConfig"},
	{Name: "GetRuntimeManagementConfig"},
	{Name: "Invoke"},
	{Name: "InvokeAsync"},
	{Name: "InvokeWithResponseStream"},
	{Name: "ListAliases"},
	{Name: "ListCapacityProviders"},
	{Name: "ListCodeSigningConfigs"},
	{Name: "ListDurableExecutionsByFunction"},
	{Name: "ListEventSourceMappings"},
	{Name: "ListFunctionEventInvokeConfigs"},
	{Name: "ListFunctionUrlConfigs"},
	{Name: "ListFunctionVersionsByCapacityProvider"},
	{Name: "ListFunctions"},
	{Name: "ListFunctionsByCodeSigningConfig"},
	{Name: "ListLayerVersions"},
	{Name: "ListLayers"},
	{Name: "ListProvisionedConcurrencyConfigs"},
	{Name: "ListTags"},
	{Name: "ListVersionsByFunction"},
	{Name: "PublishLayerVersion"},
	{Name: "PublishVersion"},
	{Name: "PutFunctionCodeSigningConfig"},
	{Name: "PutFunctionConcurrency"},
	{Name: "PutFunctionEventInvokeConfig"},
	{Name: "PutFunctionRecursionConfig"},
	{Name: "PutFunctionScalingConfig"},
	{Name: "PutProvisionedConcurrencyConfig"},
	{Name: "PutRuntimeManagementConfig"},
	{Name: "RemoveLayerVersionPermission"},
	{Name: "RemovePermission"},
	{Name: "SendDurableExecutionCallbackFailure"},
	{Name: "SendDurableExecutionCallbackHeartbeat"},
	{Name: "SendDurableExecutionCallbackSuccess"},
	{Name: "StopDurableExecution"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateAlias"},
	{Name: "UpdateCapacityProvider"},
	{Name: "UpdateCodeSigningConfig"},
	{Name: "UpdateEventSourceMapping"},
	{Name: "UpdateFunctionCode"},
	{Name: "UpdateFunctionConfiguration"},
	{Name: "UpdateFunctionEventInvokeConfig"},
	{Name: "UpdateFunctionUrlConfig"},
}

var lambdaOperationByName = func() map[string]lambdaOperation {
	out := make(map[string]lambdaOperation, len(lambdaOperations))
	for _, op := range lambdaOperations {
		out[op.Name] = op
	}
	return out
}()
