package server

type lexV2Operation struct {
	Name   string
	Method string
	URI    string
}

// Amazon Lex V2 actions sourced from:
// https://docs.aws.amazon.com/lexv2/latest/APIReference/API_Operations.html
var lexV2Operations = []lexV2Operation{
	{Name: "BatchCreateCustomVocabularyItem", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary/DEFAULT/batchcreate"},
	{Name: "BatchDeleteCustomVocabularyItem", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary/DEFAULT/batchdelete"},
	{Name: "BatchUpdateCustomVocabularyItem", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary/DEFAULT/batchupdate"},
	{Name: "BuildBotLocale", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/"},
	{Name: "CreateBot", Method: "PUT", URI: "/bots/"},
	{Name: "CreateBotAlias", Method: "PUT", URI: "/bots/{botId}/botaliases/"},
	{Name: "CreateBotLocale", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/"},
	{Name: "CreateBotReplica", Method: "PUT", URI: "/bots/{botId}/replicas/"},
	{Name: "CreateBotVersion", Method: "PUT", URI: "/bots/{botId}/botversions/"},
	{Name: "CreateExport", Method: "PUT", URI: "/exports/"},
	{Name: "CreateIntent", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/"},
	{Name: "CreateResourcePolicy", Method: "POST", URI: "/policy/{resourceArn}/"},
	{Name: "CreateResourcePolicyStatement", Method: "POST", URI: "/policy/{resourceArn}/statements/"},
	{Name: "CreateSlot", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/slots/"},
	{Name: "CreateSlotType", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/slottypes/"},
	{Name: "CreateTestSetDiscrepancyReport", Method: "POST", URI: "/testsets/{testSetId}/testsetdiscrepancy"},
	{Name: "CreateUploadUrl", Method: "POST", URI: "/createuploadurl/"},
	{Name: "DeleteBot", Method: "DELETE", URI: "/bots/{botId}/"},
	{Name: "DeleteBotAlias", Method: "DELETE", URI: "/bots/{botId}/botaliases/{botAliasId}/"},
	{Name: "DeleteBotLocale", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/"},
	{Name: "DeleteBotReplica", Method: "DELETE", URI: "/bots/{botId}/replicas/{replicaRegion}/"},
	{Name: "DeleteBotVersion", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/"},
	{Name: "DeleteCustomVocabulary", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary"},
	{Name: "DeleteExport", Method: "DELETE", URI: "/exports/{exportId}/"},
	{Name: "DeleteImport", Method: "DELETE", URI: "/imports/{importId}/"},
	{Name: "DeleteIntent", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/"},
	{Name: "DeleteResourcePolicy", Method: "DELETE", URI: "/policy/{resourceArn}/"},
	{Name: "DeleteResourcePolicyStatement", Method: "DELETE", URI: "/policy/{resourceArn}/statements/{statementId}/"},
	{Name: "DeleteSlot", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/slots/{slotId}/"},
	{Name: "DeleteSlotType", Method: "DELETE", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/slottypes/{slotTypeId}/"},
	{Name: "DeleteTestSet", Method: "DELETE", URI: "/testsets/{testSetId}"},
	{Name: "DeleteUtterances", Method: "DELETE", URI: "/bots/{botId}/utterances/"},
	{Name: "DescribeBot", Method: "GET", URI: "/bots/{botId}/"},
	{Name: "DescribeBotAlias", Method: "GET", URI: "/bots/{botId}/botaliases/{botAliasId}/"},
	{Name: "DescribeBotLocale", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/"},
	{Name: "DescribeBotRecommendation", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/{botRecommendationId}/"},
	{Name: "DescribeBotReplica", Method: "GET", URI: "/bots/{botId}/replicas/{replicaRegion}/"},
	{Name: "DescribeBotResourceGeneration", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/generations/{generationId}"},
	{Name: "DescribeBotVersion", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/"},
	{Name: "DescribeCustomVocabularyMetadata", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary/DEFAULT/metadata"},
	{Name: "DescribeExport", Method: "GET", URI: "/exports/{exportId}/"},
	{Name: "DescribeImport", Method: "GET", URI: "/imports/{importId}/"},
	{Name: "DescribeIntent", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/"},
	{Name: "DescribeResourcePolicy", Method: "GET", URI: "/policy/{resourceArn}/"},
	{Name: "DescribeSlot", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/slots/{slotId}/"},
	{Name: "DescribeSlotType", Method: "GET", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/slottypes/{slotTypeId}/"},
	{Name: "DescribeTestExecution", Method: "GET", URI: "/testexecutions/{testExecutionId}"},
	{Name: "DescribeTestSet", Method: "GET", URI: "/testsets/{testSetId}"},
	{Name: "DescribeTestSetDiscrepancyReport", Method: "GET", URI: "/testsetdiscrepancy/{testSetDiscrepancyReportId}"},
	{Name: "DescribeTestSetGeneration", Method: "GET", URI: "/testsetgenerations/{testSetGenerationId}"},
	{Name: "GenerateBotElement", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/generate"},
	{Name: "GetTestExecutionArtifactsUrl", Method: "GET", URI: "/testexecutions/{testExecutionId}/artifacturl"},
	{Name: "ListAggregatedUtterances", Method: "POST", URI: "/bots/{botId}/aggregatedutterances/"},
	{Name: "ListBotAliasReplicas", Method: "POST", URI: "/bots/{botId}/replicas/{replicaRegion}/botaliases/"},
	{Name: "ListBotAliases", Method: "POST", URI: "/bots/{botId}/botaliases/"},
	{Name: "ListBotLocales", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/"},
	{Name: "ListBotRecommendations", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/"},
	{Name: "ListBotReplicas", Method: "POST", URI: "/bots/{botId}/replicas/"},
	{Name: "ListBotResourceGenerations", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/generations"},
	{Name: "ListBotVersionReplicas", Method: "POST", URI: "/bots/{botId}/replicas/{replicaRegion}/botversions/"},
	{Name: "ListBotVersions", Method: "POST", URI: "/bots/{botId}/botversions/"},
	{Name: "ListBots", Method: "POST", URI: "/bots/"},
	{Name: "ListBuiltInIntents", Method: "POST", URI: "/builtins/locales/{localeId}/intents/"},
	{Name: "ListBuiltInSlotTypes", Method: "POST", URI: "/builtins/locales/{localeId}/slottypes/"},
	{Name: "ListCustomVocabularyItems", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/customvocabulary/DEFAULT/list"},
	{Name: "ListExports", Method: "POST", URI: "/exports/"},
	{Name: "ListImports", Method: "POST", URI: "/imports/"},
	{Name: "ListIntentMetrics", Method: "POST", URI: "/bots/{botId}/analytics/intentmetrics"},
	{Name: "ListIntentPaths", Method: "POST", URI: "/bots/{botId}/analytics/intentpaths"},
	{Name: "ListIntentStageMetrics", Method: "POST", URI: "/bots/{botId}/analytics/intentstagemetrics"},
	{Name: "ListIntents", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/"},
	{Name: "ListRecommendedIntents", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/{botRecommendationId}/intents"},
	{Name: "ListSessionAnalyticsData", Method: "POST", URI: "/bots/{botId}/analytics/sessions"},
	{Name: "ListSessionMetrics", Method: "POST", URI: "/bots/{botId}/analytics/sessionmetrics"},
	{Name: "ListSlotTypes", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/slottypes/"},
	{Name: "ListSlots", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/slots/"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/tags/{resourceARN}"},
	{Name: "ListTestExecutionResultItems", Method: "POST", URI: "/testexecutions/{testExecutionId}/results"},
	{Name: "ListTestExecutions", Method: "POST", URI: "/testexecutions"},
	{Name: "ListTestSetRecords", Method: "POST", URI: "/testsets/{testSetId}/records"},
	{Name: "ListTestSets", Method: "POST", URI: "/testsets"},
	{Name: "ListUtteranceAnalyticsData", Method: "POST", URI: "/bots/{botId}/analytics/utterances"},
	{Name: "ListUtteranceMetrics", Method: "POST", URI: "/bots/{botId}/analytics/utterancemetrics"},
	{Name: "SearchAssociatedTranscripts", Method: "POST", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/{botRecommendationId}/associatedtranscripts"},
	{Name: "StartBotRecommendation", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/"},
	{Name: "StartBotResourceGeneration", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/startgeneration"},
	{Name: "StartImport", Method: "PUT", URI: "/imports/"},
	{Name: "StartTestExecution", Method: "POST", URI: "/testsets/{testSetId}/testexecutions"},
	{Name: "StartTestSetGeneration", Method: "PUT", URI: "/testsetgenerations"},
	{Name: "StopBotRecommendation", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/{botRecommendationId}/stopbotrecommendation"},
	{Name: "TagResource", Method: "POST", URI: "/tags/{resourceARN}"},
	{Name: "UntagResource", Method: "DELETE", URI: "/tags/{resourceARN}"},
	{Name: "UpdateBot", Method: "PUT", URI: "/bots/{botId}/"},
	{Name: "UpdateBotAlias", Method: "PUT", URI: "/bots/{botId}/botaliases/{botAliasId}/"},
	{Name: "UpdateBotLocale", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/"},
	{Name: "UpdateBotRecommendation", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/botrecommendations/{botRecommendationId}/"},
	{Name: "UpdateExport", Method: "PUT", URI: "/exports/{exportId}/"},
	{Name: "UpdateIntent", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/"},
	{Name: "UpdateResourcePolicy", Method: "PUT", URI: "/policy/{resourceArn}/"},
	{Name: "UpdateSlot", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/intents/{intentId}/slots/{slotId}/"},
	{Name: "UpdateSlotType", Method: "PUT", URI: "/bots/{botId}/botversions/{botVersion}/botlocales/{localeId}/slottypes/{slotTypeId}/"},
	{Name: "UpdateTestSet", Method: "PUT", URI: "/testsets/{testSetId}"},
}

var lexV2OperationByName = func() map[string]lexV2Operation {
	out := make(map[string]lexV2Operation, len(lexV2Operations))
	for _, op := range lexV2Operations {
		out[op.Name] = op
	}
	return out
}()
