package server

type omicsOperation struct {
	Name   string
	Method string
	URI    string
}

// Amazon HealthOmics operations sourced from:
// https://docs.aws.amazon.com/omics/latest/APIReference/API_Operations.html
var omicsOperations = []omicsOperation{
	{Name: "AbortMultipartReadSetUpload", Method: "DELETE", URI: "/sequencestore/sequenceStoreId"},
	{Name: "AcceptShare", Method: "POST", URI: "/share/shareId"},
	{Name: "BatchDeleteReadSet", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "CancelAnnotationImportJob", Method: "DELETE", URI: "/import/annotation/jobId"},
	{Name: "CancelRun", Method: "POST", URI: "/run/id"},
	{Name: "CancelVariantImportJob", Method: "DELETE", URI: "/import/variant/jobId"},
	{Name: "CompleteMultipartReadSetUpload", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "CreateAnnotationStore", Method: "POST", URI: "/annotationStore"},
	{Name: "CreateAnnotationStoreVersion", Method: "POST", URI: "/annotationStore/name"},
	{Name: "CreateMultipartReadSetUpload", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "CreateReferenceStore", Method: "POST", URI: "/referencestore"},
	{Name: "CreateRunCache", Method: "POST", URI: "/runCache"},
	{Name: "CreateRunGroup", Method: "POST", URI: "/runGroup"},
	{Name: "CreateSequenceStore", Method: "POST", URI: "/sequencestore"},
	{Name: "CreateShare", Method: "POST", URI: "/share"},
	{Name: "CreateVariantStore", Method: "POST", URI: "/variantStore"},
	{Name: "CreateWorkflow", Method: "POST", URI: "/workflow"},
	{Name: "CreateWorkflowVersion", Method: "POST", URI: "/workflow/workflowId"},
	{Name: "DeleteAnnotationStore", Method: "DELETE", URI: "/annotationStore/name"},
	{Name: "DeleteAnnotationStoreVersions", Method: "POST", URI: "/annotationStore/name"},
	{Name: "DeleteReference", Method: "DELETE", URI: "/referencestore/referenceStoreId"},
	{Name: "DeleteReferenceStore", Method: "DELETE", URI: "/referencestore/id"},
	{Name: "DeleteRun", Method: "DELETE", URI: "/run/id"},
	{Name: "DeleteRunCache", Method: "DELETE", URI: "/runCache/id"},
	{Name: "DeleteRunGroup", Method: "DELETE", URI: "/runGroup/id"},
	{Name: "DeleteS3AccessPolicy", Method: "DELETE", URI: "/s3accesspolicy/s3AccessPointArn"},
	{Name: "DeleteSequenceStore", Method: "DELETE", URI: "/sequencestore/id"},
	{Name: "DeleteShare", Method: "DELETE", URI: "/share/shareId"},
	{Name: "DeleteVariantStore", Method: "DELETE", URI: "/variantStore/name"},
	{Name: "DeleteWorkflow", Method: "DELETE", URI: "/workflow/id"},
	{Name: "DeleteWorkflowVersion", Method: "DELETE", URI: "/workflow/workflowId"},
	{Name: "GetAnnotationImportJob", Method: "GET", URI: "/import/annotation/jobId"},
	{Name: "GetAnnotationStore", Method: "GET", URI: "/annotationStore/name"},
	{Name: "GetAnnotationStoreVersion", Method: "GET", URI: "/annotationStore/name"},
	{Name: "GetReadSet", Method: "GET", URI: "/sequencestore/sequenceStoreId"},
	{Name: "GetReadSetActivationJob", Method: "GET", URI: "/sequencestore/sequenceStoreId"},
	{Name: "GetReadSetExportJob", Method: "GET", URI: "/sequencestore/sequenceStoreId"},
	{Name: "GetReadSetImportJob", Method: "GET", URI: "/sequencestore/sequenceStoreId"},
	{Name: "GetReadSetMetadata", Method: "GET", URI: "/sequencestore/sequenceStoreId"},
	{Name: "GetReference", Method: "GET", URI: "/referencestore/referenceStoreId"},
	{Name: "GetReferenceImportJob", Method: "GET", URI: "/referencestore/referenceStoreId"},
	{Name: "GetReferenceMetadata", Method: "GET", URI: "/referencestore/referenceStoreId"},
	{Name: "GetReferenceStore", Method: "GET", URI: "/referencestore/id"},
	{Name: "GetRun", Method: "GET", URI: "/run/id"},
	{Name: "GetRunCache", Method: "GET", URI: "/runCache/id"},
	{Name: "GetRunGroup", Method: "GET", URI: "/runGroup/id"},
	{Name: "GetRunTask", Method: "GET", URI: "/run/id"},
	{Name: "GetS3AccessPolicy", Method: "GET", URI: "/s3accesspolicy/s3AccessPointArn"},
	{Name: "GetSequenceStore", Method: "GET", URI: "/sequencestore/id"},
	{Name: "GetShare", Method: "GET", URI: "/share/shareId"},
	{Name: "GetVariantImportJob", Method: "GET", URI: "/import/variant/jobId"},
	{Name: "GetVariantStore", Method: "GET", URI: "/variantStore/name"},
	{Name: "GetWorkflow", Method: "GET", URI: "/workflow/id"},
	{Name: "GetWorkflowVersion", Method: "GET", URI: "/workflow/workflowId"},
	{Name: "ListAnnotationImportJobs", Method: "POST", URI: "/import/annotations"},
	{Name: "ListAnnotationStores", Method: "POST", URI: "/annotationStores"},
	{Name: "ListAnnotationStoreVersions", Method: "POST", URI: "/annotationStore/name"},
	{Name: "ListMultipartReadSetUploads", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReadSetActivationJobs", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReadSetExportJobs", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReadSetImportJobs", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReadSets", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReadSetUploadParts", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "ListReferenceImportJobs", Method: "POST", URI: "/referencestore/referenceStoreId"},
	{Name: "ListReferences", Method: "POST", URI: "/referencestore/referenceStoreId"},
	{Name: "ListReferenceStores", Method: "POST", URI: "/referencestores"},
	{Name: "ListRunCaches", Method: "GET", URI: "/runCache"},
	{Name: "ListRunGroups", Method: "GET", URI: "/runGroup"},
	{Name: "ListRuns", Method: "GET", URI: "/run"},
	{Name: "ListRunTasks", Method: "GET", URI: "/run/id"},
	{Name: "ListSequenceStores", Method: "POST", URI: "/sequencestores"},
	{Name: "ListShares", Method: "POST", URI: "/shares"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/tags/resourceArn"},
	{Name: "ListVariantImportJobs", Method: "POST", URI: "/import/variants"},
	{Name: "ListVariantStores", Method: "POST", URI: "/variantStores"},
	{Name: "ListWorkflows", Method: "GET", URI: "/workflow"},
	{Name: "ListWorkflowVersions", Method: "GET", URI: "/workflow/workflowId"},
	{Name: "PutS3AccessPolicy", Method: "PUT", URI: "/s3accesspolicy/s3AccessPointArn"},
	{Name: "StartAnnotationImportJob", Method: "POST", URI: "/import/annotation"},
	{Name: "StartReadSetActivationJob", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "StartReadSetExportJob", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "StartReadSetImportJob", Method: "POST", URI: "/sequencestore/sequenceStoreId"},
	{Name: "StartReferenceImportJob", Method: "POST", URI: "/referencestore/referenceStoreId"},
	{Name: "StartRun", Method: "POST", URI: "/run"},
	{Name: "StartVariantImportJob", Method: "POST", URI: "/import/variant"},
	{Name: "TagResource", Method: "POST", URI: "/tags/resourceArn"},
	{Name: "UntagResource", Method: "DELETE", URI: "/tags/resourceArn"},
	{Name: "UpdateAnnotationStore", Method: "POST", URI: "/annotationStore/name"},
	{Name: "UpdateAnnotationStoreVersion", Method: "POST", URI: "/annotationStore/name"},
	{Name: "UpdateRunCache", Method: "POST", URI: "/runCache/id"},
	{Name: "UpdateRunGroup", Method: "POST", URI: "/runGroup/id"},
	{Name: "UpdateSequenceStore", Method: "PATCH", URI: "/sequencestore/id"},
	{Name: "UpdateVariantStore", Method: "POST", URI: "/variantStore/name"},
	{Name: "UpdateWorkflow", Method: "POST", URI: "/workflow/id"},
	{Name: "UpdateWorkflowVersion", Method: "POST", URI: "/workflow/workflowId"},
	{Name: "UploadReadSetPart", Method: "PUT", URI: "/sequencestore/sequenceStoreId"},
}

var omicsOperationByName = func() map[string]omicsOperation {
	out := make(map[string]omicsOperation, len(omicsOperations))
	for _, op := range omicsOperations {
		out[op.Name] = op
	}
	return out
}()
