package server

type partnerCentralSellingOperation struct {
	Name string
}

// AWS Partner Central Selling actions sourced from:
// https://docs.aws.amazon.com/partner-central/latest/APIReference/API_Operations.html
var partnerCentralSellingOperations = []partnerCentralSellingOperation{
	{Name: "AcceptChannelHandshake"},
	{Name: "AcceptConnectionInvitation"},
	{Name: "AcceptEngagementInvitation"},
	{Name: "AmendBenefitApplication"},
	{Name: "AssignOpportunity"},
	{Name: "AssociateAwsTrainingCertificationEmailDomain"},
	{Name: "AssociateBenefitApplicationResource"},
	{Name: "AssociateOpportunity"},
	{Name: "CancelBenefitApplication"},
	{Name: "CancelChannelHandshake"},
	{Name: "CancelConnection"},
	{Name: "CancelConnectionInvitation"},
	{Name: "CancelProfileUpdateTask"},
	{Name: "CreateBenefitApplication"},
	{Name: "CreateChannelHandshake"},
	{Name: "CreateConnectionInvitation"},
	{Name: "CreateEngagement"},
	{Name: "CreateEngagementContext"},
	{Name: "CreateEngagementInvitation"},
	{Name: "CreateOpportunity"},
	{Name: "CreatePartner"},
	{Name: "CreateProgramManagementAccount"},
	{Name: "CreateRelationship"},
	{Name: "CreateResourceSnapshot"},
	{Name: "CreateResourceSnapshotJob"},
	{Name: "DeleteProgramManagementAccount"},
	{Name: "DeleteRelationship"},
	{Name: "DeleteResourceSnapshotJob"},
	{Name: "DisassociateAwsTrainingCertificationEmailDomain"},
	{Name: "DisassociateBenefitApplicationResource"},
	{Name: "DisassociateOpportunity"},
	{Name: "GetAllianceLeadContact"},
	{Name: "GetAwsOpportunitySummary"},
	{Name: "GetBenefit"},
	{Name: "GetBenefitAllocation"},
	{Name: "GetBenefitApplication"},
	{Name: "GetConnection"},
	{Name: "GetConnectionInvitation"},
	{Name: "GetConnectionPreferences"},
	{Name: "GetEngagement"},
	{Name: "GetEngagementInvitation"},
	{Name: "GetOpportunity"},
	{Name: "GetPartner"},
	{Name: "GetProfileUpdateTask"},
	{Name: "GetProfileVisibility"},
	{Name: "GetRelationship"},
	{Name: "GetResourceSnapshot"},
	{Name: "GetResourceSnapshotJob"},
	{Name: "GetSellingSystemSettings"},
	{Name: "GetVerification"},
	{Name: "ListBenefitAllocations"},
	{Name: "ListBenefitApplications"},
	{Name: "ListBenefits"},
	{Name: "ListChannelHandshakes"},
	{Name: "ListConnectionInvitations"},
	{Name: "ListConnections"},
	{Name: "ListEngagementByAcceptingInvitationTasks"},
	{Name: "ListEngagementFromOpportunityTasks"},
	{Name: "ListEngagementInvitations"},
	{Name: "ListEngagementMembers"},
	{Name: "ListEngagementResourceAssociations"},
	{Name: "ListEngagements"},
	{Name: "ListOpportunities"},
	{Name: "ListOpportunityFromEngagementTasks"},
	{Name: "ListPartners"},
	{Name: "ListProgramManagementAccounts"},
	{Name: "ListRelationships"},
	{Name: "ListResourceSnapshotJobs"},
	{Name: "ListResourceSnapshots"},
	{Name: "ListSolutions"},
	{Name: "ListTagsForResource"},
	{Name: "Partner"},
	{Name: "PutAllianceLeadContact"},
	{Name: "PutProfileVisibility"},
	{Name: "PutSellingSystemSettings"},
	{Name: "RecallBenefitApplication"},
	{Name: "RejectChannelHandshake"},
	{Name: "RejectConnectionInvitation"},
	{Name: "RejectEngagementInvitation"},
	{Name: "SendEmailVerificationCode"},
	{Name: "StartEngagementByAcceptingInvitationTask"},
	{Name: "StartEngagementFromOpportunityTask"},
	{Name: "StartOpportunityFromEngagementTask"},
	{Name: "StartProfileUpdateTask"},
	{Name: "StartResourceSnapshotJob"},
	{Name: "StartVerification"},
	{Name: "StopResourceSnapshotJob"},
	{Name: "SubmitBenefitApplication"},
	{Name: "SubmitOpportunity"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateBenefitApplication"},
	{Name: "UpdateConnectionPreferences"},
	{Name: "UpdateEngagementContext"},
	{Name: "UpdateOpportunity"},
	{Name: "UpdateProgramManagementAccount"},
	{Name: "UpdateRelationship"},
}

var partnerCentralSellingOperationByName = func() map[string]partnerCentralSellingOperation {
	out := make(map[string]partnerCentralSellingOperation, len(partnerCentralSellingOperations))
	for _, op := range partnerCentralSellingOperations {
		out[op.Name] = op
	}
	return out
}()
