package server

type pinpointOperation struct {
	Name   string
	Method string
	URI    string
}

// Amazon Pinpoint operations sourced from:
// https://docs.aws.amazon.com/pinpoint/latest/apireference/operations.html
var pinpointOperations = []pinpointOperation{
	{Name: "CreateApp", Method: "POST", URI: "/v1/apps"},
	{Name: "CreateCampaign", Method: "POST", URI: "/v1/apps/{application-id}/campaigns"},
	{Name: "CreateEmailTemplate", Method: "POST", URI: "/v1/templates/{template-name}/email"},
	{Name: "CreateExportJob", Method: "POST", URI: "/v1/apps/{application-id}/jobs/export"},
	{Name: "CreateImportJob", Method: "POST", URI: "/v1/apps/{application-id}/jobs/import"},
	{Name: "CreateInAppTemplate", Method: "POST", URI: "/v1/templates/{template-name}/inapp"},
	{Name: "CreateJourney", Method: "POST", URI: "/v1/apps/{application-id}/journeys"},
	{Name: "CreatePushTemplate", Method: "POST", URI: "/v1/templates/{template-name}/push"},
	{Name: "CreateRecommenderConfiguration", Method: "POST", URI: "/v1/recommenders"},
	{Name: "CreateSegment", Method: "POST", URI: "/v1/apps/{application-id}/segments"},
	{Name: "CreateSmsTemplate", Method: "POST", URI: "/v1/templates/{template-name}/sms"},
	{Name: "CreateVoiceTemplate", Method: "POST", URI: "/v1/templates/{template-name}/voice"},
	{Name: "DeleteAdmChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/adm"},
	{Name: "DeleteApnsChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/apns"},
	{Name: "DeleteApnsSandboxChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/apns_sandbox"},
	{Name: "DeleteApnsVoipChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/apns_voip"},
	{Name: "DeleteApnsVoipSandboxChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/apns_voip_sandbox"},
	{Name: "DeleteApp", Method: "DELETE", URI: "/v1/apps/{application-id}"},
	{Name: "DeleteBaiduChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/baidu"},
	{Name: "DeleteCampaign", Method: "DELETE", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}"},
	{Name: "DeleteEmailChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/email"},
	{Name: "DeleteEmailTemplate", Method: "DELETE", URI: "/v1/templates/{template-name}/email"},
	{Name: "DeleteEndpoint", Method: "DELETE", URI: "/v1/apps/{application-id}/endpoints/{endpoint-id}"},
	{Name: "DeleteEventStream", Method: "DELETE", URI: "/v1/apps/{application-id}/eventstream"},
	{Name: "DeleteGcmChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/gcm"},
	{Name: "DeleteInAppTemplate", Method: "DELETE", URI: "/v1/templates/{template-name}/inapp"},
	{Name: "DeleteJourney", Method: "DELETE", URI: "/v1/apps/{application-id}/journeys/{journey-id}"},
	{Name: "DeletePushTemplate", Method: "DELETE", URI: "/v1/templates/{template-name}/push"},
	{Name: "DeleteRecommenderConfiguration", Method: "DELETE", URI: "/v1/recommenders/{recommender-id}"},
	{Name: "DeleteSegment", Method: "DELETE", URI: "/v1/apps/{application-id}/segments/{segment-id}"},
	{Name: "DeleteSmsChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/sms"},
	{Name: "DeleteSmsTemplate", Method: "DELETE", URI: "/v1/templates/{template-name}/sms"},
	{Name: "DeleteUserEndpoints", Method: "DELETE", URI: "/v1/apps/{application-id}/users/{user-id}"},
	{Name: "DeleteVoiceChannel", Method: "DELETE", URI: "/v1/apps/{application-id}/channels/voice"},
	{Name: "DeleteVoiceTemplate", Method: "DELETE", URI: "/v1/templates/{template-name}/voice"},
	{Name: "GetAdmChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/adm"},
	{Name: "GetApnsChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/apns"},
	{Name: "GetApnsSandboxChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/apns_sandbox"},
	{Name: "GetApnsVoipChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/apns_voip"},
	{Name: "GetApnsVoipSandboxChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/apns_voip_sandbox"},
	{Name: "GetApp", Method: "GET", URI: "/v1/apps/{application-id}"},
	{Name: "GetApplicationDateRangeKpi", Method: "GET", URI: "/v1/apps/{application-id}/kpis/daterange/{kpi-name}"},
	{Name: "GetApplicationSettings", Method: "GET", URI: "/v1/apps/{application-id}/settings"},
	{Name: "GetApps", Method: "GET", URI: "/v1/apps"},
	{Name: "GetBaiduChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/baidu"},
	{Name: "GetCampaign", Method: "GET", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}"},
	{Name: "GetCampaignActivities", Method: "GET", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}/activities"},
	{Name: "GetCampaignDateRangeKpi", Method: "GET", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}/kpis/daterange/{kpi-name}"},
	{Name: "GetCampaignVersion", Method: "GET", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}/versions/{version}"},
	{Name: "GetCampaignVersions", Method: "GET", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}/versions"},
	{Name: "GetCampaigns", Method: "GET", URI: "/v1/apps/{application-id}/campaigns"},
	{Name: "GetChannels", Method: "GET", URI: "/v1/apps/{application-id}/channels"},
	{Name: "GetEmailChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/email"},
	{Name: "GetEmailTemplate", Method: "GET", URI: "/v1/templates/{template-name}/email"},
	{Name: "GetEndpoint", Method: "GET", URI: "/v1/apps/{application-id}/endpoints/{endpoint-id}"},
	{Name: "GetEventStream", Method: "GET", URI: "/v1/apps/{application-id}/eventstream"},
	{Name: "GetExportJob", Method: "GET", URI: "/v1/apps/{application-id}/jobs/export/{job-id}"},
	{Name: "GetExportJobs", Method: "GET", URI: "/v1/apps/{application-id}/jobs/export"},
	{Name: "GetGcmChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/gcm"},
	{Name: "GetImportJob", Method: "GET", URI: "/v1/apps/{application-id}/jobs/import/{job-id}"},
	{Name: "GetImportJobs", Method: "GET", URI: "/v1/apps/{application-id}/jobs/import"},
	{Name: "GetInAppMessages", Method: "GET", URI: "/v1/apps/{application-id}/endpoints/{endpoint-id}/inappmessages"},
	{Name: "GetInAppTemplate", Method: "GET", URI: "/v1/templates/{template-name}/inapp"},
	{Name: "GetJourney", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}"},
	{Name: "GetJourneyDateRangeKpi", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/kpis/daterange/{kpi-name}"},
	{Name: "GetJourneyExecutionActivityMetrics", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/activities/{journey-activity-id}/execution-metrics"},
	{Name: "GetJourneyExecutionMetrics", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/execution-metrics"},
	{Name: "GetJourneyRunExecutionActivityMetrics", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/runs/{run-id}/activities/{journey-activity-id}/execution-metrics"},
	{Name: "GetJourneyRunExecutionMetrics", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/runs/{run-id}/execution-metrics"},
	{Name: "GetJourneyRuns", Method: "GET", URI: "/v1/apps/{application-id}/journeys/{journey-id}/runs"},
	{Name: "GetPushTemplate", Method: "GET", URI: "/v1/templates/{template-name}/push"},
	{Name: "GetRecommenderConfiguration", Method: "GET", URI: "/v1/recommenders/{recommender-id}"},
	{Name: "GetRecommenderConfigurations", Method: "GET", URI: "/v1/recommenders"},
	{Name: "GetSegment", Method: "GET", URI: "/v1/apps/{application-id}/segments/{segment-id}"},
	{Name: "GetSegmentExportJobs", Method: "GET", URI: "/v1/apps/{application-id}/segments/{segment-id}/jobs/export"},
	{Name: "GetSegmentImportJobs", Method: "GET", URI: "/v1/apps/{application-id}/segments/{segment-id}/jobs/import"},
	{Name: "GetSegmentVersion", Method: "GET", URI: "/v1/apps/{application-id}/segments/{segment-id}/versions/{version}"},
	{Name: "GetSegmentVersions", Method: "GET", URI: "/v1/apps/{application-id}/segments/{segment-id}/versions"},
	{Name: "GetSegments", Method: "GET", URI: "/v1/apps/{application-id}/segments"},
	{Name: "GetSmsChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/sms"},
	{Name: "GetSmsTemplate", Method: "GET", URI: "/v1/templates/{template-name}/sms"},
	{Name: "GetUserEndpoints", Method: "GET", URI: "/v1/apps/{application-id}/users/{user-id}"},
	{Name: "GetVoiceChannel", Method: "GET", URI: "/v1/apps/{application-id}/channels/voice"},
	{Name: "GetVoiceTemplate", Method: "GET", URI: "/v1/templates/{template-name}/voice"},
	{Name: "ListJourneys", Method: "GET", URI: "/v1/apps/{application-id}/journeys"},
	{Name: "ListTagsForResource", Method: "GET", URI: "/v1/tags/{resource-arn}"},
	{Name: "ListTemplateVersions", Method: "GET", URI: "/v1/templates/{template-name}/{template-type}/versions"},
	{Name: "ListTemplates", Method: "GET", URI: "/v1/templates"},
	{Name: "PhoneNumberValidate", Method: "POST", URI: "/v1/phone/number/validate"},
	{Name: "PutEventStream", Method: "POST", URI: "/v1/apps/{application-id}/eventstream"},
	{Name: "PutEvents", Method: "POST", URI: "/v1/apps/{application-id}/events"},
	{Name: "RemoveAttributes", Method: "PUT", URI: "/v1/apps/{application-id}/attributes/{attribute-type}"},
	{Name: "SendMessages", Method: "POST", URI: "/v1/apps/{application-id}/messages"},
	{Name: "SendOTPMessage", Method: "POST", URI: "/v1/apps/{application-id}/otp"},
	{Name: "SendUsersMessages", Method: "POST", URI: "/v1/apps/{application-id}/users-messages"},
	{Name: "TagResource", Method: "POST", URI: "/v1/tags/{resource-arn}"},
	{Name: "UntagResource", Method: "DELETE", URI: "/v1/tags/{resource-arn}"},
	{Name: "UpdateAdmChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/adm"},
	{Name: "UpdateApnsChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/apns"},
	{Name: "UpdateApnsSandboxChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/apns_sandbox"},
	{Name: "UpdateApnsVoipChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/apns_voip"},
	{Name: "UpdateApnsVoipSandboxChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/apns_voip_sandbox"},
	{Name: "UpdateApplicationSettings", Method: "PUT", URI: "/v1/apps/{application-id}/settings"},
	{Name: "UpdateBaiduChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/baidu"},
	{Name: "UpdateCampaign", Method: "PUT", URI: "/v1/apps/{application-id}/campaigns/{campaign-id}"},
	{Name: "UpdateEmailChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/email"},
	{Name: "UpdateEmailTemplate", Method: "PUT", URI: "/v1/templates/{template-name}/email"},
	{Name: "UpdateEndpoint", Method: "PUT", URI: "/v1/apps/{application-id}/endpoints/{endpoint-id}"},
	{Name: "UpdateEndpointsBatch", Method: "PUT", URI: "/v1/apps/{application-id}/endpoints"},
	{Name: "UpdateGcmChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/gcm"},
	{Name: "UpdateInAppTemplate", Method: "PUT", URI: "/v1/templates/{template-name}/inapp"},
	{Name: "UpdateJourney", Method: "PUT", URI: "/v1/apps/{application-id}/journeys/{journey-id}"},
	{Name: "UpdateJourneyState", Method: "PUT", URI: "/v1/apps/{application-id}/journeys/{journey-id}/state"},
	{Name: "UpdatePushTemplate", Method: "PUT", URI: "/v1/templates/{template-name}/push"},
	{Name: "UpdateRecommenderConfiguration", Method: "PUT", URI: "/v1/recommenders/{recommender-id}"},
	{Name: "UpdateSegment", Method: "PUT", URI: "/v1/apps/{application-id}/segments/{segment-id}"},
	{Name: "UpdateSmsChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/sms"},
	{Name: "UpdateSmsTemplate", Method: "PUT", URI: "/v1/templates/{template-name}/sms"},
	{Name: "UpdateTemplateActiveVersion", Method: "PUT", URI: "/v1/templates/{template-name}/{template-type}/active-version"},
	{Name: "UpdateVoiceChannel", Method: "PUT", URI: "/v1/apps/{application-id}/channels/voice"},
	{Name: "UpdateVoiceTemplate", Method: "PUT", URI: "/v1/templates/{template-name}/voice"},
	{Name: "VerifyOTPMessage", Method: "POST", URI: "/v1/apps/{application-id}/verify-otp"},
}

var pinpointOperationByName = func() map[string]pinpointOperation {
	out := make(map[string]pinpointOperation, len(pinpointOperations))
	for _, op := range pinpointOperations {
		out[op.Name] = op
	}
	return out
}()
