package server

type securityHubOperation struct {
	Name string
}

// AWS Security Hub CSPM operations sourced from:
// https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_Operations.html
var securityHubOperations = []securityHubOperation{
	{Name: "AcceptAdministratorInvitation"},
	{Name: "AcceptInvitation"},
	{Name: "BatchDeleteAutomationRules"},
	{Name: "BatchDisableStandards"},
	{Name: "BatchEnableStandards"},
	{Name: "BatchGetAutomationRules"},
	{Name: "BatchGetConfigurationPolicyAssociations"},
	{Name: "BatchGetSecurityControls"},
	{Name: "BatchGetStandardsControlAssociations"},
	{Name: "BatchImportFindings"},
	{Name: "BatchUpdateAutomationRules"},
	{Name: "BatchUpdateFindings"},
	{Name: "BatchUpdateFindingsV2"},
	{Name: "BatchUpdateStandardsControlAssociations"},
	{Name: "CreateActionTarget"},
	{Name: "CreateAggregatorV2"},
	{Name: "CreateAutomationRule"},
	{Name: "CreateAutomationRuleV2"},
	{Name: "CreateConfigurationPolicy"},
	{Name: "CreateConnectorV2"},
	{Name: "CreateFindingAggregator"},
	{Name: "CreateInsight"},
	{Name: "CreateMembers"},
	{Name: "CreateTicketV2"},
	{Name: "DeclineInvitations"},
	{Name: "DeleteActionTarget"},
	{Name: "DeleteAggregatorV2"},
	{Name: "DeleteAutomationRuleV2"},
	{Name: "DeleteConfigurationPolicy"},
	{Name: "DeleteConnectorV2"},
	{Name: "DeleteFindingAggregator"},
	{Name: "DeleteInsight"},
	{Name: "DeleteInvitations"},
	{Name: "DeleteMembers"},
	{Name: "DescribeActionTargets"},
	{Name: "DescribeHub"},
	{Name: "DescribeOrganizationConfiguration"},
	{Name: "DescribeProducts"},
	{Name: "DescribeProductsV2"},
	{Name: "DescribeSecurityHubV2"},
	{Name: "DescribeStandards"},
	{Name: "DescribeStandardsControls"},
	{Name: "DisableImportFindingsForProduct"},
	{Name: "DisableOrganizationAdminAccount"},
	{Name: "DisableSecurityHub"},
	{Name: "DisableSecurityHubV2"},
	{Name: "DisassociateFromAdministratorAccount"},
	{Name: "DisassociateFromMasterAccount"},
	{Name: "DisassociateMembers"},
	{Name: "EnableImportFindingsForProduct"},
	{Name: "EnableOrganizationAdminAccount"},
	{Name: "EnableSecurityHub"},
	{Name: "EnableSecurityHubV2"},
	{Name: "GetAdministratorAccount"},
	{Name: "GetAggregatorV2"},
	{Name: "GetAutomationRuleV2"},
	{Name: "GetConfigurationPolicy"},
	{Name: "GetConfigurationPolicyAssociation"},
	{Name: "GetConnectorV2"},
	{Name: "GetEnabledStandards"},
	{Name: "GetFindingAggregator"},
	{Name: "GetFindingHistory"},
	{Name: "GetFindingStatisticsV2"},
	{Name: "GetFindings"},
	{Name: "GetFindingsTrendsV2"},
	{Name: "GetFindingsV2"},
	{Name: "GetInsightResults"},
	{Name: "GetInsights"},
	{Name: "GetInvitationsCount"},
	{Name: "GetMasterAccount"},
	{Name: "GetMembers"},
	{Name: "GetResourcesStatisticsV2"},
	{Name: "GetResourcesTrendsV2"},
	{Name: "GetResourcesV2"},
	{Name: "GetSecurityControlDefinition"},
	{Name: "InviteMembers"},
	{Name: "ListAggregatorsV2"},
	{Name: "ListAutomationRules"},
	{Name: "ListAutomationRulesV2"},
	{Name: "ListConfigurationPolicies"},
	{Name: "ListConfigurationPolicyAssociations"},
	{Name: "ListConnectorsV2"},
	{Name: "ListEnabledProductsForImport"},
	{Name: "ListFindingAggregators"},
	{Name: "ListInvitations"},
	{Name: "ListMembers"},
	{Name: "ListOrganizationAdminAccounts"},
	{Name: "ListSecurityControlDefinitions"},
	{Name: "ListStandardsControlAssociations"},
	{Name: "ListTagsForResource"},
	{Name: "RegisterConnectorV2"},
	{Name: "StartConfigurationPolicyAssociation"},
	{Name: "StartConfigurationPolicyDisassociation"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateActionTarget"},
	{Name: "UpdateAggregatorV2"},
	{Name: "UpdateAutomationRuleV2"},
	{Name: "UpdateConfigurationPolicy"},
	{Name: "UpdateConnectorV2"},
	{Name: "UpdateFindingAggregator"},
	{Name: "UpdateFindings"},
	{Name: "UpdateInsight"},
	{Name: "UpdateOrganizationConfiguration"},
	{Name: "UpdateSecurityControl"},
	{Name: "UpdateSecurityHubConfiguration"},
	{Name: "UpdateStandardsControl"},
}

var securityHubOperationByName = func() map[string]securityHubOperation {
	out := make(map[string]securityHubOperation, len(securityHubOperations))
	for _, op := range securityHubOperations {
		out[op.Name] = op
	}
	return out
}()
