package server

type sesv2Operation struct {
	Name    string
	Method  string
	Pattern string
}

var sesv2Operations = []sesv2Operation{
	{Name: "BatchGetMetricData", Method: "POST", Pattern: "/v2/email/metrics/batch"},
	{Name: "CancelExportJob", Method: "PUT", Pattern: "/v2/email/export-jobs/{JobId}/cancel"},
	{Name: "CreateConfigurationSet", Method: "POST", Pattern: "/v2/email/configuration-sets"},
	{Name: "CreateConfigurationSetEventDestination", Method: "POST", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/event-destinations"},
	{Name: "CreateContact", Method: "POST", Pattern: "/v2/email/contact-lists/{ContactListName}/contacts"},
	{Name: "CreateContactList", Method: "POST", Pattern: "/v2/email/contact-lists"},
	{Name: "CreateCustomVerificationEmailTemplate", Method: "POST", Pattern: "/v2/email/custom-verification-email-templates"},
	{Name: "CreateDedicatedIpPool", Method: "POST", Pattern: "/v2/email/dedicated-ip-pools"},
	{Name: "CreateDeliverabilityTestReport", Method: "POST", Pattern: "/v2/email/deliverability-dashboard/test"},
	{Name: "CreateEmailIdentity", Method: "POST", Pattern: "/v2/email/identities"},
	{Name: "CreateEmailIdentityPolicy", Method: "POST", Pattern: "/v2/email/identities/{EmailIdentity}/policies/{PolicyName}"},
	{Name: "CreateEmailTemplate", Method: "POST", Pattern: "/v2/email/templates"},
	{Name: "CreateExportJob", Method: "POST", Pattern: "/v2/email/export-jobs"},
	{Name: "CreateImportJob", Method: "POST", Pattern: "/v2/email/import-jobs"},
	{Name: "CreateMultiRegionEndpoint", Method: "POST", Pattern: "/v2/email/multi-region-endpoints"},
	{Name: "CreateTenant", Method: "POST", Pattern: "/v2/email/tenants"},
	{Name: "CreateTenantResourceAssociation", Method: "POST", Pattern: "/v2/email/tenants/resources"},
	{Name: "DeleteConfigurationSet", Method: "DELETE", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}"},
	{Name: "DeleteConfigurationSetEventDestination", Method: "DELETE", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/event-destinations/{EventDestinationName}"},
	{Name: "DeleteContact", Method: "DELETE", Pattern: "/v2/email/contact-lists/{ContactListName}/contacts/{EmailAddress}"},
	{Name: "DeleteContactList", Method: "DELETE", Pattern: "/v2/email/contact-lists/{ContactListName}"},
	{Name: "DeleteCustomVerificationEmailTemplate", Method: "DELETE", Pattern: "/v2/email/custom-verification-email-templates/{TemplateName}"},
	{Name: "DeleteDedicatedIpPool", Method: "DELETE", Pattern: "/v2/email/dedicated-ip-pools/{PoolName}"},
	{Name: "DeleteEmailIdentity", Method: "DELETE", Pattern: "/v2/email/identities/{EmailIdentity}"},
	{Name: "DeleteEmailIdentityPolicy", Method: "DELETE", Pattern: "/v2/email/identities/{EmailIdentity}/policies/{PolicyName}"},
	{Name: "DeleteEmailTemplate", Method: "DELETE", Pattern: "/v2/email/templates/{TemplateName}"},
	{Name: "DeleteMultiRegionEndpoint", Method: "DELETE", Pattern: "/v2/email/multi-region-endpoints/{EndpointName}"},
	{Name: "DeleteSuppressedDestination", Method: "DELETE", Pattern: "/v2/email/suppression/addresses/{EmailAddress}"},
	{Name: "DeleteTenant", Method: "POST", Pattern: "/v2/email/tenants/delete"},
	{Name: "DeleteTenantResourceAssociation", Method: "POST", Pattern: "/v2/email/tenants/resources/delete"},
	{Name: "GetAccount", Method: "GET", Pattern: "/v2/email/account"},
	{Name: "GetBlacklistReports", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/blacklist-report"},
	{Name: "GetConfigurationSet", Method: "GET", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}"},
	{Name: "GetConfigurationSetEventDestinations", Method: "GET", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/event-destinations"},
	{Name: "GetContact", Method: "GET", Pattern: "/v2/email/contact-lists/{ContactListName}/contacts/{EmailAddress}"},
	{Name: "GetContactList", Method: "GET", Pattern: "/v2/email/contact-lists/{ContactListName}"},
	{Name: "GetCustomVerificationEmailTemplate", Method: "GET", Pattern: "/v2/email/custom-verification-email-templates/{TemplateName}"},
	{Name: "GetDedicatedIp", Method: "GET", Pattern: "/v2/email/dedicated-ips/{Ip}"},
	{Name: "GetDedicatedIpPool", Method: "GET", Pattern: "/v2/email/dedicated-ip-pools/{PoolName}"},
	{Name: "GetDedicatedIps", Method: "GET", Pattern: "/v2/email/dedicated-ips"},
	{Name: "GetDeliverabilityDashboardOptions", Method: "GET", Pattern: "/v2/email/deliverability-dashboard"},
	{Name: "GetDeliverabilityTestReport", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/test-reports/{ReportId}"},
	{Name: "GetDomainDeliverabilityCampaign", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/campaigns/{CampaignId}"},
	{Name: "GetDomainStatisticsReport", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/statistics-report/{Domain}"},
	{Name: "GetEmailAddressInsights", Method: "POST", Pattern: "/v2/email/email-address-insights/"},
	{Name: "GetEmailIdentity", Method: "GET", Pattern: "/v2/email/identities/{EmailIdentity}"},
	{Name: "GetEmailIdentityPolicies", Method: "GET", Pattern: "/v2/email/identities/{EmailIdentity}/policies"},
	{Name: "GetEmailTemplate", Method: "GET", Pattern: "/v2/email/templates/{TemplateName}"},
	{Name: "GetExportJob", Method: "GET", Pattern: "/v2/email/export-jobs/{JobId}"},
	{Name: "GetImportJob", Method: "GET", Pattern: "/v2/email/import-jobs/{JobId}"},
	{Name: "GetMessageInsights", Method: "GET", Pattern: "/v2/email/insights/{MessageId}"},
	{Name: "GetMultiRegionEndpoint", Method: "GET", Pattern: "/v2/email/multi-region-endpoints/{EndpointName}"},
	{Name: "GetReputationEntity", Method: "GET", Pattern: "/v2/email/reputation/entities/{ReputationEntityType}/{ReputationEntityReference}"},
	{Name: "GetSuppressedDestination", Method: "GET", Pattern: "/v2/email/suppression/addresses/{EmailAddress}"},
	{Name: "GetTenant", Method: "POST", Pattern: "/v2/email/tenants/get"},
	{Name: "ListConfigurationSets", Method: "GET", Pattern: "/v2/email/configuration-sets"},
	{Name: "ListContactLists", Method: "GET", Pattern: "/v2/email/contact-lists"},
	{Name: "ListContacts", Method: "POST", Pattern: "/v2/email/contact-lists/{ContactListName}/contacts/list"},
	{Name: "ListCustomVerificationEmailTemplates", Method: "GET", Pattern: "/v2/email/custom-verification-email-templates"},
	{Name: "ListDedicatedIpPools", Method: "GET", Pattern: "/v2/email/dedicated-ip-pools"},
	{Name: "ListDeliverabilityTestReports", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/test-reports"},
	{Name: "ListDomainDeliverabilityCampaigns", Method: "GET", Pattern: "/v2/email/deliverability-dashboard/domains/{SubscribedDomain}/campaigns"},
	{Name: "ListEmailIdentities", Method: "GET", Pattern: "/v2/email/identities"},
	{Name: "ListEmailTemplates", Method: "GET", Pattern: "/v2/email/templates"},
	{Name: "ListExportJobs", Method: "POST", Pattern: "/v2/email/list-export-jobs"},
	{Name: "ListImportJobs", Method: "POST", Pattern: "/v2/email/import-jobs/list"},
	{Name: "ListMultiRegionEndpoints", Method: "GET", Pattern: "/v2/email/multi-region-endpoints"},
	{Name: "ListRecommendations", Method: "POST", Pattern: "/v2/email/vdm/recommendations"},
	{Name: "ListReputationEntities", Method: "POST", Pattern: "/v2/email/reputation/entities"},
	{Name: "ListResourceTenants", Method: "POST", Pattern: "/v2/email/resources/tenants/list"},
	{Name: "ListSuppressedDestinations", Method: "GET", Pattern: "/v2/email/suppression/addresses"},
	{Name: "ListTagsForResource", Method: "GET", Pattern: "/v2/email/tags"},
	{Name: "ListTenantResources", Method: "POST", Pattern: "/v2/email/tenants/resources/list"},
	{Name: "ListTenants", Method: "POST", Pattern: "/v2/email/tenants/list"},
	{Name: "PutAccountDedicatedIpWarmupAttributes", Method: "PUT", Pattern: "/v2/email/account/dedicated-ips/warmup"},
	{Name: "PutAccountDetails", Method: "POST", Pattern: "/v2/email/account/details"},
	{Name: "PutAccountSendingAttributes", Method: "PUT", Pattern: "/v2/email/account/sending"},
	{Name: "PutAccountSuppressionAttributes", Method: "PUT", Pattern: "/v2/email/account/suppression"},
	{Name: "PutAccountVdmAttributes", Method: "PUT", Pattern: "/v2/email/account/vdm"},
	{Name: "PutConfigurationSetArchivingOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/archiving-options"},
	{Name: "PutConfigurationSetDeliveryOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/delivery-options"},
	{Name: "PutConfigurationSetReputationOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/reputation-options"},
	{Name: "PutConfigurationSetSendingOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/sending"},
	{Name: "PutConfigurationSetSuppressionOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/suppression-options"},
	{Name: "PutConfigurationSetTrackingOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/tracking-options"},
	{Name: "PutConfigurationSetVdmOptions", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/vdm-options"},
	{Name: "PutDedicatedIpInPool", Method: "PUT", Pattern: "/v2/email/dedicated-ips/{Ip}/pool"},
	{Name: "PutDedicatedIpPoolScalingAttributes", Method: "PUT", Pattern: "/v2/email/dedicated-ip-pools/{PoolName}/scaling"},
	{Name: "PutDedicatedIpWarmupAttributes", Method: "PUT", Pattern: "/v2/email/dedicated-ips/{Ip}/warmup"},
	{Name: "PutDeliverabilityDashboardOption", Method: "PUT", Pattern: "/v2/email/deliverability-dashboard"},
	{Name: "PutEmailIdentityConfigurationSetAttributes", Method: "PUT", Pattern: "/v2/email/identities/{EmailIdentity}/configuration-set"},
	{Name: "PutEmailIdentityDkimAttributes", Method: "PUT", Pattern: "/v2/email/identities/{EmailIdentity}/dkim"},
	{Name: "PutEmailIdentityDkimSigningAttributes", Method: "PUT", Pattern: "/v1/email/identities/{EmailIdentity}/dkim/signing"},
	{Name: "PutEmailIdentityFeedbackAttributes", Method: "PUT", Pattern: "/v2/email/identities/{EmailIdentity}/feedback"},
	{Name: "PutEmailIdentityMailFromAttributes", Method: "PUT", Pattern: "/v2/email/identities/{EmailIdentity}/mail-from"},
	{Name: "PutSuppressedDestination", Method: "PUT", Pattern: "/v2/email/suppression/addresses"},
	{Name: "SendBulkEmail", Method: "POST", Pattern: "/v2/email/outbound-bulk-emails"},
	{Name: "SendCustomVerificationEmail", Method: "POST", Pattern: "/v2/email/outbound-custom-verification-emails"},
	{Name: "SendEmail", Method: "POST", Pattern: "/v2/email/outbound-emails"},
	{Name: "TagResource", Method: "POST", Pattern: "/v2/email/tags"},
	{Name: "TestRenderEmailTemplate", Method: "POST", Pattern: "/v2/email/templates/{TemplateName}/render"},
	{Name: "UntagResource", Method: "DELETE", Pattern: "/v2/email/tags"},
	{Name: "UpdateConfigurationSetEventDestination", Method: "PUT", Pattern: "/v2/email/configuration-sets/{ConfigurationSetName}/event-destinations/{EventDestinationName}"},
	{Name: "UpdateContact", Method: "PUT", Pattern: "/v2/email/contact-lists/{ContactListName}/contacts/{EmailAddress}"},
	{Name: "UpdateContactList", Method: "PUT", Pattern: "/v2/email/contact-lists/{ContactListName}"},
	{Name: "UpdateCustomVerificationEmailTemplate", Method: "PUT", Pattern: "/v2/email/custom-verification-email-templates/{TemplateName}"},
	{Name: "UpdateEmailIdentityPolicy", Method: "PUT", Pattern: "/v2/email/identities/{EmailIdentity}/policies/{PolicyName}"},
	{Name: "UpdateEmailTemplate", Method: "PUT", Pattern: "/v2/email/templates/{TemplateName}"},
	{Name: "UpdateReputationEntityCustomerManagedStatus", Method: "PUT", Pattern: "/v2/email/reputation/entities/{ReputationEntityType}/{ReputationEntityReference}/customer-managed-status"},
	{Name: "UpdateReputationEntityPolicy", Method: "PUT", Pattern: "/v2/email/reputation/entities/{ReputationEntityType}/{ReputationEntityReference}/policy"},
}

var sesv2OperationByName = func() map[string]sesv2Operation {
	out := make(map[string]sesv2Operation, len(sesv2Operations))
	for _, op := range sesv2Operations {
		out[op.Name] = op
	}
	return out
}()
