package server

type smsVoiceV2Operation struct {
	Name string
}

// Amazon End User Messaging SMS actions sourced from:
// https://docs.aws.amazon.com/pinpoint/latest/apireference_smsvoicev2/API_Operations.html
var smsVoiceV2Operations = []smsVoiceV2Operation{
	{Name: "AssociateOriginationIdentity"},
	{Name: "AssociateProtectConfiguration"},
	{Name: "CreateConfigurationSet"},
	{Name: "CreateEventDestination"},
	{Name: "CreateOptOutList"},
	{Name: "CreatePool"},
	{Name: "CreateProtectConfiguration"},
	{Name: "CreateRegistration"},
	{Name: "CreateRegistrationAssociation"},
	{Name: "CreateRegistrationAttachment"},
	{Name: "CreateRegistrationVersion"},
	{Name: "CreateVerifiedDestinationNumber"},
	{Name: "DeleteAccountDefaultProtectConfiguration"},
	{Name: "DeleteConfigurationSet"},
	{Name: "DeleteDefaultMessageType"},
	{Name: "DeleteDefaultSenderId"},
	{Name: "DeleteEventDestination"},
	{Name: "DeleteKeyword"},
	{Name: "DeleteMediaMessageSpendLimitOverride"},
	{Name: "DeleteOptOutList"},
	{Name: "DeleteOptedOutNumber"},
	{Name: "DeletePool"},
	{Name: "DeleteProtectConfiguration"},
	{Name: "DeleteProtectConfigurationRuleSetNumberOverride"},
	{Name: "DeleteRegistration"},
	{Name: "DeleteRegistrationAttachment"},
	{Name: "DeleteRegistrationFieldValue"},
	{Name: "DeleteResourcePolicy"},
	{Name: "DeleteTextMessageSpendLimitOverride"},
	{Name: "DeleteVerifiedDestinationNumber"},
	{Name: "DeleteVoiceMessageSpendLimitOverride"},
	{Name: "DescribeAccountAttributes"},
	{Name: "DescribeAccountLimits"},
	{Name: "DescribeConfigurationSets"},
	{Name: "DescribeKeywords"},
	{Name: "DescribeOptOutLists"},
	{Name: "DescribeOptedOutNumbers"},
	{Name: "DescribePhoneNumbers"},
	{Name: "DescribePools"},
	{Name: "DescribeProtectConfigurations"},
	{Name: "DescribeRegistrationAttachments"},
	{Name: "DescribeRegistrationFieldDefinitions"},
	{Name: "DescribeRegistrationFieldValues"},
	{Name: "DescribeRegistrationSectionDefinitions"},
	{Name: "DescribeRegistrationTypeDefinitions"},
	{Name: "DescribeRegistrationVersions"},
	{Name: "DescribeRegistrations"},
	{Name: "DescribeSenderIds"},
	{Name: "DescribeSpendLimits"},
	{Name: "DescribeVerifiedDestinationNumbers"},
	{Name: "DisassociateOriginationIdentity"},
	{Name: "DisassociateProtectConfiguration"},
	{Name: "DiscardRegistrationVersion"},
	{Name: "GetProtectConfigurationCountryRuleSet"},
	{Name: "GetResourcePolicy"},
	{Name: "ListPoolOriginationIdentities"},
	{Name: "ListProtectConfigurationRuleSetNumberOverrides"},
	{Name: "ListRegistrationAssociations"},
	{Name: "ListTagsForResource"},
	{Name: "PutKeyword"},
	{Name: "PutMessageFeedback"},
	{Name: "PutOptedOutNumber"},
	{Name: "PutProtectConfigurationRuleSetNumberOverride"},
	{Name: "PutRegistrationFieldValue"},
	{Name: "PutResourcePolicy"},
	{Name: "ReleasePhoneNumber"},
	{Name: "ReleaseSenderId"},
	{Name: "RequestPhoneNumber"},
	{Name: "RequestSenderId"},
	{Name: "SendDestinationNumberVerificationCode"},
	{Name: "SendMediaMessage"},
	{Name: "SendTextMessage"},
	{Name: "SendVoiceMessage"},
	{Name: "SetAccountDefaultProtectConfiguration"},
	{Name: "SetDefaultMessageFeedbackEnabled"},
	{Name: "SetDefaultMessageType"},
	{Name: "SetDefaultSenderId"},
	{Name: "SetMediaMessageSpendLimitOverride"},
	{Name: "SetTextMessageSpendLimitOverride"},
	{Name: "SetVoiceMessageSpendLimitOverride"},
	{Name: "SubmitRegistrationVersion"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateEventDestination"},
	{Name: "UpdatePhoneNumber"},
	{Name: "UpdatePool"},
	{Name: "UpdateProtectConfiguration"},
	{Name: "UpdateProtectConfigurationCountryRuleSet"},
	{Name: "UpdateSenderId"},
	{Name: "VerifyDestinationNumber"},
}

var smsVoiceV2OperationByName = func() map[string]smsVoiceV2Operation {
	out := make(map[string]smsVoiceV2Operation, len(smsVoiceV2Operations))
	for _, op := range smsVoiceV2Operations {
		out[op.Name] = op
	}
	return out
}()
