package server

type storageGatewayOperation struct {
	Name string
}

// AWS Storage Gateway operations sourced from:
// https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_Operations.html
var storageGatewayOperations = []storageGatewayOperation{
	{Name: "ActivateGateway"},
	{Name: "AddCache"},
	{Name: "AddTagsToResource"},
	{Name: "AddUploadBuffer"},
	{Name: "AddWorkingStorage"},
	{Name: "AssignTapePool"},
	{Name: "AssociateFileSystem"},
	{Name: "AttachVolume"},
	{Name: "CancelArchival"},
	{Name: "CancelCacheReport"},
	{Name: "CancelRetrieval"},
	{Name: "CreateCachediSCSIVolume"},
	{Name: "CreateNFSFileShare"},
	{Name: "CreateSMBFileShare"},
	{Name: "CreateSnapshot"},
	{Name: "CreateSnapshotFromVolumeRecoveryPoint"},
	{Name: "CreateStorediSCSIVolume"},
	{Name: "CreateTapePool"},
	{Name: "CreateTapeWithBarcode"},
	{Name: "CreateTapes"},
	{Name: "DeleteAutomaticTapeCreationPolicy"},
	{Name: "DeleteBandwidthRateLimit"},
	{Name: "DeleteCacheReport"},
	{Name: "DeleteChapCredentials"},
	{Name: "DeleteFileShare"},
	{Name: "DeleteGateway"},
	{Name: "DeleteSnapshotSchedule"},
	{Name: "DeleteTape"},
	{Name: "DeleteTapeArchive"},
	{Name: "DeleteTapePool"},
	{Name: "DeleteVolume"},
	{Name: "DescribeAvailabilityMonitorTest"},
	{Name: "DescribeBandwidthRateLimit"},
	{Name: "DescribeBandwidthRateLimitSchedule"},
	{Name: "DescribeCache"},
	{Name: "DescribeCacheReport"},
	{Name: "DescribeCachediSCSIVolumes"},
	{Name: "DescribeChapCredentials"},
	{Name: "DescribeFileSystemAssociations"},
	{Name: "DescribeGatewayInformation"},
	{Name: "DescribeMaintenanceStartTime"},
	{Name: "DescribeNFSFileShares"},
	{Name: "DescribeSMBFileShares"},
	{Name: "DescribeSMBSettings"},
	{Name: "DescribeSnapshotSchedule"},
	{Name: "DescribeStorediSCSIVolumes"},
	{Name: "DescribeTapeArchives"},
	{Name: "DescribeTapeRecoveryPoints"},
	{Name: "DescribeTapes"},
	{Name: "DescribeUploadBuffer"},
	{Name: "DescribeVTLDevices"},
	{Name: "DescribeWorkingStorage"},
	{Name: "DetachVolume"},
	{Name: "DisableGateway"},
	{Name: "DisassociateFileSystem"},
	{Name: "EvictFilesFailingUpload"},
	{Name: "JoinDomain"},
	{Name: "ListAutomaticTapeCreationPolicies"},
	{Name: "ListCacheReports"},
	{Name: "ListFileShares"},
	{Name: "ListFileSystemAssociations"},
	{Name: "ListGateways"},
	{Name: "ListLocalDisks"},
	{Name: "ListTagsForResource"},
	{Name: "ListTapePools"},
	{Name: "ListTapes"},
	{Name: "ListVolumeInitiators"},
	{Name: "ListVolumeRecoveryPoints"},
	{Name: "ListVolumes"},
	{Name: "NotifyWhenUploaded"},
	{Name: "RefreshCache"},
	{Name: "RemoveTagsFromResource"},
	{Name: "ResetCache"},
	{Name: "RetrieveTapeArchive"},
	{Name: "RetrieveTapeRecoveryPoint"},
	{Name: "SetLocalConsolePassword"},
	{Name: "SetSMBGuestPassword"},
	{Name: "ShutdownGateway"},
	{Name: "StartAvailabilityMonitorTest"},
	{Name: "StartCacheReport"},
	{Name: "StartGateway"},
	{Name: "UpdateAutomaticTapeCreationPolicy"},
	{Name: "UpdateBandwidthRateLimit"},
	{Name: "UpdateBandwidthRateLimitSchedule"},
	{Name: "UpdateChapCredentials"},
	{Name: "UpdateFileSystemAssociation"},
	{Name: "UpdateGatewayInformation"},
	{Name: "UpdateGatewaySoftwareNow"},
	{Name: "UpdateMaintenanceStartTime"},
	{Name: "UpdateNFSFileShare"},
	{Name: "UpdateSMBFileShare"},
	{Name: "UpdateSMBFileShareVisibility"},
	{Name: "UpdateSMBLocalGroups"},
	{Name: "UpdateSMBSecurityStrategy"},
	{Name: "UpdateSnapshotSchedule"},
	{Name: "UpdateVTLDeviceType"},
}

var storageGatewayOperationByName = func() map[string]storageGatewayOperation {
	out := make(map[string]storageGatewayOperation, len(storageGatewayOperations))
	for _, op := range storageGatewayOperations {
		out[op.Name] = op
	}
	return out
}()
