package server

type workmailOperation struct {
	Name string
}

// Amazon WorkMail actions sourced from:
// https://docs.aws.amazon.com/workmail/latest/APIReference/API_Operations.html
var workmailOperations = []workmailOperation{
	{Name: "AssociateDelegateToResource"},
	{Name: "AssociateMemberToGroup"},
	{Name: "AssumeImpersonationRole"},
	{Name: "CancelMailboxExportJob"},
	{Name: "CreateAlias"},
	{Name: "CreateAvailabilityConfiguration"},
	{Name: "CreateGroup"},
	{Name: "CreateIdentityCenterApplication"},
	{Name: "CreateImpersonationRole"},
	{Name: "CreateMobileDeviceAccessRule"},
	{Name: "CreateOrganization"},
	{Name: "CreateResource"},
	{Name: "CreateUser"},
	{Name: "DeleteAccessControlRule"},
	{Name: "DeleteAlias"},
	{Name: "DeleteAvailabilityConfiguration"},
	{Name: "DeleteEmailMonitoringConfiguration"},
	{Name: "DeleteGroup"},
	{Name: "DeleteIdentityCenterApplication"},
	{Name: "DeleteIdentityProviderConfiguration"},
	{Name: "DeleteImpersonationRole"},
	{Name: "DeleteMailboxPermissions"},
	{Name: "DeleteMobileDeviceAccessOverride"},
	{Name: "DeleteMobileDeviceAccessRule"},
	{Name: "DeleteOrganization"},
	{Name: "DeletePersonalAccessToken"},
	{Name: "DeleteResource"},
	{Name: "DeleteRetentionPolicy"},
	{Name: "DeleteUser"},
	{Name: "DeregisterFromWorkMail"},
	{Name: "DeregisterMailDomain"},
	{Name: "DescribeEmailMonitoringConfiguration"},
	{Name: "DescribeEntity"},
	{Name: "DescribeGroup"},
	{Name: "DescribeIdentityProviderConfiguration"},
	{Name: "DescribeInboundDmarcSettings"},
	{Name: "DescribeMailboxExportJob"},
	{Name: "DescribeOrganization"},
	{Name: "DescribeResource"},
	{Name: "DescribeUser"},
	{Name: "DisassociateDelegateFromResource"},
	{Name: "DisassociateMemberFromGroup"},
	{Name: "GetAccessControlEffect"},
	{Name: "GetDefaultRetentionPolicy"},
	{Name: "GetImpersonationRole"},
	{Name: "GetImpersonationRoleEffect"},
	{Name: "GetMailDomain"},
	{Name: "GetMailboxDetails"},
	{Name: "GetMobileDeviceAccessEffect"},
	{Name: "GetMobileDeviceAccessOverride"},
	{Name: "GetPersonalAccessTokenMetadata"},
	{Name: "ListAccessControlRules"},
	{Name: "ListAliases"},
	{Name: "ListAvailabilityConfigurations"},
	{Name: "ListGroupMembers"},
	{Name: "ListGroups"},
	{Name: "ListGroupsForEntity"},
	{Name: "ListImpersonationRoles"},
	{Name: "ListMailDomains"},
	{Name: "ListMailboxExportJobs"},
	{Name: "ListMailboxPermissions"},
	{Name: "ListMobileDeviceAccessOverrides"},
	{Name: "ListMobileDeviceAccessRules"},
	{Name: "ListOrganizations"},
	{Name: "ListPersonalAccessTokens"},
	{Name: "ListResourceDelegates"},
	{Name: "ListResources"},
	{Name: "ListTagsForResource"},
	{Name: "ListUsers"},
	{Name: "PutAccessControlRule"},
	{Name: "PutEmailMonitoringConfiguration"},
	{Name: "PutIdentityProviderConfiguration"},
	{Name: "PutInboundDmarcSettings"},
	{Name: "PutMailboxPermissions"},
	{Name: "PutMobileDeviceAccessOverride"},
	{Name: "PutRetentionPolicy"},
	{Name: "RegisterMailDomain"},
	{Name: "RegisterToWorkMail"},
	{Name: "ResetPassword"},
	{Name: "StartMailboxExportJob"},
	{Name: "TagResource"},
	{Name: "TestAvailabilityConfiguration"},
	{Name: "UntagResource"},
	{Name: "UpdateAvailabilityConfiguration"},
	{Name: "UpdateDefaultMailDomain"},
	{Name: "UpdateGroup"},
	{Name: "UpdateImpersonationRole"},
	{Name: "UpdateMailboxQuota"},
	{Name: "UpdateMobileDeviceAccessRule"},
	{Name: "UpdatePrimaryEmailAddress"},
	{Name: "UpdateResource"},
	{Name: "UpdateUser"},
}

var workmailOperationByName = func() map[string]workmailOperation {
	out := make(map[string]workmailOperation, len(workmailOperations))
	for _, op := range workmailOperations {
		out[op.Name] = op
	}
	return out
}()
