package server

type workspacesAppStream2Operation struct {
	Name string
}

// Amazon WorkSpaces Applications actions sourced from:
// https://docs.aws.amazon.com/appstream2/latest/APIReference/API_Operations.html
var workspacesAppStream2Operations = []workspacesAppStream2Operation{
	{Name: "AssociateAppBlockBuilderAppBlock"},
	{Name: "AssociateApplicationFleet"},
	{Name: "AssociateApplicationToEntitlement"},
	{Name: "AssociateFleet"},
	{Name: "AssociateSoftwareToImageBuilder"},
	{Name: "BatchAssociateUserStack"},
	{Name: "BatchDisassociateUserStack"},
	{Name: "CopyImage"},
	{Name: "CreateAppBlock"},
	{Name: "CreateAppBlockBuilder"},
	{Name: "CreateAppBlockBuilderStreamingURL"},
	{Name: "CreateApplication"},
	{Name: "CreateDirectoryConfig"},
	{Name: "CreateEntitlement"},
	{Name: "CreateExportImageTask"},
	{Name: "CreateFleet"},
	{Name: "CreateImageBuilder"},
	{Name: "CreateImageBuilderStreamingURL"},
	{Name: "CreateImportedImage"},
	{Name: "CreateStack"},
	{Name: "CreateStreamingURL"},
	{Name: "CreateThemeForStack"},
	{Name: "CreateUpdatedImage"},
	{Name: "CreateUsageReportSubscription"},
	{Name: "CreateUser"},
	{Name: "DeleteAppBlock"},
	{Name: "DeleteAppBlockBuilder"},
	{Name: "DeleteApplication"},
	{Name: "DeleteDirectoryConfig"},
	{Name: "DeleteEntitlement"},
	{Name: "DeleteFleet"},
	{Name: "DeleteImage"},
	{Name: "DeleteImageBuilder"},
	{Name: "DeleteImagePermissions"},
	{Name: "DeleteStack"},
	{Name: "DeleteThemeForStack"},
	{Name: "DeleteUsageReportSubscription"},
	{Name: "DeleteUser"},
	{Name: "DescribeAppBlockBuilderAppBlockAssociations"},
	{Name: "DescribeAppBlockBuilders"},
	{Name: "DescribeAppBlocks"},
	{Name: "DescribeApplicationFleetAssociations"},
	{Name: "DescribeApplications"},
	{Name: "DescribeAppLicenseUsage"},
	{Name: "DescribeDirectoryConfigs"},
	{Name: "DescribeEntitlements"},
	{Name: "DescribeFleets"},
	{Name: "DescribeImageBuilders"},
	{Name: "DescribeImagePermissions"},
	{Name: "DescribeImages"},
	{Name: "DescribeSessions"},
	{Name: "DescribeSoftwareAssociations"},
	{Name: "DescribeStacks"},
	{Name: "DescribeThemeForStack"},
	{Name: "DescribeUsageReportSubscriptions"},
	{Name: "DescribeUsers"},
	{Name: "DescribeUserStackAssociations"},
	{Name: "DisableUser"},
	{Name: "DisassociateAppBlockBuilderAppBlock"},
	{Name: "DisassociateApplicationFleet"},
	{Name: "DisassociateApplicationFromEntitlement"},
	{Name: "DisassociateFleet"},
	{Name: "DisassociateSoftwareFromImageBuilder"},
	{Name: "EnableUser"},
	{Name: "ExpireSession"},
	{Name: "GetExportImageTask"},
	{Name: "ListAssociatedFleets"},
	{Name: "ListAssociatedStacks"},
	{Name: "ListEntitledApplications"},
	{Name: "ListExportImageTasks"},
	{Name: "ListTagsForResource"},
	{Name: "StartAppBlockBuilder"},
	{Name: "StartFleet"},
	{Name: "StartImageBuilder"},
	{Name: "StartSoftwareDeploymentToImageBuilder"},
	{Name: "StopAppBlockBuilder"},
	{Name: "StopFleet"},
	{Name: "StopImageBuilder"},
	{Name: "TagResource"},
	{Name: "UntagResource"},
	{Name: "UpdateAppBlockBuilder"},
	{Name: "UpdateApplication"},
	{Name: "UpdateDirectoryConfig"},
	{Name: "UpdateEntitlement"},
	{Name: "UpdateFleet"},
	{Name: "UpdateImagePermissions"},
	{Name: "UpdateStack"},
	{Name: "UpdateThemeForStack"},
}

var workspacesAppStream2OperationByName = func() map[string]workspacesAppStream2Operation {
	out := make(map[string]workspacesAppStream2Operation, len(workspacesAppStream2Operations))
	for _, op := range workspacesAppStream2Operations {
		out[op.Name] = op
	}
	return out
}()
