package server

type workspacesOperation struct {
	Name string
}

// Amazon WorkSpaces Service actions sourced from:
// https://docs.aws.amazon.com/workspaces/latest/api/API_Operations.html
var workspacesOperations = []workspacesOperation{
	{Name: "AcceptAccountLinkInvitation"},
	{Name: "AssociateConnectionAlias"},
	{Name: "AssociateIpGroups"},
	{Name: "AssociateWorkspaceApplication"},
	{Name: "AuthorizeIpRules"},
	{Name: "CopyWorkspaceImage"},
	{Name: "CreateAccountLinkInvitation"},
	{Name: "CreateConnectClientAddIn"},
	{Name: "CreateConnectionAlias"},
	{Name: "CreateIpGroup"},
	{Name: "CreateStandbyWorkspaces"},
	{Name: "CreateTags"},
	{Name: "CreateUpdatedWorkspaceImage"},
	{Name: "CreateWorkspaceBundle"},
	{Name: "CreateWorkspaceImage"},
	{Name: "CreateWorkspaces"},
	{Name: "CreateWorkspacesPool"},
	{Name: "DeleteAccountLinkInvitation"},
	{Name: "DeleteClientBranding"},
	{Name: "DeleteConnectClientAddIn"},
	{Name: "DeleteConnectionAlias"},
	{Name: "DeleteIpGroup"},
	{Name: "DeleteTags"},
	{Name: "DeleteWorkspaceBundle"},
	{Name: "DeleteWorkspaceImage"},
	{Name: "DeployWorkspaceApplications"},
	{Name: "DeregisterWorkspaceDirectory"},
	{Name: "DescribeAccount"},
	{Name: "DescribeAccountModifications"},
	{Name: "DescribeApplicationAssociations"},
	{Name: "DescribeApplications"},
	{Name: "DescribeBundleAssociations"},
	{Name: "DescribeClientBranding"},
	{Name: "DescribeClientProperties"},
	{Name: "DescribeConnectClientAddIns"},
	{Name: "DescribeConnectionAliasPermissions"},
	{Name: "DescribeConnectionAliases"},
	{Name: "DescribeCustomWorkspaceImageImport"},
	{Name: "DescribeImageAssociations"},
	{Name: "DescribeIpGroups"},
	{Name: "DescribeTags"},
	{Name: "DescribeWorkspaceAssociations"},
	{Name: "DescribeWorkspaceBundles"},
	{Name: "DescribeWorkspaceDirectories"},
	{Name: "DescribeWorkspaceImagePermissions"},
	{Name: "DescribeWorkspaceImages"},
	{Name: "DescribeWorkspaceSnapshots"},
	{Name: "DescribeWorkspaces"},
	{Name: "DescribeWorkspacesConnectionStatus"},
	{Name: "DescribeWorkspacesPoolSessions"},
	{Name: "DescribeWorkspacesPools"},
	{Name: "DisassociateConnectionAlias"},
	{Name: "DisassociateIpGroups"},
	{Name: "DisassociateWorkspaceApplication"},
	{Name: "GetAccountLink"},
	{Name: "ImportClientBranding"},
	{Name: "ImportCustomWorkspaceImage"},
	{Name: "ImportWorkspaceImage"},
	{Name: "ListAccountLinks"},
	{Name: "ListAvailableManagementCidrRanges"},
	{Name: "MigrateWorkspace"},
	{Name: "ModifyAccount"},
	{Name: "ModifyCertificateBasedAuthProperties"},
	{Name: "ModifyClientProperties"},
	{Name: "ModifyEndpointEncryptionMode"},
	{Name: "ModifySamlProperties"},
	{Name: "ModifySelfservicePermissions"},
	{Name: "ModifyStreamingProperties"},
	{Name: "ModifyWorkspaceAccessProperties"},
	{Name: "ModifyWorkspaceCreationProperties"},
	{Name: "ModifyWorkspaceProperties"},
	{Name: "ModifyWorkspaceState"},
	{Name: "RebootWorkspaces"},
	{Name: "RebuildWorkspaces"},
	{Name: "RegisterWorkspaceDirectory"},
	{Name: "RejectAccountLinkInvitation"},
	{Name: "RestoreWorkspace"},
	{Name: "RevokeIpRules"},
	{Name: "StartWorkspaces"},
	{Name: "StartWorkspacesPool"},
	{Name: "StopWorkspaces"},
	{Name: "StopWorkspacesPool"},
	{Name: "TerminateWorkspaces"},
	{Name: "TerminateWorkspacesPool"},
	{Name: "TerminateWorkspacesPoolSession"},
	{Name: "UpdateConnectClientAddIn"},
	{Name: "UpdateConnectionAliasPermission"},
	{Name: "UpdateRulesOfIpGroup"},
	{Name: "UpdateWorkspaceBundle"},
	{Name: "UpdateWorkspaceImagePermission"},
	{Name: "UpdateWorkspacesPool"},
}

var workspacesOperationByName = func() map[string]workspacesOperation {
	out := make(map[string]workspacesOperation, len(workspacesOperations))
	for _, op := range workspacesOperations {
		out[op.Name] = op
	}
	return out
}()
