services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  sns-basic:
    build:
      context: ../../..
      dockerfile: examples/sns/sns-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_TOPIC=demo-sns-basic
