services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  swf:
    build:
      context: ../../../..
      dockerfile: examples/aws/swf/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_DOMAIN=demo-swf
      - STACKYARD_WORKFLOW=demo-workflow
      - STACKYARD_WORKFLOW_VERSION=1
      - STACKYARD_ACTIVITY=demo-activity
      - STACKYARD_ACTIVITY_VERSION=1
      - STACKYARD_TASK_LIST=advanced-tasks
