services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,azure
      - STACKYARD_AZURE_AUTH_MODE=shared_key

  resource-manager-2024-03-01:
    build:
      context: ../../../..
      dockerfile: examples/azure/api-center/resource-manager-2024-03-01/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_AZURE_APICENTER_ACCOUNT=devstoreaccount1
      - STACKYARD_AZURE_APICENTER_SUBSCRIPTION_KEY=stackyard-local-subscription-key
      - STACKYARD_AZURE_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - STACKYARD_AZURE_RESOURCE_GROUP=rg-apic
      - STACKYARD_AZURE_APICENTER_SERVICE=contoso
      - STACKYARD_AZURE_APICENTER_WORKSPACE=default
      - STACKYARD_AZURE_APICENTER_API=echo-api
      - STACKYARD_AZURE_APICENTER_VERSION=2023-01-01
      - STACKYARD_AZURE_APICENTER_DEFINITION=openapi
      - STACKYARD_AZURE_APICENTER_DEPLOYMENT=production
      - STACKYARD_AZURE_APICENTER_ENVIRONMENT=public
      - STACKYARD_AZURE_APICENTER_METADATA_SCHEMA=author
