services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  ecs-advanced:
    build:
      context: ../../../..
      dockerfile: examples/aws/ecs/ecs-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_CLUSTER_NAME=ecs-advanced-cluster
      - STACKYARD_TASK_FAMILY=ecs-advanced-task
      - STACKYARD_SERVICE_NAME=ecs-advanced-service
      - STACKYARD_NAMESPACE=ecs-advanced-ns
