services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  locationfinder-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/locationfinder-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-central1
      - STACKYARD_GCP_LOCATIONFINDER_CLOUD_LOCATION_ID=us-east1
      - STACKYARD_GCP_LOCATIONFINDER_SOURCE_CLOUD_LOCATION_ID=us-central1
      - STACKYARD_GCP_LOCATIONFINDER_QUERY=latency
