services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  videointelligence-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/videointelligence-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-east1
      - STACKYARD_GCP_VIDEO_INPUT_URI=gs://stackyard-inputs/video-1.mp4
      - STACKYARD_GCP_VIDEO_OUTPUT_URI=gs://stackyard-outputs/video-1.json
