services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  dataproc-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/dataproc-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_REGION=us-central1
      - STACKYARD_GCP_LOCATION=us-central1
      - STACKYARD_GCP_DATAPROC_CLUSTER_ID=team-cluster
      - STACKYARD_GCP_DATAPROC_JOB_ID=team-job
      - STACKYARD_GCP_DATAPROC_TEMPLATE_ID=team-template
      - STACKYARD_GCP_DATAPROC_POLICY_ID=team-policy
      - STACKYARD_GCP_DATAPROC_BATCH_ID=team-batch
