services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  osconfig-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/osconfig-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=us-central1-a
      - STACKYARD_GCP_INSTANCE_ID=instance-1
      - STACKYARD_GCP_OSCONFIG_PATCH_JOB_ID=patch-job-1
      - STACKYARD_GCP_OSCONFIG_PATCH_DEPLOYMENT_ID=patch-deployment-1
      - STACKYARD_GCP_OSCONFIG_ASSIGNMENT_ID=assignment-1
