services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  artifactregistry-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/artifactregistry-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_LOCATION=projects/stackyard/locations/us-central1
      - STACKYARD_GCP_REPOSITORY_ID=team-repo
      - STACKYARD_GCP_PACKAGE_ID=orders
      - STACKYARD_GCP_VERSION_ID=1.0.0
      - STACKYARD_GCP_TAG_ID=latest
