services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  filestore-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/filestore-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_FILESTORE_ZONE=us-central1-c
      - STACKYARD_GCP_FILESTORE_REGION=us-central1
      - STACKYARD_GCP_FILESTORE_INSTANCE_ID=team-instance
      - STACKYARD_GCP_FILESTORE_SNAPSHOT_ID=team-snapshot
      - STACKYARD_GCP_FILESTORE_BACKUP_ID=team-backup
      - STACKYARD_GCP_FILESTORE_OPERATION_ID=op-1
