services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  eventbridge-basic:
    build:
      context: ../../../..
      dockerfile: examples/aws/eventbridge/eventbridge-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_EVENT_BUS=demo-eventbridge-basic
      - STACKYARD_RULE=demo-rule-basic
