services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  transfer-advanced:
    build:
      context: ../../..
      dockerfile: examples/transfer/transfer-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - AWS_REGION=us-east-1
      - STACKYARD_SERVER_ID=s-00000000000000000
