services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  global-accelerator:
    build:
      context: ../../../..
      dockerfile: examples/aws/global-accelerator/global-accelerator/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - AWS_REGION=us-west-2
      - STACKYARD_GLOBAL_ACCELERATOR_ARN=arn:aws:globalaccelerator::123456789012:accelerator/stackyard-accelerator
      - STACKYARD_GLOBAL_ACCELERATOR_LISTENER_ARN=arn:aws:globalaccelerator::123456789012:accelerator/stackyard-accelerator/listener/stackyard-listener
