services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
      - "4567:4567"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  aiplatform-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/aiplatform-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_GRPC_ENDPOINT=stackyard:4567
      - STACKYARD_GCP_PARENT=projects/stackyard/locations/us-central1
