services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  dlp-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/dlp-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_LOCATION=global
      - STACKYARD_GCP_DLP_TEMPLATE_ID=inspect-template-1
      - STACKYARD_GCP_DLP_JOB_TRIGGER_ID=job-trigger-1
      - STACKYARD_GCP_DLP_JOB_ID=dlp-job-1
      - STACKYARD_GCP_DLP_STORED_INFO_TYPE_ID=stored-info-type-1
