services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  memorydb:
    build:
      context: ../../../..
      dockerfile: examples/aws/memorydb/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_MEMORYDB_CLUSTER=memorydb-cluster
      - STACKYARD_MEMORYDB_ACL=memorydb-acl
