services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  configdelivery-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/configdelivery-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_CONFIGDELIVERY_LOCATION=us-central1
      - STACKYARD_GCP_CONFIGDELIVERY_RESOURCE_BUNDLE_ID=platform-bundle
      - STACKYARD_GCP_CONFIGDELIVERY_RELEASE_ID=r-1
      - STACKYARD_GCP_CONFIGDELIVERY_VARIANT_ID=default
      - STACKYARD_GCP_CONFIGDELIVERY_FLEET_PACKAGE_ID=platform-package
      - STACKYARD_GCP_CONFIGDELIVERY_ROLLOUT_ID=rollout-1
