services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  maps-fleetengine-delivery-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/maps-fleetengine-delivery-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_PROVIDER_ID=stackyard
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_VEHICLE_ID=delivery-vehicle-1
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_TASK_ID=task-1
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_BATCH_TASK_ID=task-batch-1
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_TRACKING_ID=tracking-1
      - STACKYARD_GCP_FLEETENGINE_DELIVERY_BATCH_TRACKING_ID=tracking-batch-1
