services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  recommendationengine-apiv1beta1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/recommendationengine-apiv1beta1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_PROJECT_ID=stackyard
      - STACKYARD_GCP_CATALOG_ID=default_catalog
      - STACKYARD_GCP_EVENT_STORE_ID=default_event_store
      - STACKYARD_GCP_PLACEMENT_ID=home_page
      - STACKYARD_GCP_CATALOG_ITEM_ID=item-1
      - STACKYARD_GCP_PREDICTION_API_KEY=stackyard-api-key
