services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  neptuneanalytics-basic:
    build:
      context: ../../../..
      dockerfile: examples/aws/neptuneanalytics/neptuneanalytics-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_NEPTUNEANALYTICS_GRAPH_NAME=stackyard-neptuneanalytics-basic
      - STACKYARD_NEPTUNEANALYTICS_IMPORT_SOURCE=s3://stackyard-neptuneanalytics-basic/import
      - STACKYARD_NEPTUNEANALYTICS_ROLE_ARN=arn:aws:iam::123456789012:role/stackyard-neptuneanalytics
