services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,azure
      - STACKYARD_AZURE_AUTH_MODE=shared_key

  ai-services-language-analyze-text-authoring-2023-04-01:
    build:
      context: ../../../..
      dockerfile: examples/azure/ai-services/language-analyze-text-authoring-2023-04-01/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_AZURE_AISERVICES_ACCOUNT=devstoreaccount1
      - STACKYARD_AZURE_AISERVICES_SUBSCRIPTION_KEY=stackyard-local-subscription-key
      - STACKYARD_AZURE_LANGUAGE_AUTHORING_PROJECT=proj-a
      - STACKYARD_AZURE_LANGUAGE_AUTHORING_MODEL_LABEL=model-v1
      - STACKYARD_AZURE_LANGUAGE_AUTHORING_DEPLOYMENT=prod
      - STACKYARD_AZURE_LANGUAGE_AUTHORING_JOB_ID=job-123
      - STACKYARD_AZURE_LANGUAGE_AUTHORING_RESOURCE=authoring-resource-a
