services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,azure
      - STACKYARD_AZURE_AUTH_MODE=shared_key

  speech-to-text-v3-2-preview-2:
    build:
      context: ../../../..
      dockerfile: examples/azure/ai-services/speech-to-text-v3.2-preview.2/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_AZURE_AISERVICES_ACCOUNT=devstoreaccount1
      - STACKYARD_AZURE_AISERVICES_SUBSCRIPTION_KEY=stackyard-local-subscription-key
      - STACKYARD_AZURE_SPEECH_TO_TEXT_LOCALE=en-US
      - STACKYARD_AZURE_SPEECH_TO_TEXT_TRANSCRIPTION_ID=transcription-a
      - STACKYARD_AZURE_SPEECH_TO_TEXT_PROJECT_ID=project-a
      - STACKYARD_AZURE_SPEECH_TO_TEXT_WEBHOOK_ID=webhook-a
