services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  swf-basic:
    build:
      context: ../../../..
      dockerfile: examples/aws/swf/swf-basic/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_DOMAIN=demo-swf-basic
      - STACKYARD_WORKFLOW=demo-workflow-basic
      - STACKYARD_WORKFLOW_VERSION=1
      - STACKYARD_TASK_LIST=basic-tasks
