services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_PROVIDERS=aws,gcp
      - STACKYARD_GCP_AUTH_MODE=emulator

  commerce-consumer-procurement-apiv1:
    build:
      context: ../../../..
      dockerfile: examples/gcp/commerce-consumer-procurement-apiv1/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_GCP_BILLING_ACCOUNT_ID=0123456789
      - STACKYARD_GCP_PROCUREMENT_ORDER_ID=order-1
      - STACKYARD_GCP_PROCUREMENT_OPERATION_ID=op-1
