services:
  stackyard:
    build:
      context: ../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  keyspaces-advanced:
    build:
      context: ../../..
      dockerfile: examples/keyspaces/keyspaces-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_KEYSPACES_KEYSPACE=stackyard_keyspace
      - STACKYARD_KEYSPACES_TABLE=stackyard_table
