services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug
      - STACKYARD_LAMBDA_EXECUTION_MODE=local

  lambda-advanced:
    build:
      context: ../../../..
      dockerfile: examples/aws/lambda/lambda-advanced/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_FUNCTION_NAME=lambda-advanced-function
      - STACKYARD_ALIAS_NAME=live
