services:
  stackyard:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    container_name: stackyard
    ports:
      - "4566:4566"
    environment:
      - STACKYARD_LOG_LEVEL=debug

  neptune:
    build:
      context: ../../../..
      dockerfile: examples/aws/neptune/Dockerfile
    depends_on:
      - stackyard
    environment:
      - STACKYARD_ENDPOINT=http://stackyard:4566
      - STACKYARD_NEPTUNE_CLUSTER=neptune-cluster
      - STACKYARD_NEPTUNE_CLUSTER_ARN=arn:aws:rds:us-east-1:123456789012:cluster:neptune-cluster
