name: Docker Runs

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  examples-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run examples docker suite
        run: make examples-docker
