name: Docker Runs (AWS)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  examples-docker-aws:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run AWS examples docker suite
        run: make examples-docker-aws
